IF NOT EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[DRT2019]') AND TYPE IN (N'U'))
BEGIN
     CREATE TABLE [dbo].[DRT2019]
     (
      [APK] UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL,
      [DivisionID] VARCHAR(50) NULL,
      [TranMonth] INT NOT NULL,
      [TranYear] INT NOT NULL,
      [Row] INT NULL,
      [TeamID] VARCHAR(50) NULL,
      [DebtRecoveryType] VARCHAR(50) NULL,
      [CustomerID] VARCHAR(50) NULL,
      [CustomerName] NVARCHAR(250) NULL,
      [ContractNo] VARCHAR(50) NULL,
      [DebtorID] VARCHAR(50) NULL,
      [DebtorName] NVARCHAR(250) NULL,
      [ContractQuantity] INT NULL,
      [FeePlace] NVARCHAR(250) NULL,
      [DebtAmount] DECIMAL(28,8) NULL,
      [DebtPeriod] INT NULL,
      [DebtDate] NVARCHAR(250) NULL,
      [LoanBeginDate] DATETIME NULL,
      [LoanEndDate] DATETIME NULL,
      [UnPaidAmount] DECIMAL(28,8) NULL,
      [UnPaidElse] DECIMAL(28,8) NULL,
      [PunishFee] DECIMAL(28,8) NULL,
      [OverDueProfit] DECIMAL(28,8) NULL,
      [ContractBeginDate] DATETIME NULL,
      [ContractEndDate] DATETIME NULL,
      [NearPaidDate] DATETIME NULL,
      [NearPaidAmount] DECIMAL(28,8) NULL,
      [PaidPeriodTotal] INT NULL,
      [PaidAmount] DECIMAL(28,8) NULL,
      [UnPaidPeriodTotal] INT NULL,
      [FirstPaidPeriod] DATETIME NULL,
      [NextPaidPeriod] DATETIME NULL,
      [AccountingDate] DATETIME NULL,
      [OverDueDays] INT NULL,
      [OverDueDate] DATETIME NULL,
      [BankAccount] NVARCHAR(100) NULL,
      [Note] NVARCHAR(500) NULL,
      [OtherNote] NVARCHAR(500) NULL,
      [WorkHistory] NVARCHAR(2000) NULL,
      [IdentifyCardNo] NVARCHAR(250) NULL,
      [IdentifyCardDate] DATETIME NULL,
      [Birthday] DATETIME NULL,
      [RegistrationBook] NVARCHAR(250) NULL,
      [HouseholdName] NVARCHAR(250) NULL,
      [WorkPlace] NVARCHAR(250) NULL,
      [WorkNote] NVARCHAR(250) NULL,
      [Duty] NVARCHAR(250) NULL,
      [AddQuantity] INT NULL,
      [AssetInfo] NVARCHAR(500) NULL,
      [Asset] NVARCHAR(250) NULL,
      [BikeType] NVARCHAR(250) NULL,
      [BikeName] NVARCHAR(250) NULL,
      [BikeColor] NVARCHAR(250) NULL,
      [BikeEngineNo] NVARCHAR(250) NULL,
      [NumberPlate] NVARCHAR(250) NULL,
      [CavetStatus] NVARCHAR(250) NULL,
      [BikePrice] DECIMAL(28,8) NULL,
      [PrePaid] DECIMAL(28,8) NULL,
      [Address01] NVARCHAR(500) NULL,
      [Ward01] NVARCHAR(250) NULL,
      [District01] NVARCHAR(250) NULL,
      [City01] NVARCHAR(250) NULL,
      [Address02] NVARCHAR(500) NULL,
      [Ward02] NVARCHAR(250) NULL,
      [District02] NVARCHAR(250) NULL,
      [City02] NVARCHAR(250) NULL,
      [Address03] NVARCHAR(500) NULL,
      [Ward03] NVARCHAR(250) NULL,
      [District03] NVARCHAR(250) NULL,
      [City03] NVARCHAR(250) NULL,
      [Address04] NVARCHAR(500) NULL,
      [Ward04] NVARCHAR(250) NULL,
      [District04] NVARCHAR(250) NULL,
      [City04] NVARCHAR(250) NULL,
      [Address05] NVARCHAR(500) NULL,
      [Ward05] NVARCHAR(250) NULL,
      [District05] NVARCHAR(250) NULL,
      [City05] NVARCHAR(250) NULL,
      [Address06] NVARCHAR(500) NULL,
      [Ward06] NVARCHAR(250) NULL,
      [District06] NVARCHAR(250) NULL,
      [City06] NVARCHAR(250) NULL,
      [Address07] NVARCHAR(500) NULL,
      [Ward07] NVARCHAR(250) NULL,
      [District07] NVARCHAR(250) NULL,
      [City07] NVARCHAR(250) NULL,
      [Address08] NVARCHAR(500) NULL,
      [Ward08] NVARCHAR(250) NULL,
      [District08] NVARCHAR(250) NULL,
      [City08] NVARCHAR(250) NULL,
      [Address09] NVARCHAR(500) NULL,
      [Ward09] NVARCHAR(250) NULL,
      [District09] NVARCHAR(250) NULL,
      [City09] NVARCHAR(250) NULL,
      [Address10] NVARCHAR(500) NULL,
      [Ward10] NVARCHAR(250) NULL,
      [District10] NVARCHAR(250) NULL,
      [City10] NVARCHAR(250) NULL,
      [Receiver01] NVARCHAR(250) NULL,
      [Receiver02] NVARCHAR(250) NULL,
      [Receiver03] NVARCHAR(250) NULL,
      [Receiver04] NVARCHAR(250) NULL,
      [Receiver05] NVARCHAR(250) NULL,
      [Receiver06] NVARCHAR(250) NULL,
      [Receiver07] NVARCHAR(250) NULL,
      [Receiver08] NVARCHAR(250) NULL,
      [Receiver09] NVARCHAR(250) NULL,
      [Receiver10] NVARCHAR(250) NULL,
      [Fax01] NVARCHAR(100) NULL,
      [Fax02] NVARCHAR(100) NULL,
      [ComEmail] NVARCHAR(100) NULL,
      [HomeEmail] NVARCHAR(100) NULL,
      [MobiPhone01] NVARCHAR(250) NULL,
      [MobiPhone02] NVARCHAR(250) NULL,
      [ComPhone01] NVARCHAR(250) NULL,
      [ComPhone02] NVARCHAR(250) NULL,
      [HomePhone01] NVARCHAR(250) NULL,
      [HomePhone02] NVARCHAR(250) NULL,
      [TransactionKey] NVARCHAR(50) NULL,
      [CreateDate] DATETIME NULL,
      [TransactionID] VARCHAR(50) NULL,
      [ErrorColumn] NVARCHAR(4000) NULL,
      [ErrorMessage] NVARCHAR(4000) NULL,
      [ContractReceiveDate] DATETIME NULL
    CONSTRAINT [PK_DRT2019] PRIMARY KEY CLUSTERED
      (
      [APK]
      )
WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
     )
 ON [PRIMARY]
END