---- Create by Kiều Nga on 28/04/2021 
---- Tính khoản trả khác

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[AT0415]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[AT0415]
(
  [APK] UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL,
  [DivisionID] VARCHAR(50) NOT NULL,
  [TranMonth] INT NULL,
  [TranYear] INT NULL,
  [Period] VARCHAR(50) NOT NULL, -- Kỳ
  [Type] VARCHAR(50) NOT NULL,  -- Loại
  [EmployeeID] VARCHAR(50) NULL, -- Nhân viên
  [ApportionID] VARCHAR(50) NULL, -- Mã số phân bổ
  [DepartmentID] VARCHAR(50) NULL, -- Phòng ban
  [ConvertedAmount] DECIMAL (28, 8) NULL, -- Số tiền
  [CreateUserID] VARCHAR(50) NULL,
  [CreateDate] DATETIME NULL,
  [LastModifyUserID] VARCHAR(50) NULL,
  [LastModifyDate] DATETIME NULL
CONSTRAINT [PK_AT0415] PRIMARY KEY CLUSTERED
(
  [APK]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END

