-- <Summary>
---- Danh mục nhà lồng
-- <History>
---- Create on Hồng Thảo on 05/12/2018

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[AT0417]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[AT0417](
	[APK] [uniqueidentifier] DEFAULT NEWID(),
    [DivisionID] VARCHAR(50) NOT NULL,
	[BlockID] VARCHAR(50) NOT NULL,
	[BlockName] NVARCHAR(250) NOT NULL,
	[IsCommon] TINYINT DEFAULT (0) NULL,
    [Disabled] TINYINT DEFAULT (0) NULL,	
    [CreateUserID] VARCHAR(50) NULL,
    [CreateDate] DATETIME NULL,
    [LastModifyUserID] VARCHAR(50) NULL,
    [LastModifyDate] DATETIME NULL
	CONSTRAINT [PK_AT0417] PRIMARY KEY NONCLUSTERED 
(
	[BlockID] ASC
    )WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON

)) ON [PRIMARY]
END





