---- Create by Nguyễn Hoàng Bảo Thy on 12/29/2016 2:28:08 PM
---- Chi tiết mặt hàng trong kho cho thuê (EIMSKIP)

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[AT1025]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[AT1025]
(
  [APK] UNIQUEIDENTIFIER DEFAULT newid() NOT NULL,
  [DivisionID] VARCHAR(50) NOT NULL,
  [ContractID] VARCHAR(50) NOT NULL,
  [TransactionID] VARCHAR(50) NOT NULL,
  [InventoryID] VARCHAR(50) NOT NULL,
  [UnitID] VARCHAR(50) NULL,
  [UnitPrice] DECIMAL(28,8) NULL,
  [Quantity] DECIMAL(28,8) NULL,
  [ConvertCoefficient] DECIMAL(28,8) NULL,
  [Amount] DECIMAL(28,8) NULL,
  [Notes] NVARCHAR(250) NULL,
  [CreateDate] DATETIME NULL,
  [CreateUserID] VARCHAR(50) NULL,
  [LastModifyDate] DATETIME NULL,
  [LastModifyUserID] VARCHAR(50) NULL
CONSTRAINT [PK_AT1025] PRIMARY KEY CLUSTERED
(
  [DivisionID],
  [ContractID],
  [TransactionID]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END