---- Create by Dũng DV on 20/09/2019
---- Điều phối nhân viên

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[POST2053]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[POST2053]
(
  [APK] UNIQUEIDENTIFIER DEFAULT newid() NOT NULL,
  [DivisionID] VARCHAR(50) NOT NULL,
  [VoucherNo] VARCHAR(50) NOT NULL,
  [GuaranteeEmployeeID] VARCHAR(50) NOT NULL,
  [RepairEmployeeID] VARCHAR(50) NULL,
  [DeliveryEmployeeID] VARCHAR(50) NULL,
    
  [IsCommon] TINYINT DEFAULT (0) NULL,
  [Disabled] TINYINT DEFAULT (0) NULL,
 
  [CreateUserID] VARCHAR(50) NULL,
  [CreateDate] DATETIME DEFAULT GETDATE() NOT NULL,
  [LastModifyDate] DATETIME NULL,
  [LastModifyUserID] VARCHAR(50) NULL
CONSTRAINT [PK_POST2053] PRIMARY KEY CLUSTERED
(
  [DivisionID],
  [VoucherNo]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END


