---- Create by Tieumai on 6/11/2018 1:15:14 PM
---- Lưu thông tin chi tiết chốt ca bán hàng

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[POST2034]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[POST2034]
(
  [APK] UNIQUEIDENTIFIER DEFAULT newid() NOT NULL,
  [DivisionID] NVARCHAR(50) NOT NULL,
  [ShopID] NVARCHAR(50) NOT NULL,
  [ShiftID] NVARCHAR(50) NOT NULL,
  [ShiftDate] DATETIME NOT NULL,
  [TypeID] TINYINT DEFAULT (0) NOT NULL,
  [Orders] INT NULL,
  [FaceValue] DECIMAL(28,8) NULL,
  [Quantity] DECIMAL(28,8) NULL,
  [OriginalAmount] DECIMAL(28,8) NULL,
  [ConvertedAmount] DECIMAL(28,8) NULL,
  [InventoryID] NVARCHAR(50) NULL,
  [UnitID] NVARCHAR(50) NULL,
  [BeginQuantity] DECIMAL(28,8) NULL,
  [ImQuantity] DECIMAL(28,8) NULL,
  [ExQuantity] DECIMAL(28,8) NULL,
  [ReturnQuantity] DECIMAL(28,8) NULL,
  [MovedQuantity] DECIMAL(28,8) NULL,
  [EndQuantity] DECIMAL(28,8) NULL
CONSTRAINT [PK_POST2034] PRIMARY KEY CLUSTERED
(
  [APK]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END
