---- Create by Cao Thị Phượng on 8/21/2017 10:37:22 AM
---- Danh sách người quản lý (Cập nhật cửa hàng_KIMYEN)

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[POST00101]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[POST00101]
(
  [APK] UNIQUEIDENTIFIER DEFAULT newid() NOT NULL,
  [DivisionID] VARCHAR(50) NOT NULL,
  [ShopID] VARCHAR(50) NOT NULL,
  [EmployeeID] VARCHAR(50) NULL,
  [EmployeeName] NVARCHAR(250) NULL,
  [FromDate] DATETIME NULL,
  [ToDate] DATETIME NULL,
  [IsUsed] TINYINT DEFAULT (0) NULL,
  [DeleteFlg] TINYINT DEFAULT (0) NULL,
  [CreateUserID] VARCHAR(50) NULL,
  [CreateDate] DATETIME NULL,
  [LastModifyUserID] VARCHAR(50) NULL,
  [LastModifyDate] DATETIME NULL
CONSTRAINT [PK_POST00101] PRIMARY KEY CLUSTERED
(
  [APK]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END