---- Create by Cao Thị Phượng on 8/14/2017 10:29:20 AM
---- Danh sách mức huê hồng theo doanh thu tích lũy (Customize Kim Yến)

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[POST01201]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[POST01201]
(
  [APK] UNIQUEIDENTIFIER DEFAULT newid() NOT NULL,
  [DivisionID] VARCHAR(50) NOT NULL,
  [ShopID] VARCHAR(50) NOT NULL,
  [FromIncome] DECIMAL(28,8) NULL,
  [ToIncome] DECIMAL(28,8) NULL,
  [CommissionRate] DECIMAL(28,8) NULL,
  [Description] NVARCHAR(max) NULL,
  [IsCommon] TINYINT DEFAULT (0) NULL,
  [Disabled] TINYINT DEFAULT (0) NULL,
  [CreateDate] DATETIME NULL,
  [CreateUserID] VARCHAR(50) NULL,
  [LastModifyDate] DATETIME NULL,
  [LastModifyUserID] VARCHAR(50) NULL,
  [RelatedToTypeID] INT DEFAULT 31 NULL
CONSTRAINT [PK_POST01201] PRIMARY KEY CLUSTERED
(
  [APK]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END