IF NOT EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[POST0016_Del]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[POST0016_Del](
	[APK] [uniqueidentifier] NOT NULL,
	[DivisionID] [varchar](50) NOT NULL,
	[ShopID] [varchar](50) NOT NULL,
	[VoucherTypeID] [varchar](50) NOT NULL,
	[TranMonth] [int] NOT NULL,
	[TranYear] [int] NOT NULL,
	[VoucherNo] [varchar](50) NOT NULL,
	[VoucherDate] [datetime] NOT NULL,
	[ObjectID] [varchar](50) NULL,
	[ObjectName] [nvarchar](250) NULL,
	[PaymentObjectID01] [varchar](50) NULL,
	[PaymentObjectName01] [nvarchar](250) NULL,
	[EmployeeID] [varchar](50) NULL,
	[EmployeeName] [nvarchar](250) NULL,
	[MemberID] [varchar](50) NOT NULL,
	[MemberName] [nvarchar](250) NULL,
	[APKPaymentID] [uniqueidentifier] NULL,
	[CurrencyID] [varchar](50) NOT NULL,
	[CurrencyName] [nvarchar](250) NULL,
	[ExchangeRate] [decimal](28, 8) NOT NULL,
	[TotalAmount] [decimal](28, 8) NULL,
	[TotalTaxAmount] [decimal](28, 8) NULL,
	[TotalDiscountAmount] [decimal](28, 8) NULL,
	[TotalInventoryAmount] [decimal](28, 8) NULL,
	[AccruedScore] [int] NULL,
	[PayScore] [int] NULL,
	[LastAccruedScore] [int] NULL,
	[AmountOfPoint] [decimal](28, 8) NULL,
	[VoucherID] [varchar](50) NULL,
	[DeleteFlg] [tinyint] NOT NULL,
	[CreateUserID] [varchar](50) NULL,
	[CreateDate] [datetime] NULL,
	[LastModifyUserID] [varchar](50) NULL,
	[LastModifyDate] [datetime] NULL,
	[Change] [decimal](28, 6) NULL,
	[PaymentObjectID02] [varchar](50) NULL,
	[PaymentObjectName02] [nvarchar](250) NULL,
	[TotalDiscountRate] [decimal](28, 6) NULL,
	[TotalRedureRate] [decimal](28, 6) NULL,
	[TotalRedureAmount] [decimal](28, 6) NULL,
	[PaymentObjectAmount01] [decimal](28, 6) NULL,
	[PaymentObjectAmount02] [decimal](28, 6) NULL,
	[AccountNumber01] [nvarchar](250) NULL,
	[AccountNumber02] [nvarchar](250) NULL,
	[IsTransferred] [tinyint] NULL,
	[AreaID] [varchar](50) NULL,
	[TableID] [varchar](50) NULL,
	[OrderPrintDate] [datetime] NULL,
	[VoucherPrintDate] [datetime] NULL,
	[VoucherSaveDate] [datetime] NULL,
	[PVoucherNo] [varchar](50) NULL,
	[CVoucherNo] [varchar](50) NULL,
	[ChangeAmount] [decimal](28, 6) NULL,
	[Description] [nvarchar](250) NULL,
	[SaleManID] [varchar](50) NULL,
	[IsWarehouseExported] [tinyint] NULL,
	[PromoteChangeAmount] [decimal](28, 8) NULL,
	[APPSuggestID] [uniqueidentifier] NULL,
	[BookingAmount] [decimal](28, 8) NULL,
	[DeliveryAddress] [nvarchar](250) NULL,
	[DeliveryContact] [nvarchar](250) NULL,
	[DeliveryMobile] [nvarchar](250) NULL,
	[DeliveryReceiver] [nvarchar](250) NULL,
	[Notes] [nvarchar](250) NULL,
	[DeliveryStatus] [int] NULL,
	[IsPaymentObject01] [tinyint] NULL,
	[IsPaymentObject02] [tinyint] NULL,
	[IsTaxIncluded] [tinyint] NULL,
	[IsCutDataERP] [tinyint] NULL,
	[TotalGiftVoucherAmount] [decimal](28, 8) NULL
) ON [PRIMARY]
END