---- Create by Nguyễn Tấn Lộc on 1/22/2021 3:14:43 PM
---- Bảng liên kết nghiệp vụ

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[OOT0088]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[OOT0088]
(
  [APK] UNIQUEIDENTIFIER DEFAULT newid() NOT NULL,
  [APKParent] UNIQUEIDENTIFIER NULL,
  [BusinessParent] VARCHAR(50) NULL,
  [TableBusinessParent] VARCHAR(50) NULL,
  [APKChild] UNIQUEIDENTIFIER NULL,
  [BusinessChild] VARCHAR(50) NULL,
  [TableBusinessChild] VARCHAR(50) NULL,
  [DataRefer01] NVARCHAR(MAX) NULL,
  [DataRefer02] NVARCHAR(MAX) NULL,
  [DataRefer03] NVARCHAR(MAX) NULL,
  [DataRefer04] NVARCHAR(MAX) NULL,
  [DataRefer05] NVARCHAR(MAX) NULL
CONSTRAINT [PK_OOT0088] PRIMARY KEY CLUSTERED
(
  [APK]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END