---- Create by Hồng Thảo on 21/2/2020
---- Thời gian làm việc

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[OOT0034]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[OOT0034]
(
  [APK] UNIQUEIDENTIFIER DEFAULT newid() NOT NULL,
  [APKMaster] VARCHAR(50) NOT NULL,
  [DayStart] INT NULL,
  [DayEnd] INT NULL,
  [IsDay] TINYINT DEFAULT (0) NULL,
  [PercentValue] VARCHAR(50) NULL
CONSTRAINT [PK_OOT0034] PRIMARY KEY CLUSTERED
(
  [APK]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END











