---- Create by Cao Thị Phượng on 9/22/2017 3:56:29 PM
---- Thiết lập ngày nghỉ trong năm

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[OOT0031]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[OOT0031]
(
  [APK] UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL,
  [APKMaster] UNIQUEIDENTIFIER NULL,
  [Orders] INT NULL,
  [StartDayOff] DATETIME NULL,
  [EndDayOff] DATETIME NULL,
  [Description] NVARCHAR(MAX) NULL,
  [IsCompens] TINYINT DEFAULT 0 NULL,
  [Notes] NVARCHAR(MAX) NULL
CONSTRAINT [PK_OOT0031] PRIMARY KEY CLUSTERED
(
  [APK]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END