---- Create by Cao Thị Phượng on 10/3/2017 10:43:54 AM
---- Danh mục bước quy trình

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[OOT1030]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[OOT1030]
(
  [APK] UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL,
  [APKMaster] UNIQUEIDENTIFIER NULL,
  [DivisionID] VARCHAR(50) NOT NULL,
  [StepID] VARCHAR(50) NOT NULL,
  [StepName] NVARCHAR(250) NOT NULL,
  [Description] NVARCHAR(MAX) NULL,
  [Orders] INT NULL,
  [RelatedToTypeID] INT NULL,
  [IsCommon] TINYINT DEFAULT 0 NULL,
  [Disabled] TINYINT DEFAULT 0 NULL,
  [CreateUserID] VARCHAR(50) NULL,
  [CreateDate] DATETIME NULL,
  [LastModifyUserID] VARCHAR(50) NULL,
  [LastModifyDate] DATETIME NULL
CONSTRAINT [PK_OOT1030] PRIMARY KEY CLUSTERED
(
  [DivisionID],
  [StepID]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END