---- Create by Cao Thị Phượng on 10/2/2017 11:16:38 AM
---- Danh mục quy trình

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[OOT1020]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[OOT1020]
(
  [APK] UNIQUEIDENTIFIER DEFAULT newid() NOT NULL,
  [DivisionID] VARCHAR(50) NOT NULL,
  [ProcessID] VARCHAR(50) NOT NULL,
  [ProcessName] NVARCHAR(250) NOT NULL,
  [Description] NVARCHAR(MAX) NULL,
  [RelatedToTypeID] INT DEFAULT 43 NULL,
  [Disabled] TINYINT DEFAULT 0 NULL,
  [IsCommon] TINYINT DEFAULT 0 NULL,
  [CreateDate] DATETIME NULL,
  [CreateUserID] VARCHAR(50) NULL,
  [LastModifyDate] DATETIME NULL,
  [LastModifyUserID] VARCHAR(50) NULL
CONSTRAINT [PK_OOT1020] PRIMARY KEY CLUSTERED
(
  [DivisionID],
  [ProcessID]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END