---- Create by Cao Thị Phượng on 9/28/2017 4:45:55 PM
---- Danh mục mẫu dự án/nhóm công việc

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[OOT1050]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[OOT1050]
(
  [APK] UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL,
  [DivisionID] VARCHAR(50) NOT NULL,
  [ProjectSampleID] VARCHAR(50) NOT NULL,
  [ProjectSampleName] NVARCHAR(250) NOT NULL,
  [Description] NVARCHAR(MAX) NULL,
  [Disabled] TINYINT DEFAULT 0 NULL,
  [IsCommon] TINYINT DEFAULT 0 NULL,
  [RelatedToTypeID] INT DEFAULT 46 NULL,
  [CreateUserID] VARCHAR(50) NULL,
  [CreateDate] DATETIME NULL,
  [LastModifyUserID] VARCHAR(50) NULL,
  [LastModifyDate] DATETIME NULL
CONSTRAINT [PK_OOT1050] PRIMARY KEY CLUSTERED
(
  [DivisionID],
  [ProjectSampleID]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END