---- Create by Quang on 3/24/2023 2:02:45 PM
---- OOT1100

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[OOT1100]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[OOT1100]
(
  [APK] UNIQUEIDENTIFIER DEFAULT newid() NOT NULL,
  [DivisionID] NVARCHAR(50) NOT NULL,
  [FromToDate] DATETIME NULL,
  [GroupID] NVARCHAR(50) NULL,
  [GroupName] NVARCHAR(50) NULL,
  [CreateUserID] NVARCHAR(50) NULL,
  [CreateDate] DATETIME NULL,
  [LastModifyDate] DATETIME NULL,
  [LastModifyUserID] NVARCHAR(250) NULL
CONSTRAINT [PK_OOT1100] PRIMARY KEY CLUSTERED
(
 [APK]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END