---- Create by Quang on 3/24/2023 2:17:07 PM
---- OOT1102

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[OOT1102]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[OOT1102]
(
  [APK] UNIQUEIDENTIFIER DEFAULT newid() NOT NULL,
  [APKMaster] NVARCHAR(150) NOT NULL,
  [EmployeeID] NVARCHAR(50) NULL,
  [EmployeeName] NVARCHAR(150) NULL,
  [DepartmentName] NVARCHAR(150) NULL,
  [Address] NVARCHAR(250) NULL,
  [Tel] NVARCHAR(50) NULL,
  [Email] NVARCHAR(150) NULL
CONSTRAINT [PK_OOT1102] PRIMARY KEY CLUSTERED
(
	[APK]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END