---- Create by Trần Đình Hoà on 12/10/2020 9:46:00 AM
---- Bảng quản lí đặt/booking thiết bị

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[OOT2240]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[OOT2240]
(
  [APK] UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL,
  [DivisionID] VARCHAR(50) NOT NULL,
  [BookingID] VARCHAR(50) NULL,
  [BookingName] NVARCHAR(250) NULL,
  [AreaID] VARCHAR(50) NULL,
  [BookingUserID] VARCHAR(50) NULL,
  [UseUserID] VARCHAR(50) NULL,
  [EquipmentTypeID] VARCHAR(50) NULL,
  [EquipmentNameID] VARCHAR(50) NULL,
  [IsRepeat] TINYINT DEFAULT 0 NULL,
  [APKSettingTime] VARCHAR(50) NULL,
  [TypeID] TINYINT DEFAULT 0 NULL,
  [Description] NVARCHAR(MAX) NULL,
  [PlanStartDate] DATETIME NULL,
  [PlanEndDate] DATETIME NULL, 
  [IsAllDay] TINYINT DEFAULT 0 NULL,
  [BookingStatus] TINYINT DEFAULT 0 NULL,
  [DeleteFlg] TINYINT DEFAULT 0 NULL,
  [CreateUserID] VARCHAR(50) NULL,
  [CreateDate] DATETIME NULL,
  [LastModifyUserID] VARCHAR(50) NULL,
  [LastModifyDate] DATETIME NULL
CONSTRAINT [PK_OOT3040] PRIMARY KEY CLUSTERED
(
  [APK]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END

IF EXISTS (SELECT TOP 1 1 FROM sysobjects WHERE NAME='OOT2240' AND xtype='U')
	BEGIN
		IF EXISTS (SELECT TOP 1 1 FROM syscolumns col INNER JOIN sysobjects tab 
		ON col.id=tab.id WHERE tab.name='OOT2240' AND col.name='Description')
		ALTER TABLE OOT2240 ALTER COLUMN Description NVARCHAR(MAX) NULL
	END