---- Create by Nguyễn Tấn Lộc on 8/31/2020 9:59:28 AM
---- Danh sách Email hộp thư đi

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[OOT2230]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[OOT2230]
(
  [APK] UNIQUEIDENTIFIER DEFAULT newid() NOT NULL,
  [DivisionID] VARCHAR(50) NULL,
  [UIDMail] INT NOT NULL,
  [SubjectName] NVARCHAR(MAX) NULL,
  [From] NVARCHAR(MAX) NULL,
  [To] NVARCHAR(MAX) NULL,
  [Cc] NVARCHAR(MAX) NULL,
  [Bcc] NVARCHAR(MAX) NULL,
  [UserID] VARCHAR(50) NULL,
  [StatusID] VARCHAR(50) NULL,
  [TypeOfProtocol] VARCHAR(50) NULL,
  [Description] NVARCHAR(MAX) NULL,
  [APKRel] VARCHAR(250) NULL,
  [RelTableID] VARCHAR(250) NULL,
  [EmailTemplateID] NVARCHAR(MAX) NULL,
  [NoOfAttachFile] INT NULL,
  [DeleteFlg] TINYINT DEFAULT (0) NULL,
  [CreateDate] DATETIME NULL,
  [CreateUserID] VARCHAR(50) NULL,
  [LastModifyDate] DATETIME NULL,
  [LastModifyUserID] VARCHAR(50) NULL
CONSTRAINT [PK_OOT2230] PRIMARY KEY CLUSTERED
(
  [APK],
  [UIDMail]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END