---- Create by Khâu Vĩnh Tâm on 3/4/2019 4:22:23 PM
---- Danh sách công việc dự án/nhóm công việc

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[OOT2102]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[OOT2102]
(
  [APK] UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL,
  [APKMaster] UNIQUEIDENTIFIER NULL,
  [NodeParent] UNIQUEIDENTIFIER NULL,
  [NodeLevel] INT NULL,
  [NodeOrder] INT NULL,
  [ObjectID] VARCHAR(50) NULL,
  [ObjectName] NVARCHAR(250) NULL,
  [ObjectTypeID] VARCHAR(50) NULL,
  [Description] NVARCHAR(MAX) NULL,
  [TaskTypeID] VARCHAR(50) NULL,
  [TargetTypeID] VARCHAR(50) NULL,
  [PriorityID] INT NULL,
  [AssignedToUserID] VARCHAR(50) NULL,
  [SupportUserID] VARCHAR(250) NULL,
  [ReviewerUserID] VARCHAR(250) NULL,
  [PercentProgress] DECIMAL(28,8) NULL,
  [StatusID] VARCHAR(50) NULL,
  [PlanStartDate] DATETIME NULL,
  [PlanEndDate] DATETIME NULL,
  [ActualStartDate] DATETIME NULL,
  [ActualEndDate] DATETIME NULL,
  [CreateUserID] VARCHAR(50) NULL,
  [CreateDate] DATETIME NULL,
  [LastModifyUserID] VARCHAR(50) NULL,
  [LastModifyDate] DATETIME NULL,
  [DeleteFlg] TINYINT NULL DEFAULT 0
CONSTRAINT [PK_OOT2102] PRIMARY KEY CLUSTERED
(
  [APK]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END
