---- Create by Nguyễn Tấn Lộc on 1/2/2020 9:33:05 AM
---- Quản lý release

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[OOT2210]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[OOT2210]
(
  [APK] UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL,
  [DivisionID] VARCHAR(50) NULL,
  [ReleaseID] VARCHAR(50) NULL,
  [ReleaseName] NVARCHAR(MAX) NULL,
  [TypeOfRelease] VARCHAR(50) NULL,
  [ProjectID] VARCHAR(50) NULL,
  [MilestoneID] VARCHAR(50) NULL,
  [AssignedToUserID] VARCHAR(250) NULL,
  [ReleaseVersion] NVARCHAR(250) NULL,
  [Description] NVARCHAR(MAX) NULL,
  [DeleteFlg] TINYINT DEFAULT 0 NULL,
  [CreateDate] DATETIME NULL,
  [CreateUserID] VARCHAR(50) NULL,
  [LastModifyDate] DATETIME NULL,
  [LastModifyUserID] VARCHAR(50) NULL
CONSTRAINT [PK_OOT2210] PRIMARY KEY CLUSTERED
(
  [APK]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END