---- Create by Văn Tài on 18/05/2022 19h09
---- Danh sách file văn bản ký đính kèm

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[OOT2342]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[OOT2342]
(
  [APK] UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL,
  [DivisionID] VARCHAR(50) NOT NULL,
  [DocumentID] VARCHAR(50) NOT NULL,
  [AttachID] INT Identity(1,1) NOT NULL,
  [AttachFile] VARBINARY(8000) NULL,
  [AttachName] NVARCHAR(MAX) NULL,
  [IsDelete]	INT NOT NULL,
  [RelatedToID] VARCHAR(50) NULL,
  [CreateDate] DATETIME NULL,
  [CreateUserID] VARCHAR(50) NULL,
  [LastModifyDate] DATETIME NULL,
  [LastModifyUserID] VARCHAR(50) NULL
CONSTRAINT [PK_OOT2342] PRIMARY KEY CLUSTERED
(
  [APK]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END