---- Create by Khâu Vĩnh Tâm on 10/16/2019 10:06:42 AM
---- Khóa sổ module OO

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[OOT9999]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[OOT9999]
(
  [APK] UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL,
  [DivisionID] VARCHAR(50) NOT NULL,
  [TranMonth] INT NULL,
  [TranYear] INT NULL,
  [Closing] TINYINT DEFAULT 0 NULL,
  [BeginDate] DATETIME NULL,
  [EndDate] DATETIME NULL
CONSTRAINT [PK_OOT9999] PRIMARY KEY CLUSTERED
(
  [APK],
  [DivisionID]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END