---- Create by Như Hàn on 07/01/2019 
---- Danh mục Nguồn thanh toán
IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[LMT1030]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[LMT1030]
(
  [APK] UNIQUEIDENTIFIER DEFAULT newid() NOT NULL,
  [DivisionID] NVARCHAR(50) NOT NULL,
  [Paymentsource] NVARCHAR(100) NOT NULL,
  [Descriptions] NVARCHAR(2000) NULL,
  [Notes] NVARCHAR(2000) NULL,
  [Disabled] INT NULL,
  [IsCommon] INT NULL,
  [CreateDate] DATETIME NULL,
  [CreateUserID] NVARCHAR(50) NULL,
  [LastModifyDate] DATETIME NULL,
  [LastModifyUserID] NVARCHAR(50) NULL
CONSTRAINT [PK_LMT1030] PRIMARY KEY CLUSTERED
(
  [APK]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END

