IF EXISTS (SELECT TOP 1 1 FROM DBO.SYSOBJECTS WHERE ID = OBJECT_ID(N'[DBO].[OOV9999]') AND OBJECTPROPERTY(ID, N'IsView') = 1)
DROP VIEW [DBO].[OOV9999]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

-- <Summary>
-- Tạo View lấy danh sách Kỳ của module OO
-- <Param>
-- <Return>
-- <Reference>
-- <History>
-- Created by Vĩnh Tâm on 05/08/2004

CREATE VIEW [dbo].[OOV9999] AS

SELECT 
	CASE
		WHEN TranMonth < 10
			THEN '0'+ LTRIM(RTRIM(STR(TRANMONTH))) + '/' + LTRIM(RTRIM(STR(TRANYEAR)))
		ELSE LTRIM(RTRIM(STR(TRANMONTH))) + '/' + LTRIM(RTRIM(STR(TRANYEAR)))
	END AS MonthYear
	, DivisionID, TranMonth, TranYear, Closing, BeginDate, EndDate
FROM OOT9999

GO
SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
