IF EXISTS (SELECT TOP 1 1 FROM DBO.SYSOBJECTS WHERE ID = OBJECT_ID(N'[DBO].[POP1000]') AND OBJECTPROPERTY(ID, N'IsProcedure') = 1)
DROP PROCEDURE [DBO].[POP1000]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


---- Created on 11/12/2018 by Như Hàn
---- Kiểm tra xóa danh mục
---- POP1000 'AS','LMT1001',''
---- POP1000 @DivisionID, @TableID, @KeyValues

CREATE PROCEDURE [dbo].[POP1000] 
	@DivisionID nvarchar(50), 
	@TableID nvarchar(50), 
	@KeyValues XML 
  AS
  
CREATE TABLE #POP1000 (PlanID VARCHAR(50))
INSERT INTO #POP1000 (PlanID)
SELECT X.Data.query('PlanID').value('.', 'NVARCHAR(50)') AS PlanID
FROM @KeyValues.nodes('//Data') AS X (Data)



CREATE TABLE #POP1000_Errors (Status TINYINT, Params VARCHAR(50), MessageID VARCHAR(50), APK VARCHAR(50))

If @TableID ='POT1001' ---  Bước kế hoạch nhận hàng
	BEGIN

			SELECT APK, DivisionID, PlanID
			INTO #POT1001
			FROM POT1001 WITH (NOLOCK) WHERE PlanID IN (SELECT PlanID FROM #POP1000)

			---- Kiểm tra danh mục đã được sử dụng
		IF EXISTS (SELECT TOP 1 1  FROM POT1011 WHERE PlanID IN (SELECT PlanID FROM #POP1000))
		BEGIN
				INSERT INTO #POP1000_Errors (Status, Params, MessageID, APK)
				SELECT DISTINCT 1 AS Status, #POT1001.PlanID AS Params,'00ML000179'AS MessageID, #POT1001.APK
				FROM #POT1001
				INNER JOIN POT1011 WITH (NOLOCK) ON POT1011.DivisionID = #POT1001.DivisionID AND #POT1001.PlanID = POT1011.PlanID

		END

			---- Kiểm tra khác đơn vị
		IF EXISTS (SELECT TOP 1 1 FROM #POT1001 WHERE DivisionID <> @DivisionID AND DivisionID <> '@@@')
		BEGIN
			INSERT INTO #POP1000_Errors (Status, Params, MessageID, APK)
			SELECT DISTINCT 1 AS Status, #POT1001.PlanID AS Params,'00ML000050'AS MessageID, #POT1001.APK
			FROM #POT1001 WHERE #POT1001.DivisionID != @DivisionID
		END

		DELETE T1
		FROM POT1001 T1
		INNER JOIN #POT1001 T2 ON T1.APK = T2.APK AND T1.DivisionID = T2.DivisionID AND T1.PlanID = T2.PlanID
		WHERE NOT EXISTS (SELECT TOP 1 1 FROM #POP1000_Errors T3 WHERE T1.APK = T3.APK) 

	END
SELECT * FROM #POP1000_Errors

GO
SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO

