---- Create by Thái Huỳnh Khả Vi on 11/13/2017 2:14:58 PM
---- Mã phân tích phụ thuộc

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[CT0145]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[CT0145]
(
  [APK] UNIQUEIDENTIFIER DEFAULT newid() NOT NULL,
  [DivisionID] NVARCHAR(50) NOT NULL,
  [ObjectID] NVARCHAR(50) NULL,
  [TypeID] NVARCHAR(50) NULL,
  [AnaID] NVARCHAR(50) NULL, 
  [CreateUserID] NVARCHAR(50) NULL,
  [LastModifyUserID] NVARCHAR(50) NULL,
  [CreateDate] DATETIME NULL,
  [LastModifyDate] DATETIME NULL
CONSTRAINT [PK_CT0145] PRIMARY KEY CLUSTERED
(
  [APK],
  [DivisionID]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END


