---- Create by Như Hàn on 10/12/2018
---- Detail mẫu kế hoạch nhận hàng

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[POT1011]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[POT1011]
(
  [APK] UNIQUEIDENTIFIER DEFAULT newid() NOT NULL,
  [APKMaster] UNIQUEIDENTIFIER NOT NULL,
  [DivisionID] VARCHAR(50) NOT NULL,
  [OrderID] INT NULL,
  [PlanID] VARCHAR(50) NOT NULL,
  [NDay] INT NULL,
  [Notes] NVARCHAR(250) NULL

CONSTRAINT [PK_POT1011] PRIMARY KEY CLUSTERED
(
  [APK]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END

