---- Create by Tieumai on 7/4/2018 10:21:26 AM
---- Đơn đặt hàng sỉ/nội bộ

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[POT2015]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[POT2015]
(
  [APK] UNIQUEIDENTIFIER DEFAULT newid() NOT NULL,
  [DivisionID] VARCHAR(50) NOT NULL,
  [VoucherTypeID] VARCHAR(50) NULL,
  [VoucherNo] VARCHAR(50) NOT NULL,
  [VoucherDate] DATETIME NULL,
  [TranMonth] TINYINT NULL,
  [TranYear] INT NULL,
  [Description] NVARCHAR(250) NULL,
  [OrderType] TINYINT DEFAULT (0) NULL,
  [OrderStatus] TINYINT DEFAULT (0) NULL,
  [CurrencyID] NVARCHAR(50) NULL,
  [ExchangeRate] DECIMAL(28,8) NULL,
  [EmployeeID] NVARCHAR(50) NULL,
  [ObjectID] NVARCHAR(50) NULL,
  [ContactPerson] NVARCHAR(250) NULL,
  [ContactPersonTel] NVARCHAR(250) NULL,
  [DeliveryAddress] NVARCHAR(250) NULL,
  [PaymentID] NVARCHAR(50) NULL,
  [PaymentTermID] NVARCHAR(50) NULL,
  [CreateUserID] VARCHAR(50) NULL,
  [CreateDate] DATETIME NULL,
  [LastmodifyUserID] VARCHAR(50) NULL,
  [LastmodifyDate] DATETIME NULL,
  [IsObjectConfirm] TINYINT NULL,
  [NoteConfirm] NVARCHAR(250) NULL,
  [DateConfirm] DATETIME NULL
CONSTRAINT [PK_POT2015] PRIMARY KEY CLUSTERED
(
  [APK]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END
