---- Create by Tieumai on 7/12/2018 1:09:48 PM
---- Kế hoạch mua hàng dự trữ (detail)

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[POT2018]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[POT2018]
(
  [APK] UNIQUEIDENTIFIER DEFAULT newid() NOT NULL,
  [DivisionID] NVARCHAR(50) NULL,
  [APK_Master] UNIQUEIDENTIFIER DEFAULT newid() NULL,
  [InventoryID] NVARCHAR(50) NULL,
  [UnitID] NVARCHAR(50) NULL,
  [ObjectID] NVARCHAR(50) NULL,
  [ID_LeadtimeMOQ] UNIQUEIDENTIFIER NULL,
  [AVGQuantity] DECIMAL(28,8) NULL,
  [OrderQuantity] DECIMAL(28,8) NULL,
  [ExpectDate] DATETIME NULL,
  [Notes] NVARCHAR(250) NULL,
  [Ana01ID] NVARCHAR(50) NULL,
  [Ana02ID] NVARCHAR(50) NULL,
  [Ana03ID] NVARCHAR(50) NULL,
  [Ana04ID] NVARCHAR(50) NULL,
  [Ana05ID] NVARCHAR(50) NULL,
  [Ana06ID] NVARCHAR(50) NULL,
  [Ana07ID] NVARCHAR(50) NULL,
  [Ana08ID] NVARCHAR(50) NULL,
  [Ana09ID] NVARCHAR(50) NULL,
  [Ana10ID] NVARCHAR(50) NULL,
  [InheritTableID] NVARCHAR(50) NULL,
  [InheritTransactionID] NVARCHAR(50) NULL,
  [InheritVoucherID] NVARCHAR(50) NULL
CONSTRAINT [PK_POT2018] PRIMARY KEY CLUSTERED
(
  [APK]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END


