IF EXISTS (SELECT TOP 1 1 FROM DBO.SYSOBJECTS WHERE ID = OBJECT_ID(N'[DBO].[NMP1011]') AND  OBJECTPROPERTY(ID, N'IsProcedure') = 1)			
DROP PROCEDURE [DBO].[NMP1011]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

-- <Summary>
---- Xuất Excel danh mục thực phẩm
-- <Param>
---- 
-- <Return>
---- 
-- <Reference>
---- 
-- <History>
----Created by: Trà Giang, Date: 25/08/2018
-- <Example>
---- 
/*-- <Example>
	NMP1011 @DivisionID = 'VF', @UserID = 'ASOFTADMIN', @XML = '431AFE34-9E6E-45B6-9C8E-241532857FBE'
	
	NMP1011 @DivisionID, @UserID, @XML
----*/

CREATE PROCEDURE NMP1011
( 
	 @DivisionID VARCHAR(50),
	 @UserID VARCHAR(50),
	 @XML XML
)
AS 
DECLARE @sSQL NVARCHAR (MAX) = N'',
		@LanguageID VARCHAR(50)

SELECT TOP 1 @LanguageID = ISNULL(LanguageID,'') FROM AT14051 WITH (NOLOCK) WHERE UserID = @UserID
        
CREATE TABLE #NMP1011 (APK VARCHAR(50))
INSERT INTO #NMP1011 (APK)
SELECT X.Data.query('APK').value('.', 'NVARCHAR(50)') AS APK
FROM @XML.nodes('//Data') AS X (Data)	

SET @sSQL = @sSQL + N'
SELECT NMT1010.DivisionID, NMT1010.MaterialsID, NMT1010.MaterialsTypeID,  NMT1010.Description, NMT1011.SystemName, NMT1011.ActualQuantity,
'+CASE WHEN ISNULL(@LanguageID,'') = 'vi-VN' THEN 'CST02.Description' ELSE 'CST02.DescriptionE' END+' AS [Disabled]
FROM NMT1010 WITH (NOLOCK)
 inner join NMT1011 WITH (NOLOCK) on NMT1010.APK= NMT1011.APKMaster
INNER JOIN #NMP1011 ON NMT1010.APK = #NMP1011.APK
LEFT JOIN NMT0099 CST02 WITH (NOLOCK) ON NMT1010.[Disabled] = CST02.ID AND CST02.CodeMaster = ''Disabled''
ORDER BY NMT1010.MaterialsID'

EXEC (@sSQL)
--PRINT(@sSQL)

   

GO
SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
