trigger: none

resources:
  - repo: self

pool:
  name: Stewie

jobs:
- job: UpdateDatabase
  displayName: 'Update Database'
  steps:
    - task: UpdateDatabaseWithDbUp@2
      inputs:
        ConnectionString: 'Server=$(DbUp.Server);Database=$(DbUp.Database);User ID=$(DbUp.UserId);Password=$(DbUp.Password);Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;'
        ScriptPath: 'path'
        JournalSchemaName: 'dbo'
        JournalTableName: '_SchemaVersions'