trigger: none

resources:
  - repo: self

pool:
  name: Stewie

jobs:
- job: UpdateDatabase
  displayName: 'Update Database'
  steps:
  
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)/s'
        artifact: 'ScriptsFix'
        publishLocation: 'pipeline'
      displayName: 'Publish Pipeline Artifact'

    - task: RunSqlCmdScriptsInFolderTask@1
      inputs:
        Server: '61.28.229.125'
        Database: '1BOSS_nhut'
        SqlCmdSciptFolderPath: '$(Pipeline.Workspace)/s/Fix'
        Recursive: 'true'
        SqlCmdVariableType: 'none'
        AuthenticationMethod: 'sqlauth'
        AuthenticationUser: 'sa'
        AuthenticationPassword: 'As@19006123'