trigger: none

jobs:
- template: updateDatabaseTemplate.yml
  parameters:
    databaseName: '1BOSS_minhnhut-01'
    serverName: '61.28.229.125'
    userName: 'sa'
    passWord: '$(SA_PASSWORD)'
- template: updateDatabaseTemplate.yml
  parameters:
    databaseName: '1BOSS_minhnhut-03'
    serverName: '61.28.229.125'
    userName: 'sa'
    passWord: '$(SA_PASSWORD)'  
- template: updateDatabaseTemplate.yml
  parameters:
    databaseName: '1BOSS_minhnhut-02'
    serverName: '61.28.227.3'
    userName: 'sa'
    passWord: '$(SA_PASSWORD)' 
- template: updateDatabaseTemplate.yml
  parameters:
    databaseName: '1BOSS_minhnhut-04'
    serverName: '61.28.227.3'
    userName: 'sa'
    passWord: '$(SA_PASSWORD)'  
