parameters:
  - name: databaseName
    type: string

jobs:
- job:
  displayName: 'Update Database - ${{ parameters.databaseName }}'
  pool:
    name: Stewie
  steps:
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)/s'
        artifact: 'ScriptsFix'
        publishLocation: 'pipeline'
      displayName: 'Publish Pipeline Artifact'

    - task: UpdateDatabaseWithDbUp@2
      inputs:
        ConnectionString: 'Server=61.28.229.125;Database=${{ parameters.databaseName }};User ID=sa;Password=As@19006123;TrustServerCertificate=True;Connection Timeout=30;'
        ScriptPath: '$(Pipeline.Workspace)/s/Fix'
        IncludeSubfolders: true
        Order: 'FolderStructure'
        # JournalSchemaName: 'dbo'
        # JournalTableName: '_SchemaVersions'
