parameters:
  - name: databaseName
    type: string
  - name: serverName
    type: string
  - name: userName
    type: string
  - name: passWord
    type: string

jobs:
- job:
  displayName: 'Update Database - ${{ parameters.databaseName }}'
  pool:
    name: Update database
  steps:
    - task: UpdateDatabaseWithDbUp@2
      inputs:
        ConnectionString: 'Server=${{ parameters.serverName }};Database=${{ parameters.databaseName }};User ID=${{ parameters.userName }};Password=${{ parameters.passWord }};TrustServerCertificate=True;Connection Timeout=30;'
        ScriptPath: 'Fix'
        IncludeSubfolders: true
        Order: 'FolderStructure'
        JournalToSqlTable: false
        # JournalSchemaName: 'dbo'
        # JournalTableName: '_SchemaVersions'
