IF EXISTS (SELECT TOP 1 1 FROM DBO.SYSOBJECTS WHERE ID = OBJECT_ID(N'[DBO].[SHMP1023]') AND  OBJECTPROPERTY(ID, N'IsProcedure') = 1)			
DROP PROCEDURE [DBO].[SHMP1023]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

-- <Summary>
---- Xuất Excel danh mục đợt phát hành
-- <Param>
---- 
-- <Return>
---- 
-- <Reference>
---- 
-- <History>
----Created by: Xuân Minh, Date: 03/10/2018
-- <Example>
---- 
/*-- <Example>
	EXEC SHMP1023 @DivisionID = 'AS', @UserID = 'ASOFTADMIN', @XML = 'B3DD9B7C-B110-4C26-9585-79A39EC28528'

	SHMP1023 @DivisionID, @UserID, @XML
----*/

CREATE PROCEDURE SHMP1023
( 
	 @DivisionID VARCHAR(50),
	 @UserID VARCHAR(50),
	 @XML XML
)
AS 
		DECLARE @sSQL NVARCHAR (MAX) = N'',
				@LanguageID VARCHAR(50)

		SELECT TOP 1 @LanguageID = ISNULL(LanguageID,'') FROM AT14051 WITH (NOLOCK) WHERE UserID = @UserID

		CREATE TABLE #SHMP1023 (APK VARCHAR(50))
		INSERT INTO #SHMP1023 (APK)
		SELECT X.Data.query('APK').value('.', 'NVARCHAR(50)') AS APK
		FROM @XML.nodes('//Data') AS X (Data)	

		SET @sSQL = @sSQL + N'
		SELECT SHMT1020.DivisionID, SHMT1020.SHPublishPeriodID, SHMT1020.SHPublishPeriodName,SHMT1020.SHPublishPeriodDate,SHMT1021.ShareTypeID,
		SHMT1020.QuantityPreferredShare,SHMT1020.QuantityCommonShare,SHMT1020.QuantityTotal,
		'+CASE WHEN ISNULL(@LanguageID,'') = 'vi-VN' THEN 'ED01.Description' ELSE 'ED01.DescriptionE' END+' AS IsCommon, 
		'+CASE WHEN ISNULL(@LanguageID,'') = 'vi-VN' THEN 'ED02.Description' ELSE 'ED02.DescriptionE' END+' AS [Disabled]
		FROM SHMT1020 WITH (NOLOCK)
		INNER JOIN #SHMP1023 ON SHMT1020.APK = #SHMP1023.APK 
		LEFT JOIN AT0099 ED01 WITH (NOLOCK) ON SHMT1020.IsCommon = ED01.ID AND ED01.CodeMaster = ''AT00000004''
		LEFT JOIN AT0099 ED02 WITH (NOLOCK) ON SHMT1020.[Disabled] = ED02.ID AND ED02.CodeMaster = ''AT00000004''
		LEFT JOIN SHMT1021 WITH (NOLOCK) ON SHMT1021.DivisionID=SHMT1020.DivisionID
		'
		--PRINT(@sSQL)
		EXEC (@sSQL)


   
GO
SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
