IF NOT EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[MTT9999]') AND TYPE IN (N'U'))
BEGIN
     CREATE TABLE [dbo].[MTT9999]
     (
      [APK] UNIQUEIDENTIFIER DEFAULT NEWID() NULL,
      [DivisionID] VARCHAR (50) NOT NULL,
      [TranMonth] INT NOT NULL,
      [TranYear] INT NOT NULL,
      [Closing] TINYINT DEFAULT (0) NOT NULL,
      [BeginDate] DATETIME NULL,
      [EndDate] DATETIME NULL,
      [Disabled] TINYINT DEFAULT (0) NOT NULL
    CONSTRAINT [PK_MTT9999] PRIMARY KEY CLUSTERED
      (
      [DivisionID],
      [TranMonth],
      [TranYear]
      )
WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
     )
 ON [PRIMARY]
END
