---- Create by Thái Huỳnh Khả Vi on 11/20/2017 1:02:46 PM
---- Dữ liệu ngầm 

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[WMT0099]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[WMT0099]
(
  [CodeMaster] VARCHAR(50) NOT NULL,
  [ID] VARCHAR(50) NOT NULL, 
  [Orders] INT NULL,
  [Description] NVARCHAR(250) NULL,
  [DescriptionE] NVARCHAR(250) NULL,  
  [Disabled] TINYINT DEFAULT (0) NULL,
  [Inherit] VARCHAR(50) NULL
CONSTRAINT [PK_WMT0099] PRIMARY KEY CLUSTERED
(
  [CodeMaster],
  [ID]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END



