---- Create by Thái Huỳnh Khả Vi on 3/2/2018 4:32:10 PM
---- Thiết lập cấp quản lý vị trí 

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[WMT0001]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].WMT0001
(
  [APK] UNIQUEIDENTIFIER DEFAULT newid() NOT NULL,
  [DivisionID] VARCHAR(50) NOT NULL,
  [LevelID] VARCHAR(50) NOT NULL,
  [SystemName] NVARCHAR(250) NULL,
  [UserName] NVARCHAR(250) NULL,
  [UserNameE] NVARCHAR(250) NULL,
  [IsUsed] TINYINT DEFAULT (0) NULL
CONSTRAINT [PK_WMT0001] PRIMARY KEY CLUSTERED
(
  [DivisionID],
  [LevelID]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END








