---- Create by Bảo Anh on 01/11/2018
---- Kết quả thu chi thực tế (master)
---- Modifier by Như Hàn on 04/01/2019: Bổ sung thêm mức độ ưu tiên

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[FNT2010]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[FNT2010]
(
	[APK] UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL,
    [DivisionID] VARCHAR(50) NOT NULL,
	[VoucherTypeID] VARCHAR(50) NULL,
	[VoucherNo] VARCHAR(50) NOT NULL,
	[VoucherDate] DATETIME NOT NULL,
	[TranMonth] INT NOT NULL,
	[TranYear] INT NOT NULL,
	[CurrencyID] VARCHAR(50) NULL,
	[ExchangeRate] DECIMAL(28,8) NULL,
	[PaymentTypeID] VARCHAR(50) NULL, 
	[Description] NVARCHAR(250) NULL,
	[APKPlanNo] VARCHAR(50) NULL,
	[CreateUserID] VARCHAR(50) NULL,
    [CreateDate] DATETIME NULL,
    [LastModifyUserID] VARCHAR(50) NULL,
    [LastModifyDate] DATETIME NULL,
	[DeleteFlag] TINYINT DEFAULT (0) NOT NULL

CONSTRAINT [PK_FNT2010] PRIMARY KEY CLUSTERED
(
	[DivisionID],
	[APK]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END


