-- <Summary>
---- 
-- <History>
---- Đợt chi cho kế hoạch thu chi tổng AIC
---- Create on 31/12/2018 by Như Hàn
---- Modified on 01/04/2019 by Như Hàn : Bổ sung 10 cột AnaID
---- <Example>
IF NOT EXISTS (SELECT * FROM sys.objects WITH (NOLOCK) WHERE object_id = OBJECT_ID(N'[dbo].[FNT2008_AIC]') AND type in (N'U'))
CREATE TABLE [dbo].[FNT2008_AIC](
    [APK] [UNIQUEIDENTIFIER] DEFAULT NEWID(),
	[APKMaster] [UNIQUEIDENTIFIER] ,--- APK của chi tiết kế hoạch thu chi (FNT2001)
	[Order] [INT],
	[DivisionID] [VARCHAR](25) , 
	[PaymentDate] [DATETIME] ,
	[POAmount] [DECIMAL],
	[PCAmount] [DECIMAL],
	[APaymentDate] [DATETIME] ,
	[AOAmount] [DECIMAL],
	[ACAmount] [DECIMAL],
	[APKMasterFNT2011] [UNIQUEIDENTIFIER] ,--- APK của chi tiết thực tế thu chi (FNT2011)
	[DeleteFlag] [TINYINT] DEFAULT 0

CONSTRAINT [PK_FNT2008_AIC] PRIMARY KEY NONCLUSTERED 
(
	[APK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

IF EXISTS (SELECT TOP 1 1 FROM sysobjects WHERE [name] = 'FNT2008_AIC' AND xtype = 'U')
BEGIN 
   IF NOT EXISTS (SELECT TOP 1 1 FROM syscolumns col INNER JOIN sysobjects tab 
   ON col.id = tab.id WHERE tab.name = 'FNT2008_AIC' AND col.name = 'Ana01ID') 
   BEGIN
	   ALTER TABLE FNT2008_AIC ADD Ana01ID [VARCHAR](50) NULL 
	   ALTER TABLE FNT2008_AIC ADD Ana02ID [VARCHAR](50) NULL 
	   ALTER TABLE FNT2008_AIC ADD Ana03ID [VARCHAR](50) NULL 
	   ALTER TABLE FNT2008_AIC ADD Ana04ID [VARCHAR](50) NULL 
	   ALTER TABLE FNT2008_AIC ADD Ana05ID [VARCHAR](50) NULL 
	   ALTER TABLE FNT2008_AIC ADD Ana06ID [VARCHAR](50) NULL 
	   ALTER TABLE FNT2008_AIC ADD Ana07ID [VARCHAR](50) NULL 
	   ALTER TABLE FNT2008_AIC ADD Ana08ID [VARCHAR](50) NULL 
	   ALTER TABLE FNT2008_AIC ADD Ana09ID [VARCHAR](50) NULL 
	   ALTER TABLE FNT2008_AIC ADD Ana10ID [VARCHAR](50) NULL 
   END

END


