---- Create by Nguyễn Hoàng Bảo Thy on 10/2/2017 2:25:16 PM
---- Sản phẩm trả về (detail)

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[HT11161]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[HT11161]
(
  [APK] UNIQUEIDENTIFIER DEFAULT newid() NOT NULL,
  [DivisionID] VARCHAR(50) NOT NULL,
  [APKMaster] VARCHAR(50) NOT NULL,
  [MachineID] VARCHAR(50) NOT NULL,
  [RepayQuantity] DECIMAL(28,8) NULL,
  [RepayAmount] DECIMAL(28,8) NULL,
  [Notes] NVARCHAR(250) NULL
CONSTRAINT [PK_HT11161] PRIMARY KEY CLUSTERED
(
  [DivisionID],
  [APKMaster],
  [MachineID]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END