---- Create by Thái Huỳnh Khả Vi on 2/26/2018 1:27:22 PM
---- Danh mục định mức lương sản phẩm 

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[HT1123]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[HT1123]
(
  [APK] UNIQUEIDENTIFIER DEFAULT newid() NOT NULL,
  [DivisionID] VARCHAR(50) NOT NULL,
  [NormID] VARCHAR(50) NOT NULL,
  [Description] NVARCHAR(250) NULL,
  [FromDate] DATETIME NULL,
  [ToDate] DATETIME NULL,
  [Disabled] TINYINT DEFAULT (0) NULL,
  [CreateUserID] VARCHAR(50) NULL,
  [CreateDate] DATETIME NULL,
  [LastModifyUserID] VARCHAR(50) NULL,
  [LastModifyDate] DATETIME NULL
CONSTRAINT [PK_HT1123] PRIMARY KEY CLUSTERED
(
  [DivisionID],
  [NormID]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END