---- Create by Nguyễn Hoàng Bảo Thy on 9/18/2017 3:45:35 PM
---- Phân công nhân viên đứng máy

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[HT1113]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[HT1113]
(
  [APK] UNIQUEIDENTIFIER DEFAULT newid() NOT NULL,
  [DivisionID] VARCHAR(50) NOT NULL,
  [APKMaster] VARCHAR(50) NOT NULL,
  [TranMonth] INT NOT NULL,
  [TranYear] INT NOT NULL,
  [MachineID] VARCHAR(50) NOT NULL,
  [EmployeeID] VARCHAR(50) NULL,
  [Date] DATETIME NULL,
  [ActFromTime] NVARCHAR(250) NULL,
  [ActToTime] NVARCHAR(250) NULL,
  [CreateUserID] VARCHAR(50) NULL,
  [CreateDate] DATETIME NULL,
  [LastmodifyDate] DATETIME NULL,
  [LastmodifyUserID] VARCHAR(50) NULL
CONSTRAINT [PK_HT1113] PRIMARY KEY CLUSTERED
(
  [APK],
  [DivisionID]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END