---- Create by Thái Huỳnh Khả Vi on 2/26/2018 1:45:47 PM
---- Danh mục định mức lương sản phẩm (Detail)

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[HT1124]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[HT1124]
(
  [APK] UNIQUEIDENTIFIER DEFAULT newid() NOT NULL,
  [DivisionID] VARCHAR(50) NOT NULL,
  [APKMaster] VARCHAR(50) NOT NULL,
  [Target] VARCHAR(50) NOT NULL,
  [Min] DECIMAL(28,8) NULL,
  [Tar] DECIMAL(28,8) NULL,
  [Max] DECIMAL(28,8) NULL,
  [Weight] DECIMAL(28,8) NULL
CONSTRAINT [PK_HT1124] PRIMARY KEY CLUSTERED
(
  [APK],
  [DivisionID]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END