---- Create by Nguyễn Hoàng Bảo Thy on 9/14/2017 11:46:45 AM
---- Danh mục máy

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[HT1109]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[HT1109]
(
  [APK] UNIQUEIDENTIFIER DEFAULT newid() NULL,
  [DivisionID] VARCHAR(50) NOT NULL,
  [MachineID] VARCHAR(50) NOT NULL,
  [MachineName] NVARCHAR(250) NULL,
  [Description] NVARCHAR(1000) NULL,
  [UnitID] VARCHAR(50) NULL,
  [HourPerDay] DECIMAL(28,8) NULL,
  [DayPerMonth] DECIMAL(28,8) NULL,
  [QuantityPerDay] DECIMAL(28,8) NULL,
  [QuantityPerHour] DECIMAL(28,8) NULL,
  [QuantityPerMonth] DECIMAL(28,8) NULL,
  [TotalEmployee] INT NULL,
  [MainEmployee] INT NULL,
  [SubEmployee] INT NULL,
  [Disabled] TINYINT DEFAULT (0) NULL,
  [CreateUserID] VARCHAR(50) NULL,
  [CreateDate] DATETIME NULL,
  [LastModifyUserID] VARCHAR(50) NULL,
  [LastModifyDate] DATETIME NULL
CONSTRAINT [PK_HT1109] PRIMARY KEY CLUSTERED
(
  [DivisionID],
  [MachineID]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END