IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[HT1401_CT]') AND TYPE IN (N'U'))
BEGIN
     CREATE TABLE [dbo].[HT1401_CT]
     (
		[Operation] [tinyint] NULL, --2: insert;1 delete;4 update
		[APK] [uniqueidentifier] NULL,
		[DivisionID] [nvarchar](50) NULL,
		[EmployeeID] [nvarchar](50) NULL,
		[FatherName] [nvarchar](250) NULL,
		[FatherYear] [int] NULL,
		[FatherJob] [nvarchar](250) NULL,
		[FatherAddress] [nvarchar](250) NULL,
		[FatherNote] [nvarchar](250) NULL,
		[IsFatherDeath] [tinyint] NULL,
		[MotherName] [nvarchar](250) NULL,
		[MotherYear] [int] NULL,
		[MotherJob] [nvarchar](250) NULL,
		[MotherAddress] [nvarchar](250) NULL,
		[MotherNote] [nvarchar](250) NULL,
		[IsMotherDeath] [tinyint]  NULL,
		[SpouseName] [nvarchar](250) NULL,
		[SpouseYear] [int] NULL,
		[SpouseAddress] [nvarchar](250) NULL,
		[SpouseNote] [nvarchar](250) NULL,
		[SpouseJob] [nvarchar](250) NULL,
		[IsSpouseDeath] [tinyint]  NULL,
		[EducationLevelID] [nvarchar](50) NULL,
		[PoliticsID] [nvarchar](50) NULL,
		[Language1ID] [nvarchar](50) NULL,
		[Language2ID] [nvarchar](50) NULL,
		[Language3ID] [nvarchar](50) NULL,
		[LanguageLevel1ID] [nvarchar](50) NULL,
		[LanguageLevel2ID] [nvarchar](50) NULL,
		[LanguageLevel3ID] [nvarchar](50) NULL,
		[CreateDate] [datetime] NULL,
		[CreateUserID] [nvarchar](50) NULL,
		[LastModifyDate] [datetime] NULL,
		[LastModifyUserID] [nvarchar](50) NULL,
		[ReAPK] [uniqueidentifier] NULL
     )
	
	INSERT INTO HT1401_CT
	(
		Operation,
		APK,
		DivisionID,
		EmployeeID,
		FatherName,
		FatherYear,
		FatherJob,
		FatherAddress,
		FatherNote,
		IsFatherDeath,
		MotherName,
		MotherYear,
		MotherJob,
		MotherAddress,
		MotherNote,
		IsMotherDeath,
		SpouseName,
		SpouseYear,
		SpouseAddress,
		SpouseNote,
		SpouseJob,
		IsSpouseDeath,
		EducationLevelID,
		PoliticsID,
		Language1ID,
		Language2ID,
		Language3ID,
		LanguageLevel1ID,
		LanguageLevel2ID,
		LanguageLevel3ID,
		CreateDate,
		CreateUserID,
		LastModifyDate,
		LastModifyUserID,
		ReAPK
	)
	SELECT 2,
		APK,
		DivisionID,
		EmployeeID,
		FatherName,
		FatherYear,
		FatherJob,
		FatherAddress,
		FatherNote,
		IsFatherDeath,
		MotherName,
		MotherYear,
		MotherJob,
		MotherAddress,
		MotherNote,
		IsMotherDeath,
		SpouseName,
		SpouseYear,
		SpouseAddress,
		SpouseNote,
		SpouseJob,
		IsSpouseDeath,
		EducationLevelID,
		PoliticsID,
		Language1ID,
		Language2ID,
		Language3ID,
		LanguageLevel1ID,
		LanguageLevel2ID,
		LanguageLevel3ID,
		CreateDate,
		CreateUserID,
		LastModifyDate,
		LastModifyUserID,
		ReAPK
	FROM HT1401  
  
END
