IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[HT1403_CT]') AND TYPE IN (N'U'))
BEGIN

CREATE TABLE [dbo].[HT1403_CT](
	[Operation] [tinyint] NULL, --2: insert;1 delete;4 update
	[APK] [uniqueidentifier] NULL,
	[DivisionID] [nvarchar](50)  NULL,
	[EmployeeID] [nvarchar](50)  NULL,
	[SalaryCoefficient] [decimal](28, 8) NULL,
	[DutyCoefficient] [decimal](28, 8) NULL,
	[TimeCoefficient] [decimal](28, 8) NULL,
	[DepartmentID] [nvarchar](50) NULL,
	[TeamID] [nvarchar](50) NULL,
	[DutyID] [nvarchar](50) NULL,
	[TaxObjectID] [nvarchar](50) NULL,
	[EmployeeStatus] [tinyint] NULL,
	[Experience] [nvarchar](100) NULL,
	[SuggestSalary] [decimal](28, 8) NULL,
	[RecruitDate] [datetime] NULL,
	[RecruitPlace] [nvarchar](250) NULL,
	[WorkDate] [datetime] NULL,
	[C01] [decimal](28, 8) NULL,
	[C02] [decimal](28, 8) NULL,
	[C03] [decimal](28, 8) NULL,
	[C04] [decimal](28, 8) NULL,
	[C05] [decimal](28, 8) NULL,
	[C06] [decimal](28, 8) NULL,
	[C07] [decimal](28, 8) NULL,
	[C08] [decimal](28, 8) NULL,
	[C09] [decimal](28, 8) NULL,
	[C10] [decimal](28, 8) NULL,
	[BaseSalary] [decimal](28, 8) NULL,
	[InsuranceSalary] [decimal](28, 8) NULL,
	[Salary01] [decimal](28, 8) NULL,
	[Salary02] [decimal](28, 8) NULL,
	[Salary03] [decimal](28, 8) NULL,
	[Target01ID] [nvarchar](50) NULL,
	[Target02ID] [nvarchar](50) NULL,
	[Target03ID] [nvarchar](50) NULL,
	[Target04ID] [nvarchar](50) NULL,
	[Target05ID] [nvarchar](50) NULL,
	[Target06ID] [nvarchar](50) NULL,
	[Target07ID] [nvarchar](50) NULL,
	[Target08ID] [nvarchar](50) NULL,
	[Target09ID] [nvarchar](50) NULL,
	[Target10ID] [nvarchar](50) NULL,
	[TargetAmount01] [decimal](28, 8) NULL,
	[TargetAmount02] [decimal](28, 8) NULL,
	[TargetAmount03] [decimal](28, 8) NULL,
	[TargetAmount04] [decimal](28, 8) NULL,
	[TargetAmount05] [decimal](28, 8) NULL,
	[TargetAmount06] [decimal](28, 8) NULL,
	[TargetAmount07] [decimal](28, 8) NULL,
	[TargetAmount08] [decimal](28, 8) NULL,
	[TargetAmount09] [decimal](28, 8) NULL,
	[TargetAmount10] [decimal](28, 8) NULL,
	[LeaveDate] [datetime] NULL,
	[LoaCondID] [nvarchar](50) NULL,
	[IsOtherDayPerMonth] [tinyint] NULL,
	[FileID] [nvarchar](50) NULL,
	[ApplyDate] [datetime] NULL,
	[BeginProbationDate] [datetime] NULL,
	[EndProbationDate] [datetime] NULL,
	[ProbationNote] [nvarchar](250) NULL,
	[QuitJobID] [nvarchar](50) NULL,
	[C11] [decimal](28, 8) NULL,
	[C12] [decimal](28, 8) NULL,
	[C13] [decimal](28, 8) NULL,
	[ExpenseAccountID] [nvarchar](50) NULL,
	[PayableAccountID] [nvarchar](50) NULL,
	[PerInTaxID] [nvarchar](50) NULL,
	[C14] [decimal](28, 8) NULL,
	[C15] [decimal](28, 8) NULL,
	[C16] [decimal](28, 8) NULL,
	[C17] [decimal](28, 8) NULL,
	[C18] [decimal](28, 8) NULL,
	[C19] [decimal](28, 8) NULL,
	[C20] [decimal](28, 8) NULL,
	[C21] [decimal](28, 8) NULL,
	[C22] [decimal](28, 8) NULL,
	[C23] [decimal](28, 8) NULL,
	[C24] [decimal](28, 8) NULL,
	[C25] [decimal](28, 8) NULL,
	[CompanyDate] [datetime] NULL,
	[IsJobWage] [tinyint] NULL,
	[IsPiecework] [tinyint] NULL,
	[TitleID] [varchar](50) NULL,
	[SalaryLevel] [varchar](50) NULL,
	[SalaryLevelDate] [datetime] NULL,
	[MidEmployeeID] [nvarchar](50) NULL,
	[LeaveToDate] [datetime] NULL,
	[Notes] [nvarchar](250) NULL,
	[IsManager] [tinyint] NULL,
	[CreateDate] [datetime] NULL,
	[CreateUserID] [nvarchar](50) NULL,
	[LastModifyDate] [datetime] NULL,
	[LastModifyUserID] [nvarchar](50) NULL,
	[ReAPK] [uniqueidentifier] NULL
)


INSERT INTO HT1403_CT
(
	Operation,
	APK,
	DivisionID,
	EmployeeID,
	SalaryCoefficient,
	DutyCoefficient,
	TimeCoefficient,
	DepartmentID,
	TeamID,
	DutyID,
	TaxObjectID,
	EmployeeStatus,
	Experience,
	SuggestSalary,
	RecruitDate,
	RecruitPlace,
	WorkDate,
	C01,
	C02,
	C03,
	C04,
	C05,
	C06,
	C07,
	C08,
	C09,
	C10,
	BaseSalary,
	InsuranceSalary,
	Salary01,
	Salary02,
	Salary03,
	Target01ID,
	Target02ID,
	Target03ID,
	Target04ID,
	Target05ID,
	Target06ID,
	Target07ID,
	Target08ID,
	Target09ID,
	Target10ID,
	TargetAmount01,
	TargetAmount02,
	TargetAmount03,
	TargetAmount04,
	TargetAmount05,
	TargetAmount06,
	TargetAmount07,
	TargetAmount08,
	TargetAmount09,
	TargetAmount10,
	LeaveDate,
	LoaCondID,
	IsOtherDayPerMonth,
	FileID,
	ApplyDate,
	BeginProbationDate,
	EndProbationDate,
	ProbationNote,
	QuitJobID,
	C11,
	C12,
	C13,
	ExpenseAccountID,
	PayableAccountID,
	PerInTaxID,
	C14,
	C15,
	C16,
	C17,
	C18,
	C19,
	C20,
	C21,
	C22,
	C23,
	C24,
	C25,
	CompanyDate,
	IsJobWage,
	IsPiecework,
	TitleID,
	SalaryLevel,
	SalaryLevelDate,
	MidEmployeeID,
	LeaveToDate,
	Notes,
	IsManager,
	CreateDate,
	CreateUserID,
	LastModifyDate,
	LastModifyUserID,
	ReAPK
)
SELECT 2,
APK,
	DivisionID,
	EmployeeID,
	SalaryCoefficient,
	DutyCoefficient,
	TimeCoefficient,
	DepartmentID,
	TeamID,
	DutyID,
	TaxObjectID,
	EmployeeStatus,
	Experience,
	SuggestSalary,
	RecruitDate,
	RecruitPlace,
	WorkDate,
	C01,
	C02,
	C03,
	C04,
	C05,
	C06,
	C07,
	C08,
	C09,
	C10,
	BaseSalary,
	InsuranceSalary,
	Salary01,
	Salary02,
	Salary03,
	Target01ID,
	Target02ID,
	Target03ID,
	Target04ID,
	Target05ID,
	Target06ID,
	Target07ID,
	Target08ID,
	Target09ID,
	Target10ID,
	TargetAmount01,
	TargetAmount02,
	TargetAmount03,
	TargetAmount04,
	TargetAmount05,
	TargetAmount06,
	TargetAmount07,
	TargetAmount08,
	TargetAmount09,
	TargetAmount10,
	LeaveDate,
	LoaCondID,
	IsOtherDayPerMonth,
	FileID,
	ApplyDate,
	BeginProbationDate,
	EndProbationDate,
	ProbationNote,
	QuitJobID,
	C11,
	C12,
	C13,
	ExpenseAccountID,
	PayableAccountID,
	PerInTaxID,
	C14,
	C15,
	C16,
	C17,
	C18,
	C19,
	C20,
	C21,
	C22,
	C23,
	C24,
	C25,
	CompanyDate,
	IsJobWage,
	IsPiecework,
	TitleID,
	SalaryLevel,
	SalaryLevelDate,
	MidEmployeeID,
	LeaveToDate,
	Notes,
	IsManager,
	CreateDate,
	CreateUserID,
	LastModifyDate,
	LastModifyUserID,
	ReAPK
FROM HT1403

END 


