-- <Summary>
---- 
-- <History>
---- Create on 11/10/2010 by Thanh Trẫm
---- Modified on ... by ...
---- <Example>
IF NOT EXISTS(SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[HT1444]') AND type in (N'U'))
CREATE TABLE [dbo].[HT1444](
	[APK] [uniqueidentifier] DEFAULT NEWID(),
	[DivisionID] nvarchar(3) NOT NULL,
	[EmployeeID] [nvarchar](50) NOT NULL,
	[Orders] [nvarchar](50) NOT NULL,
	[S1] [nvarchar](50) NULL,
	[S2] [nvarchar](50) NULL,
	[S3] [nvarchar](50) NULL,
	[FullName] [nvarchar](250) NULL,
	[LastName] [nvarchar](250) NULL,
	[MiddleName] [nvarchar](250) NULL,
	[FirstName] [nvarchar](250) NULL,
	[ShortName] [nvarchar](250) NULL,
	[Alias] [nvarchar](100) NULL,
	[Birthday] [nvarchar](100) NULL,
	[BornPlace] [nvarchar](250) NULL,
	[IsMale] [nvarchar](100) NOT NULL,
	[NativeCountry] [nvarchar](100) NULL,
	[PassportNo] [nvarchar](50) NULL,
	[PassportDate] [datetime] NULL,
	[PassportEnd] [datetime] NULL,
	[IdentifyCardNo] [nvarchar](50) NULL,
	[IdentifyDate] [datetime] NULL,
	[IdentifyPlace] [nvarchar](250) NULL,
	[IsSingle] [nvarchar](100) NOT NULL,
	[Status] [nvarchar](50) NOT NULL,
	[ImageID] [image] NULL,
	[CountryID] [nvarchar](50) NULL,
	[FullAddress] [nvarchar](250) NULL,
	[CityID] [nvarchar](50) NULL,
	[CityName] [nvarchar](250) NULL,
	[DistrictID] [nvarchar](50) NULL,
	[PermanentAddress] [nvarchar](250) NULL,
	[TemporaryAddress] [nvarchar](250) NULL,
	[EthnicID] [nvarchar](50) NULL,
	[EthnicName] [nvarchar](250) NULL,
	[ReligionID] [nvarchar](50) NULL,
	[ReligionName] [nvarchar](250) NULL,
	[Notes] [nvarchar](250) NULL,
	[HealthStatus] [nvarchar](100) NULL,
	[HomePhone] [nvarchar](100) NULL,
	[HomeFax] [nvarchar](100) NULL,
	[MobiPhone] [nvarchar](100) NULL,
	[Email] [nvarchar](100) NULL,
	[CreateDate] [datetime] NULL,
	[CreateUserID] [nvarchar](50) NULL,
	[LastModifyDate] [datetime] NULL,
	[LastModifyUserID] [nvarchar](50) NULL,
	[IsOtherDayPerMonth] [tinyint] NULL,
	[IsMaleID] [tinyint] NULL,
	[IsSingleID] [tinyint] NOT NULL,
	[IsForeigner] [tinyint] NULL,
	[RecruitTimeID] [nvarchar](50) NULL,
	[FatherName] [nvarchar](250) NULL,
	[FatherYear] [int] NULL,
	[FatherJob] [nvarchar](100) NULL,
	[FatherAddress] [nvarchar](250) NULL,
	[FatherNote] [nvarchar](250) NULL,
	[IsFatherDeath] [tinyint] NULL,
	[MotherName] [nvarchar](250) NULL,
	[MotherYear] [int] NULL,
	[MotherJob] [nvarchar](100) NULL,
	[MotherAddress] [nvarchar](250) NULL,
	[MotherNote] [nvarchar](250) NULL,
	[IsMotherDeath] [tinyint] NULL,
	[SpouseName] [nvarchar](250) NULL,
	[SpouseYear] [int] NULL,
	[SpouseAddress] [nvarchar](50) NULL,
	[SpouseNote] [nvarchar](250) NULL,
	[SpouseJob] [nvarchar](100) NULL,
	[IsSpouseDeath] [tinyint] NULL,
	[EducationLevelID] [nvarchar](50) NULL,
	[EducationLevelName] [nvarchar](250) NULL,
	[PoliticsID] [nvarchar](50) NULL,
	[Language1ID] [nvarchar](100) NULL,
	[Language2ID] [nvarchar](100) NULL,
	[Language3ID] [nvarchar](100) NULL,
	[LanguageLevel1ID] [nvarchar](50) NULL,
	[LanguageLevel2ID] [nvarchar](50) NULL,
	[LanguageLevel3ID] [nvarchar](50) NULL,
	[BankID] [nvarchar](50) NULL,
	[BankAccountNo] [nvarchar](50) NULL,
	[SoInsuranceNo] [nvarchar](50) NULL,
	[SoInsurBeginDate] [datetime] NULL,
	[HeInsuranceNo] [nvarchar](50) NULL,
	[ArmyJoinDate] [datetime] NULL,
	[ArmyEndDate] [datetime] NULL,
	[ArmyLevel] [nvarchar](100) NULL,
	[Hobby] [nvarchar](250) NULL,
	[HospitalID] [nvarchar](50) NULL,
	[Height] [nvarchar](100) NULL,
	[Weight] [nvarchar](100) NULL,
	[BloodGroup] [nvarchar](100) NULL,
	[AssociationID] [nvarchar](50) NULL,
	[SalaryCoefficient] [decimal](28, 8) NULL,
	[DutyCoefficient] [decimal](28, 8) NULL,
	[TimeCoefficient] [decimal](28, 8) NULL,
	[DepartmentID] [nvarchar](50) NULL,
	[DepartmentName] [nvarchar](250) NULL,
	[TEAMID] [nvarchar](50) NOT NULL,
	[TeamName] [nvarchar](250) NULL,
	[DutyID] [nvarchar](50) NULL,
	[DutyName] [nvarchar](250) NULL,
	[TaxObjectID] [nvarchar](50) NULL,
	[EmployeeStatus] [tinyint] NULL,
	[Experience] [nvarchar](100) NULL,
	[SuggestSalary] [decimal](28, 8) NULL,
	[RecruitDate] [datetime] NULL,
	[RecruitPlace] [nvarchar](250) NULL,
	[WorkDate] [datetime] NULL,
	[LeaveDate] [datetime] NULL,
	[QuitJobID] [nvarchar](50) NULL,
	[QuitJobName] [nvarchar](250) NULL,
	[C01] [decimal](28, 8) NULL,
	[C02] [decimal](28, 8) NULL,
	[C03] [decimal](28, 8) NULL,
	[C04] [decimal](28, 8) NULL,
	[C05] [decimal](28, 8) NULL,
	[C06] [decimal](28, 8) NULL,
	[C07] [decimal](28, 8) NULL,
	[C08] [decimal](28, 8) NULL,
	[C09] [decimal](28, 8) NULL,
	[C10] [decimal](28, 8) NULL,
	[BaseSalary] [decimal](28, 8) NULL,
	[InsuranceSalary] [decimal](28, 8) NULL,
	[Salary01] [decimal](28, 8) NULL,
	[Salary02] [decimal](28, 8) NULL,
	[Salary03] [decimal](28, 8) NULL,
	[Target01ID] [nvarchar](50) NULL,
	[Target02ID] [nvarchar](50) NULL,
	[Target03ID] [nvarchar](50) NULL,
	[Target04ID] [nvarchar](50) NULL,
	[Target05ID] [nvarchar](50) NULL,
	[Target06ID] [nvarchar](50) NULL,
	[Target07ID] [nvarchar](50) NULL,
	[Target08ID] [nvarchar](50) NULL,
	[Target09ID] [nvarchar](50) NULL,
	[Target10ID] [nvarchar](50) NULL,
	[TargetAmount01] [decimal](28, 8) NULL,
	[TargetAmount02] [decimal](28, 8) NULL,
	[TargetAmount03] [decimal](28, 8) NULL,
	[TargetAmount04] [decimal](28, 8) NULL,
	[TargetAmount05] [decimal](28, 8) NULL,
	[TargetAmount06] [decimal](28, 8) NULL,
	[TargetAmount07] [decimal](28, 8) NULL,
	[TargetAmount08] [decimal](28, 8) NULL,
	[TargetAmount09] [decimal](28, 8) NULL,
	[TargetAmount10] [decimal](28, 8) NULL,
	[LoaCondID] [nvarchar](50) NULL,
	[ApplyDate] [datetime] NULL,
	[BeginProbationDate] [datetime] NULL,
	[EndProbationDate] [datetime] NULL,
	[ProbationNote] [nvarchar](250) NULL,
	[FileID] [nvarchar](50) NULL,
	CONSTRAINT [PK_HT1444] PRIMARY KEY NONCLUSTERED 
(
	[APK] ASC
    )WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
---- Add giá trị default
IF NOT EXISTS(SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF_HT1444_IsFatherDeath]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[HT1444] ADD  CONSTRAINT [DF_HT1444_IsFatherDeath]  DEFAULT ((0)) FOR [IsFatherDeath]
END
IF NOT EXISTS(SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF_HT1444_IsMotherDeath]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[HT1444] ADD  CONSTRAINT [DF_HT1444_IsMotherDeath]  DEFAULT ((0)) FOR [IsMotherDeath]
END
IF NOT EXISTS(SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF_HT1444_IsSpouseDeath]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[HT1444] ADD  CONSTRAINT [DF_HT1444_IsSpouseDeath]  DEFAULT ((0)) FOR [IsSpouseDeath]
END

