
----- Created by: Nhựt Trường, Date 13/07/2023.
----- Purpose: Load các khoản thu nhập

IF EXISTS (SELECT TOP 1 1 FROM DBO.SYSOBJECTS WHERE ID = OBJECT_ID(N'[DBO].[HV1116]') AND OBJECTPROPERTY(ID, N'IsView') = 1)
DROP VIEW [DBO].[HV1116]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[HV1116]
AS
SELECT    DivisionID, BaseSalaryFieldID, Description, 'B' AS Type
FROM         dbo.HV1112
UNION
SELECT    DivisionID, IncomeID, Caption, 'I' AS Type
FROM         HT0002
WHERE     IsUsed = 1

GO
SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
