IF EXISTS (SELECT TOP 1 1 FROM DBO.SYSOBJECTS WHERE ID = OBJECT_ID(N'[DBO].[EDMP2166]') AND  OBJECTPROPERTY(ID, N'IsProcedure') = 1)			
DROP PROCEDURE [DBO].[EDMP2166]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO





-- <Summary>
---- Load ngày làm việc 
----
-- <Return>
---- 
-- <Reference>
---- 
-- <History>
----Created by: Hồng Thảo , Date: 6/5/2019
-- <Example>
/*
		
		 EDMP2166 @DivisionID = 'BE',@UserID = 'ASOFTADMIN',@StartDate = '2019-09-01 00:00:00', @EndDate = '2019-09-30 00:00:00',@StudentID = '0000216',@Mode = 1
*/
CREATE PROCEDURE EDMP2166
( 
        @DivisionID VARCHAR(50),
		@UserID VARCHAR(50),
		@StartDate DATETIME,
		@EndDate DATETIME,
		@StudentID VARCHAR(50),
		@Mode VARCHAR(50) 
) 
AS 

IF @Mode = 1 

BEGIN 
----load ngày làm việc 
SELECT O2.*, O1.FromDate, O1.ToDate
FROM OOT0030 O1 WITH (NOLOCK)
INNER JOIN OOT0032 O2 WITH (NOLOCK) ON O1.APK = O2.APKMaster
WHERE O1.DivisionID = @DivisionID
AND ( CONVERT(VARCHAR(10),@StartDate,126) BETWEEN  CONVERT(VARCHAR(10), CONVERT(DATE, O1.FromDate,120), 126)   AND CONVERT(VARCHAR(10), CONVERT(DATE, O1.ToDate,120), 126)
	OR CONVERT(VARCHAR(10),@EndDate,126) BETWEEN  CONVERT(VARCHAR(10), CONVERT(DATE, O1.FromDate,120), 126)   AND CONVERT(VARCHAR(10), CONVERT(DATE, O1.ToDate,120), 126)
	)

END 


IF @Mode = 2 
BEGIN 
-----Load Ngày nghỉ lễ 

SELECT O1.*
		FROM OOT0031 O1 WITH (NOLOCK)
		LEFT JOIN OOT0030 O2 WITH (NOLOCK) ON O1.APKMaster = O2.APK 
		WHERE   O2.DivisionID = @DivisionID AND 
				(CONVERT(VARCHAR(10),O1.StartDayOff,126) BETWEEN CONVERT(VARCHAR(10), CONVERT(DATE, @StartDate,120), 126) AND CONVERT(VARCHAR(10), CONVERT(DATE, @EndDate,120), 126)
			    OR CONVERT(VARCHAR(10),O1.EndDayOff,126) BETWEEN CONVERT(VARCHAR(10), CONVERT(DATE, @StartDate,120), 126) AND CONVERT(VARCHAR(10), CONVERT(DATE, @EndDate,120), 126))

END 

IF @Mode = 3
BEGIN 
----Load ngày nghỉ xin phép 

SELECT * 
FROM APT0008 
WHERE DivisionID = @DivisionID AND 
	   (CONVERT(VARCHAR(10), CONVERT(DATE, FromDate,120), 126) BETWEEN CONVERT(VARCHAR(10), CONVERT(DATE, @StartDate,120), 126) AND CONVERT(VARCHAR(10), CONVERT(DATE, @EndDate,120), 126)
	   OR CONVERT(VARCHAR(10), CONVERT(DATE, ToDate,120), 126) BETWEEN CONVERT(VARCHAR(10), CONVERT(DATE, @StartDate,120), 126) AND CONVERT(VARCHAR(10), CONVERT(DATE, @EndDate,120), 126))
AND StudentID = @StudentID AND DeleteFlg = 0
ORDER BY CreateDate ASC



END 

IF @Mode = 4 
BEGIN


SELECT T1.DivisionID,T1.GradeID,T1.AttendanceDate, T1.SchoolYearID, T1.ClassID,T1.VoucherNo,T4.StudentID, T4.AvailableStatusID
FROM EDMT2040 T1 WITH (NOLOCK) 
OUTER APPLY (SELECT TOP 1 * FROM EDMT2040 T3 WITH (NOLOCK) WHERE T1.ClassID = T3.ClassID AND T1.GradeID = T3.GradeID AND T1.SchoolYearID = T3.SchoolYearID and T1.AttendanceDate = T3.AttendanceDate  
			 ORDER BY T3.CreateDate DESC) A
LEFT JOIN EDMT2041 T4 WITH(NOLOCK) ON T4.APKMaster = T1.APK AND T1.DeleteFlg = T4.DeleteFlg
WHERE T1.DivisionID = @DivisionID AND T1.DeleteFlg = 0 
AND T1.CreateDate = A.CreateDate 
AND CONVERT(VARCHAR(10), CONVERT(DATE, T1.AttendanceDate,120), 126) BETWEEN CONVERT(VARCHAR(10), CONVERT(DATE, @StartDate,120), 126) AND CONVERT(VARCHAR(10), CONVERT(DATE, @EndDate,120), 126)
AND T4.StudentID = @StudentID AND T4.AvailableStatusID = 'HD'
ORDER BY T1.AttendanceDate


END 



 


GO
SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
