IF EXISTS (SELECT TOP 1 1 FROM DBO.SYSOBJECTS WHERE ID = OBJECT_ID(N'[DBO].[EDMP1091]') AND  OBJECTPROPERTY(ID, N'IsProcedure') = 1)			
DROP PROCEDURE [DBO].[EDMP1091]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

-- <Summary>
---- Xuất Excel danh mục biểu phí
-- <Param>
---- 
-- <Return>
---- 
-- <Reference>
---- 
-- <History>
----Created by: Hồng Thảo on 06/09/2018
-- <Example>
---- 
/*-- <Example>
	EDMP1091 @DivisionID = 'BS', @UserID = 'ASOFTADMIN', @XML = '<Data><APK>23BA8A5F-C83E-4517-8202-254736E677D2</APK></Data><Data><APK>94CF8D31-0ADE-43C7-A80D-0DDCDA1738D1</APK></Data>'


	EDMP1091 @DivisionID, @UserID, @XML
----*/

CREATE PROCEDURE EDMP1091
( 
	 @DivisionID VARCHAR(50),
	 @UserID VARCHAR(50),
	 @XML XML
)


AS 
DECLARE @sSQL NVARCHAR (MAX) = N'',
		@LanguageID VARCHAR(50)

SELECT TOP 1 @LanguageID = ISNULL(@LanguageID,'') FROM AT14051 WITH (NOLOCK) WHERE UserID = @UserID

CREATE TABLE #EDMP1091 (APK VARCHAR(50))
INSERT INTO #EDMP1091 (APK)
SELECT X.Data.query('APK').value('.', 'NVARCHAR(50)') AS APK
FROM @XML.nodes('//Data') AS X (Data)	

SET @sSQL = @sSQL + N'
SELECT EDMT1090.APK, EDMT1090.DivisionID, EDMT1090.FeeID,EDMT1090.FeeName,EDMT1090.FromDate,EDMT1090.ToDate,
EDMT1090.GradeID, EDMT1090.GradeID + '' - '' + E02.GradeName AS GradeName,
A.ReceiptTypeID + '' - '' + E03.ReceiptTypeName AS ReceiptTypeName,
A.FeeTypeID + '' - '' +'+CASE WHEN ISNULL(@LanguageID,'') = 'vi-VN' THEN 'E04.[Description]' ELSE 'E04.DescriptionE' END+' AS  FeeTypeName,
A.Amount, A.UnitID + '' - '' + '+CASE WHEN ISNULL(@LanguageID,'') = 'vi-VN' THEN 'E05.[Description]' ELSE 'E05.DescriptionE' END+' AS  UnitName,
EDMT1090.[Disabled], EDMT1090.IsCommon
FROM EDMT1090 WITH (NOLOCK)
INNER JOIN #EDMP1091 ON EDMT1090.APK = #EDMP1091.APK
INNER JOIN EDMT1091 A WITH (NOLOCK) ON A.APKMaster = EDMT1090.APK
LEFT JOIN EDMT1000 E02 WITH (NOLOCK) ON E02.DivisionID IN (EDMT1090.DivisionID,''@@@'') AND E02.GradeID = EDMT1090.GradeID
LEFT JOIN EDMT1050 E03 WITH (NOLOCK) ON E03.DivisionID IN (EDMT1090.DivisionID,''@@@'') AND E03.ReceiptTypeID = A.ReceiptTypeID
LEFT JOIN EDMT0099 E04 WITH (NOLOCK) ON E04.ID = A.FeeTypeID AND E04.CodeMaster = ''FeeType''
LEFT JOIN EDMT0099 E05 WITH (NOLOCK) ON E05.ID = A.UnitID AND E05.CodeMaster = ''Time''
ORDER BY EDMT1090.FeeID'

--PRINT(@sSQL)
EXEC (@sSQL)


   
GO
SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO


