IF EXISTS (SELECT TOP 1 1 FROM DBO.SYSOBJECTS WITH(NOLOCK) WHERE ID = OBJECT_ID(N'[DBO].[EDMP1042]') AND OBJECTPROPERTY(ID, N'IsProcedure') = 1)
DROP PROCEDURE [DBO].[EDMP1042]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


-- <Summary>
---- Xuất Excel danh mục năm học
-- <Param>
---- 
-- <Return>
---- 
-- <Reference>
---- 
-- <History>
----Created by: Minh Hòa , Date: 17/09/2018
---- Modified by on 
-- <Example>
---- 
/*-- <Example>
	EDMP1042 @DivisionID = 'VS', @UserID = 'ASOFTADMIN', @XML = '431AFE34-9E6E-45B6-9C8E-241532857FBE'
	
	EDMP1042 @DivisionID, @UserID, @XML
	Exec EDMP1042 'MK','NV04','E80FA704-6CBD-4168-A7D3-2580ABDA2D64'
----*/

CREATE PROCEDURE EDMP1042
( 
	 @DivisionID VARCHAR(50),
	 @UserID VARCHAR(50),
	 @LanguageID VARCHAR(50),
	 @XML XML
)
AS 
DECLARE @sSQL NVARCHAR (MAX) = N''

--SELECT TOP 1 @LanguageID = ISNULL(LanguageID,'') FROM AT14051 WITH (NOLOCK) WHERE UserID = @UserID
SELECT @LanguageID = ISNULL(@LanguageID, 'vi-VN')
        
CREATE TABLE #EDMP1042 (APK VARCHAR(50))
INSERT INTO #EDMP1042 (APK)
SELECT X.Data.query('APK').value('.', 'NVARCHAR(50)') AS APK
FROM @XML.nodes('//Data') AS X (Data)	

SET @sSQL = @sSQL + N'
SELECT EDMT1040.DivisionID, EDMT1040.SchoolYearID, EDMT1040.DateFrom, EDMT1040.DateTo, 
'+CASE WHEN @LanguageID = 'vi-VN' THEN 'T01.Description' ELSE 'T01.DescriptionE' END+' AS IsCommon, 
'+CASE WHEN @LanguageID = 'vi-VN' THEN 'T02.Description' ELSE 'T02.DescriptionE' END+' AS [Disabled]
FROM EDMT1040 WITH (NOLOCK)
INNER JOIN #EDMP1042 ON EDMT1040.APK = #EDMP1042.APK
LEFT JOIN EDMT0099 T01 WITH (NOLOCK) ON EDMT1040.IsCommon = T01.ID AND T01.CodeMaster = ''Disabled''
LEFT JOIN EDMT0099 T02 WITH (NOLOCK) ON EDMT1040.[Disabled] = T02.ID AND T02.CodeMaster = ''Disabled''
ORDER BY EDMT1040.SchoolYearID'

EXEC (@sSQL)
--PRINT(@sSQL)




GO
SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO

