IF EXISTS (SELECT TOP 1 1 FROM DBO.SYSOBJECTS WHERE ID = OBJECT_ID(N'[DBO].[EDMP2087]') AND  OBJECTPROPERTY(ID, N'IsProcedure') = 1)			
DROP PROCEDURE [DBO].[EDMP2087]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO





-- <Summary>
---- Quyết toán 
-- <Param>
---- 
-- <Return>
---- 
-- <Reference>
---- 
---- 
-- <History>
----Created by: Hồng Thảo on 22/7/2019
-- <Example>
---- 
/*-- <Example>


	EDMP2087 @DivisionID = 'BE',@UserID = 'ASOFTADMIN',@APK = '86D1FF91-0B60-4D08-B00D-DBE4210DCE38'
----*/

CREATE PROCEDURE EDMP2087
( 
	 @DivisionID VARCHAR(50),
	 @UserID VARCHAR(50),
	 @APK VARCHAR(50),
	 @Mode VARCHAR (50) 
)

AS 

DECLARE @sSQL NVARCHAR(MAX) = '' 



IF @Mode = 0 ---LOAD MASTER 
BEGIN 
 
	SELECT DISTINCT T1.*, T2.LeaveDate
	FROM EDMT2081 T1 WITH (NOLOCK)
	JOIN EDMT2080 T2 WITH (NOLOCK) ON T2.APKVoucher = T1.APKMaster
	WHERE CONVERT(VARCHAR(50), T1.APK) = @APK


END 



ELSE IF @Mode = 1 ----- Load detail khi thêm mới 
BEGIN 

SELECT T2.*, T3.StudentName
FROM EDMT2081 T1 WITH (NOLOCK) 
LEFT JOIN EDMT2082 T2 WITH (NOLOCK) ON T2.APKMaster = T1.APK
LEFT JOIN EDMT2010 T3 WITH (NOLOCK) ON T3.StudentID = T2.StudentID

WHERE CONVERT(VARCHAR(50), T1.APK) = @APK
ORDER BY T2.StudentID, T2.ReceiptTypeID



END 



----PRINT  @sSQL
EXEC (@sSQL)






GO
SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
