---- Create by Trương Tấn Thành on 8/14/2020 2:57:35 PM
---- Danh mục dữ liệu phân quyền

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[ST10504]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[ST10504]
(
  [APK] UNIQUEIDENTIFIER DEFAULT newid() NOT NULL,
  [ID] VARCHAR(200) NOT NULL,
  [ModuleID] VARCHAR(50) NOT NULL,
  [OrderNo] INT NULL,
  [Description] NVARCHAR(MAX) NULL,
  [DescriptionE] NVARCHAR(MAX) NULL,
  [Disabled] TINYINT DEFAULT (0) NULL,
  [LanguageID] VARCHAR(200) NULL,
  [CreateDate] DATETIME NULL,
  [CreateUserID] VARCHAR(200) NULL,
  [LastModifyDate] DATETIME NULL,
  [LastModifyUserID] VARCHAR(200) NULL
CONSTRAINT [PK_ST10504] PRIMARY KEY CLUSTERED
(
  [APK],
  [ID]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END