---- Create by Khâu Vĩnh Tâm on 6/2/2020 11:45:25 AM
---- Khóa/mở khóa kỳ kế toán module BEM

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[BEMT9999]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[BEMT9999]
(
  [APK] UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL,
  [DivisionID] VARCHAR(50) NOT NULL,
  [TranMonth] INT NULL,
  [TranYear] INT NULL,
  [Closing] TINYINT DEFAULT 0 NULL,
  [BeginDate] DATETIME NULL,
  [EndDate] DATETIME NULL
CONSTRAINT [PK_BEMT9999] PRIMARY KEY CLUSTERED
(
  [APK],
  [DivisionID]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END