---- Create by Cao Thị Phượng on 4/19/2017 2:08:09 PM
---- Định nghĩa tham số (Dữ liệu ngầm)

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[CRMT00001]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[CRMT00001]
(
  [APK] UNIQUEIDENTIFIER DEFAULT newid() NOT NULL,
  [DivisionID] VARCHAR(50) NOT NULL,
  [TypeID] VARCHAR(50) NOT NULL,
  [SystemName] NVARCHAR(250) NULL,
  [IsUsed] TINYINT DEFAULT 0 NOT NULL,
  [UserName] NVARCHAR(250) NULL,
  [UserNameE] NVARCHAR(250) NULL,
  [SystemNameE] NVARCHAR(250) NULL,
  [TransactionID] NVARCHAR(250) NULL
CONSTRAINT [PK_CRMT00001] PRIMARY KEY CLUSTERED
(
  [DivisionID],
  [TypeID]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END
