---- Create by Nguyễn Tấn Lộc on 7/10/2020 9:59:06 AM
---- Thông tin profile

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[CRMT2130]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[CRMT2130]
(
  [APK] UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL,
  [DivisionID] VARCHAR(50) NULL,
  [ProfileID] NVARCHAR(250) NULL,
  [ProfileName] NVARCHAR(MAX) NULL,
  [AccountID] VARCHAR(50) NULL,
  [APKCRMT2120] UNIQUEIDENTIFIER NULL,
  [CancellationRecords] NVARCHAR(MAX) NULL,
  [DeleteFlg] TINYINT DEFAULT 0 NULL,
  [CreateUserID] VARCHAR(50) NULL,
  [LastModifyUserID] VARCHAR(50) NULL,
  [CreateDate] DATETIME NULL,
  [LastModifyDate] DATETIME NULL
CONSTRAINT [PK_CRMT2130] PRIMARY KEY CLUSTERED
(
  [APK]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END

-------------------- 31/12/2020 - Tấn Lộc: Bổ sung cột ComputerName--------------------
IF NOT EXISTS (SELECT * FROM syscolumns col INNER JOIN sysobjects tab 
	   ON col.id = tab.id WHERE tab.name = 'CRMT2130' AND col.name = 'ComputerName')
BEGIN
	ALTER TABLE CRMT2130 ADD ComputerName NVARCHAR(MAX) NULL
END