---- Create by Nguyễn Tấn Lộc on 12/16/2019 10:15:51 AM
---- Mối liên hệ giữa Yêu cầu và Sản phẩm

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[CRMT20802]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[CRMT20802]
(
  [APK] UNIQUEIDENTIFIER DEFAULT newid() NOT NULL,
  [APKMaster] UNIQUEIDENTIFIER NULL,
  [RequestID] VARCHAR(50) NULL,
  [InventoryID] VARCHAR(50) NULL,
  [TypeID] INT NULL,
  [RelatedToTypeID] INT NULL
CONSTRAINT [PK_CRMT20802] PRIMARY KEY CLUSTERED
(
  [APK]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END