---- Create by Cao Thị Phượng on 3/6/2017 2:46:28 PM
---- File đính kèm và đối tượng liên quan

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[CRMT00002_REL]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[CRMT00002_REL]
(
  [APK] UNIQUEIDENTIFIER DEFAULT newid() NOT NULL,
  [DivisionID] VARCHAR(50) NOT NULL,
  [AttachID] INT NOT NULL,
  [RelatedToID] VARCHAR(250) NOT NULL,
  [RelatedToTypeID_REL] INT NOT NULL
CONSTRAINT [PK_CRMT00002_REL] PRIMARY KEY CLUSTERED
(
  [AttachID],
  [RelatedToID]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END