---- Create by Cao Thị Phượng on 2/16/2017 11:01:30 AM
---- Danh mục loại đầu mối

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[CRMT10201]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[CRMT10201]
(
  [APK] UNIQUEIDENTIFIER DEFAULT newid() NOT NULL,
  [DivisionID] VARCHAR(50) NOT NULL,
  [LeadTypeID] VARCHAR(50) NOT NULL,
  [LeadTypeName] NVARCHAR(250) NOT NULL,
  [Description] NVARCHAR(4000) NULL,
  [IsCommon] TINYINT DEFAULT (0) NULL,
  [Disabled] TINYINT DEFAULT (0) NULL,
  [CreateDate] DATETIME NULL,
  [CreateUserID] VARCHAR(50) NULL,
  [LastModifyDate] DATETIME NULL,
  [LastModifyUserID] VARCHAR(50) NULL,
  [RelatedToTypeID] INT DEFAULT 21 NOT NULL
CONSTRAINT [PK_CRMT10201] PRIMARY KEY CLUSTERED
(
  [LeadTypeID]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END