---- Create by Khâu Vĩnh Tâm on 11/26/2018 9:01:46 AM
---- Danh mục phân loại

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[CRMT1100]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[CRMT1100]
(
  [APK] UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL,
  [DivisionID] VARCHAR(50) NOT NULL,
  [KindID] VARCHAR(50) NOT NULL,
  [KindName] NVARCHAR(250) NOT NULL,
  [Description] NVARCHAR(MAX) NULL,
  [IsCommon] TINYINT DEFAULT 0 NULL,
  [Disabled] TINYINT DEFAULT 0 NULL,
  [CreateDate] DATETIME NULL,
  [CreateUserID] VARCHAR(50) NULL,
  [LastModifyDate] DATETIME NULL,
  [LastModifyUserID] VARCHAR(50) NULL
CONSTRAINT [PK_CRMT1100] PRIMARY KEY CLUSTERED
(
  [DivisionID],
  [KindID]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END