---- Create by Cao Thị Phượng on 3/6/2017 2:33:18 PM
---- Danh sách file đính kèm

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[CRMT00002]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[CRMT00002]
(
  [APK] UNIQUEIDENTIFIER DEFAULT newid() NOT NULL,
  [DivisionID] VARCHAR(50) NOT NULL,
  [AttachID] INT Identity(1,1) NOT NULL,
  [AttachFile] VARBINARY(8000) NULL,
  [AttachName] NVARCHAR(max) NULL,
  [DocumentType] VARCHAR(10) NULL,
  [UseESign] TINYINT NULL,				--- Sử dụng chữ ký số.
  [CreateDate] DATETIME NULL,
  [CreateUserID] VARCHAR(50) NULL,
  [LastModiFyDate] DATETIME NULL,
  [LastModiFyUserID] VARCHAR(50) NULL
CONSTRAINT [PK_CRMT00002] PRIMARY KEY CLUSTERED
(
  [AttachID]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END