--- Create by Cao Thị Phượng on 6/23/2017 4:14:14 PM
---- Danh mục lĩnh vực kinh doanh

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[CRMT10701]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[CRMT10701]
(
  [APK] UNIQUEIDENTIFIER DEFAULT newid() NOT NULL,
  [DivisionID] VARCHAR(50) NOT NULL,
  [BusinessLinesID] VARCHAR(50) NOT NULL,
  [BusinessLinesName] NVARCHAR(250) NOT NULL,
  [Description] NVARCHAR(max) NULL,
  [IsCommon] TINYINT DEFAULT (0) NULL,
  [Disabled] TINYINT DEFAULT (0) NULL,
  [CreateDate] DATETIME NULL,
  [CreateUserID] VARCHAR(50) NULL,
  [LastModifyDate] DATETIME NULL,
  [LastModifyUserID] VARCHAR(50) NULL
CONSTRAINT [PK_CRMT10701] PRIMARY KEY CLUSTERED
(
  [BusinessLinesID]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END