---- Create by Đào Tấn Đạt on 2/9/2018 11:21:42 AM
---- Đánh giá hỗ trợ khách hàng

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[CRMT2061]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[CRMT2061]
(
  [APK] UNIQUEIDENTIFIER DEFAULT newid() NOT NULL,
  [DivisionID] VARCHAR(50) NOT NULL,
  [DeleteFlag] TINYINT DEFAULT (0) NOT NULL,
  [CreateUserID] VARCHAR(50) NULL,
  [CreateDate] DATETIME NULL,
  [LastModifyUserID] VARCHAR(50) NULL,
  [LastModifyDate] DATETIME NULL,
  [RealTime] DECIMAL(10,2) NOT NULL,
  [ReviewDescription] NVARCHAR(Max) NOT NULL,
  [FeedbackDescription] NVARCHAR(Max) NOT NULL,
  [Status] INT NOT NULL,
  [EmployeeID] VARCHAR(50) NOT NULL,
  [RelatedToTypeID] INT NULL,
  [RelatedToID] INT NULL
CONSTRAINT [PK_CRMT2061] PRIMARY KEY CLUSTERED
(
  [APK]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END