---- Create by Cao Thị Phượng on 3/13/2017 3:21:20 PM
---- Mối liên hệ giữa yêu cầu và khách hàng

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[CRMT20801_CRMT10101_REL]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[CRMT20801_CRMT10101_REL]
(
  [APK] UNIQUEIDENTIFIER DEFAULT newid() NOT NULL,
  [AccountID] VARCHAR(50) NOT NULL,
  [RequestID] INT NOT NULL
CONSTRAINT [PK_CRMT20801_CRMT10101_REL] PRIMARY KEY CLUSTERED
(
  [AccountID],
  [RequestID]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END
