---- Create by Đào Tấn Đạt on 2/6/2018 2:46:44 PM
---- Xử lý công việc

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[CRMT2083]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[CRMT2083]
(
  [APK] UNIQUEIDENTIFIER DEFAULT newid() NOT NULL,
  [DivisionID] VARCHAR(50) NOT NULL,
  [DeleteFlag] TINYINT DEFAULT (0) NOT NULL,
  [CreateUserID] VARCHAR(50) NULL,
  [CreateDate] DATETIME NULL,
  [LastModifyUserID] VARCHAR(50) NULL,
  [LastModifyDate] DATETIME NULL,
  [Description] NVARCHAR(250) NOT NULL,
  [AssignUserID] VARCHAR(50) NOT NULL,
  [RealDate] DATETIME NULL,
  [WorkTime] DECIMAL(10,2) NULL,
  [ReleatedToTypeID] INT NULL,
  [ReleatedToID] VARCHAR(50) NOT NULL
CONSTRAINT [PK_CRMT2083] PRIMARY KEY CLUSTERED
(
  [APK]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END