---- Create by Nguyễn Tấn Lộc on 11/16/2020 9:21:03 AM
---- Quản lý chiến dịch mail

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[CRMT2140]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[CRMT2140]
(
  [APK] UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL,
  [DivisionID] VARCHAR(50) NULL,
  [CampaignMailID] VARCHAR(50) NULL,
  [CampaignMailName] NVARCHAR(MAX) NULL,
  [CampaignID] VARCHAR(50) NULL,
  [GroupReceiverID] VARCHAR(MAX) NULL,
  [TemplateID] VARCHAR(50) NULL,
  [QuantitySendEmail] VARCHAR(50) NULL,
  [StatusCampaignEmail] VARCHAR(50) NULL,
  [QuantitySendEmailSucceed] VARCHAR(50) NULL,
  [QuantitySendEmailFail] VARCHAR(50) NULL,
  [QuantityEmailUnsubcription] VARCHAR(50) NULL,
  [APKSettingTime] VARCHAR(250) NULL,
  [DeleteFlg] TINYINT DEFAULT 0 NULL,
  [CreateUserID] VARCHAR(50) NULL,
  [LastModifyUserID] VARCHAR(50) NULL,
  [CreateDate] DATETIME NULL,
  [LastModifyDate] DATETIME NULL
CONSTRAINT [PK_CRMT2140] PRIMARY KEY CLUSTERED
(
  [APK]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END