---- Create by Đào Tấn Đạt on 2/5/2018 11:27:38 AM
---- Mối liên hệ giữa Yêu cầu và liên hệ

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[CRMT20801_CRMT10001_REL]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[CRMT20801_CRMT10001_REL]
(
  [APK] UNIQUEIDENTIFIER DEFAULT newid() NOT NULL,
  [RequestID] INT NOT NULL,
  [ContactID] VARCHAR(50) NOT NULL
CONSTRAINT [PK_CRMT20801_CRMT10001_REL] PRIMARY KEY CLUSTERED
(
  [RequestID],
  [ContactID]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END