---- Create by Cao Thị Phượng on 3/7/2017 1:14:09 PM
---- Mối liên hệ giữa khách hàng và đơn hàng

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[CRMT10101_OT2001_REL]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[CRMT10101_OT2001_REL]
(
  [APK] UNIQUEIDENTIFIER DEFAULT newid() NOT NULL,
  [AccountID] VARCHAR(50) NOT NULL,
  [SOrderID] VARCHAR(50) NOT NULL
CONSTRAINT [PK_CRMT10101_OT2001_REL] PRIMARY KEY CLUSTERED
(
  [AccountID],
  [SOrderID]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END