---- Create by Nguyễn Tấn Lộc on 5/27/2021 3:59:11 PM
---- Chiến dịch sms

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[CRMT2190]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[CRMT2190]
(
  [APK] UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL,
  [DivisionID] VARCHAR(50) NULL,
  [CampaignSMSID] VARCHAR(50) NULL,
  [CampaignSMSName] NVARCHAR(MAX) NULL,
  [CampaignID] VARCHAR(50) NULL,
  [GroupReceiverID] VARCHAR(MAX) NULL,
  [TemplateID] VARCHAR(50) NULL,
  [QuantitySendSMS] VARCHAR(50) NULL,
  [StatusCampaignSMS] VARCHAR(50) NULL,
  [QuantitySendSMSSucceed] VARCHAR(50) NULL,
  [QuantitySendSMSFail] VARCHAR(50) NULL,
  [QuantitySMSUnsubcription] VARCHAR(50) NULL,
  [APKSettingTime] VARCHAR(250) NULL,
  [DeleteFlg] TINYINT DEFAULT 0 NULL,
  [CreateUserID] VARCHAR(50) NULL,
  [LastModifyUserID] VARCHAR(50) NULL,
  [CreateDate] DATETIME NULL,
  [LastModifyDate] DATETIME NULL
CONSTRAINT [PK_CRMT2190] PRIMARY KEY CLUSTERED
(
  [APK]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END