---- Create by Cao Thị Phượng on 3/8/2017 10:21:41 AM
---- Mối liên hệ giữa khách hàng và báo giá

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[CRMT10101_OT2101_REL]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[CRMT10101_OT2101_REL]
(
  [APK] UNIQUEIDENTIFIER DEFAULT newid() NOT NULL,
  [AccountID] VARCHAR(50) NOT NULL,
  [QuotationID] VARCHAR(50) NOT NULL
CONSTRAINT [PK_CRMT10101_OT2101_REL] PRIMARY KEY CLUSTERED
(
  [AccountID],
  [QuotationID]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END