---- Create by Cao Thị Phượng on 3/8/2017 8:11:57 AM
---- Mối liên hệ giữa chiến dịch và đơn hàng

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[CRMT20401_OT2001_REL]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[CRMT20401_OT2001_REL]
(
  [APK] UNIQUEIDENTIFIER DEFAULT newid() NOT NULL,
  [CampaignID] VARCHAR(50) NOT NULL,
  [SOrderID] VARCHAR(50) NOT NULL
CONSTRAINT [PK_CRMT20401_OT2001_REL] PRIMARY KEY CLUSTERED
(
  [CampaignID],
  [SOrderID]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END