---- Create by Nguyễn Tấn Lộc on 7/10/2020 10:20:14 AM
---- Chi tiết thông tin profile

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[CRMT2131]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[CRMT2131]
(
  [APK] UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL,
  [APKMaster] UNIQUEIDENTIFIER NULL,
  [ComputerName] VARCHAR(50) NULL,
  [ID1] VARCHAR(50) NULL,
  [ID2] VARCHAR(50) NULL,
  [Modules] NVARCHAR(250) NULL,
  [ReportOnly] VARCHAR(50) NULL,
  [StatusID] VARCHAR(50) NULL,
  [ApprovedLicense] VARCHAR(50) NULL,
  [CancelLicense] VARCHAR(50) NULL,
  [FileLic] VARCHAR(50) NULL,
  [DeleteFlg] TINYINT DEFAULT 0 NULL,
  [CreateUserID] VARCHAR(50) NULL,
  [LastModifyUserID] VARCHAR(50) NULL,
  [CreateDate] DATETIME NULL,
  [LastModifyDate] DATETIME NULL
CONSTRAINT [PK_CRMT2131] PRIMARY KEY CLUSTERED
(
  [APK]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END