---- Create by Phan thanh hoàng vũ on 3/7/2017 4:19:01 PM
---- Danh mục lý do

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[CRMT10501]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[CRMT10501]
(
  [APK] UNIQUEIDENTIFIER DEFAULT newid() NOT NULL,
  [DivisionID] VARCHAR(50) NOT NULL,
  [CauseID] VARCHAR(50) NOT NULL,
  [CauseName] NVARCHAR(250) NOT NULL,
  [Disabled] TINYINT DEFAULT (0) NULL,
  [IsCommon] TINYINT DEFAULT (0) NULL,
  [CreateUserID] VARCHAR(50) NULL,
  [CreateDate] DATETIME NULL,
  [LastModifyUserID] VARCHAR(50) NULL,
  [LastModifyDate] DATETIME NULL,
  [Description] NVARCHAR(250) NULL,
  [CauseType] TINYINT DEFAULT (1) NOT NULL
CONSTRAINT [PK_CRMT10501] PRIMARY KEY CLUSTERED
(
  [CauseID]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END