---- Create by Nguyễn Hoàng Bảo Thy on 2/3/2017 10:40:22 AM
---- Master quyết toán (EIMSKIP)

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[WT0100]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[WT0100]
(
  [APK] UNIQUEIDENTIFIER DEFAULT newid() NOT NULL,
  [DivisionID] VARCHAR(50) NOT NULL,
  [VoucherTypeID] VARCHAR(50) NULL,
  [VoucherID] VARCHAR(50) NOT NULL,
  [VoucherNo] VARCHAR(50) NOT NULL,
  [VoucherDate] DATETIME NULL,
  [ContractID] VARCHAR(50) NOT NULL,
  [ObjectID] VARCHAR(50) NOT NULL,
  [DayUnit] TINYINT NULL,
  [FromDate] DATETIME NULL,
  [ToDate] DATETIME NULL,
  [CreateUserID] VARCHAR(50) NULL,
  [CreateDate] DATETIME NULL,
  [LastModifyUserID] VARCHAR(50) NULL,
  [LastModifyDate] DATETIME NULL
CONSTRAINT [PK_WT0100] PRIMARY KEY CLUSTERED
(
  [DivisionID],
  [VoucherID],
  [ObjectID]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END