---- Create by Nguyễn Hoàng Bảo Thy on 2/3/2017 10:42:24 AM
---- Detail quyết toán (EIMSKIP)

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[WT0103]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[WT0103]
(
  [APK] UNIQUEIDENTIFIER DEFAULT newid() NOT NULL,
  [DivisionID] VARCHAR(50) NOT NULL,
  [TransationID] VARCHAR(50) NOT NULL,
  [VoucherID] VARCHAR(50) NULL,
  [DetailTransationID] VARCHAR(50) NULL,
  [DetailVoucherID] VARCHAR(50) NULL,
  [DetailVoucherNo] VARCHAR(50) NULL,
  [DetailVoucherDate] DATETIME NULL,
  [Type] VARCHAR(50) NULL,
  [CostID] VARCHAR(50) NULL,
  [WareHouseID] VARCHAR(50) NULL,
  [InventoryID] VARCHAR(50) NULL,
  [Quantity] DECIMAL(28,8) NULL,
  [DetailFromDate] DATETIME NULL,
  [DetailToDate] DATETIME NULL,
  [UnitPrice] DECIMAL(28,8) NULL,
  [OriginalAmount] DECIMAL(28,8) NULL,
  [ConvertAmount] DECIMAL(28,8) NULL
CONSTRAINT [PK_WT0103] PRIMARY KEY CLUSTERED
(
  [DivisionID],
  [TransationID]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END