IF NOT EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[CCMT0004]') AND TYPE IN (N'U'))
BEGIN
     CREATE TABLE [dbo].[CCMT0004]
     (
      [APK] UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL,
      [DivisionID] VARCHAR(50) NULL,
      [GroupID] NVARCHAR(50) NOT NULL,
      [GroupName] NVARCHAR(Max) NULL,
	  [IsPerson] TINYINT  DEFAULT (0) NULL,
      [CreateUserID] VARCHAR(50) NOT NULL,
      [CreateDate] DATETIME NULL,
	  [LastModifyUserID] VARCHAR(50) NOT NULL,
      [LastModifyDate] DATETIME NULL
    CONSTRAINT [PK_CCMT0004] PRIMARY KEY CLUSTERED
      (
      [GroupID]
      )
WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
     )
 ON [PRIMARY]
END