/****** Object:  Index [AT1302_Index1]    Script Date: 06/03/2019 - Kim Thư ******/
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[AT1302]') AND name = N'AT1302_Index1')
DROP INDEX [AT1302_Index1] ON [dbo].[AT1302] WITH ( ONLINE = OFF )
CREATE NONCLUSTERED INDEX [AT1302_Index1] ON [dbo].[AT1302] 
(
	[DivisionID] ASC,
	[MethodID] ASC,
	[InventoryID] ASC
	
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]

/****** Object:  Index [AT1302_Index2]    Script Date: 20/03/2019 - Kim Thư ******/
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[AT1302]') AND name = N'AT1302_Index2')
DROP INDEX [AT1302_Index2] ON [dbo].[AT1302] WITH ( ONLINE = OFF )
CREATE NONCLUSTERED INDEX [AT1302_Index2] ON [dbo].[AT1302] 
(
	[InventoryID] ASC,
	[MethodID] ASC,
	[IsSource] ASC,
	[IsLimitDate] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]

IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[AT1302]') AND name = N'AT1302_Index3')
DROP INDEX [AT1302_Index3] ON [dbo].[AT1302] WITH ( ONLINE = OFF )
CREATE NONCLUSTERED INDEX [AT1302_Index3] ON [dbo].[AT1302] 
(
	[DivisionID] ASC,
	[Disabled] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
