IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[AT1101]') AND name = N'AT1101_Index1')
DROP INDEX [AT1101_Index1] ON [dbo].[AT1101] WITH ( ONLINE = OFF )
CREATE NONCLUSTERED INDEX [AT1101_Index1] ON [dbo].[AT1101] 
(
	[DivisionID] ASC,
	[Disabled] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, 
ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
