/****** Object:  Index [AT2007_DivisionID_VoucherID]    Script Date: 10/09/2012 14:15:35 ******/
--AT2007
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[AT2007]') AND name = N'AT2007_DivisionID_VoucherID')
DROP INDEX [AT2007_DivisionID_VoucherID] ON [dbo].[AT2007] WITH ( ONLINE = OFF )
GO
/****** Object:  Index [AT2007_DivisionID_VoucherID]    Script Date: 10/09/2012 14:15:35 ******/
CREATE NONCLUSTERED INDEX [AT2007_DivisionID_VoucherID] ON [dbo].[AT2007] 
(
	[DivisionID] ASC,
	[VoucherID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO


IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[AT2007]') AND name = N'AT2007_Index1')
DROP INDEX [AT2007_Index1] ON [dbo].[AT2007] WITH ( ONLINE = OFF )
CREATE NONCLUSTERED INDEX [AT2007_Index1] ON [dbo].[AT2007] 
(
	[DivisionID] ASC,
	[ReVoucherID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]

IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[AT2007]') AND name = N'AT2007_Index2')
DROP INDEX [AT2007_Index2] ON [dbo].[AT2007] WITH ( ONLINE = OFF )
CREATE NONCLUSTERED INDEX [AT2007_Index2] ON [dbo].[AT2007] 
(
	[DivisionID] ASC,
	[TranYear] ASC,
	[TranMonth] ASC,
	[InventoryID] ASC,
	[CreditAccountID] ASC,
	[VoucherID] ASC,
	[TransactionID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]

IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[AT2007]') AND name = N'AT2007_Index3')
DROP INDEX [AT2007_Index3] ON [dbo].[AT2007] WITH ( ONLINE = OFF )
CREATE NONCLUSTERED INDEX [AT2007_Index3] ON [dbo].[AT2007] 
(
	[DivisionID] ASC,
	[InventoryID] ASC,
	[TransactionID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]

-- [Văn Tài] Created [30/06/2021] - xóa các index cũ của AT2007
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[AT2007]') AND name = N'AT2007_Index4')
DROP INDEX [AT2007_Index4] ON [dbo].[AT2007] WITH ( ONLINE = OFF )
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[AT2007]') AND name = N'AT2007_Index5')
DROP INDEX [AT2007_Index5] ON [dbo].[AT2007] WITH ( ONLINE = OFF )
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[AT2007]') AND name = N'AT2007_Index6')
DROP INDEX [AT2007_Index6] ON [dbo].[AT2007] WITH ( ONLINE = OFF )
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[AT2007]') AND name = N'AT2007_Index7')
DROP INDEX [AT2007_Index7] ON [dbo].[AT2007] WITH ( ONLINE = OFF )
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[AT2007]') AND name = N'AT2007_Index8')
DROP INDEX [AT2007_Index8] ON [dbo].[AT2007] WITH ( ONLINE = OFF )
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[AT2007]') AND name = N'AT2007_Index9')
DROP INDEX [AT2007_Index9] ON [dbo].[AT2007] WITH ( ONLINE = OFF )
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[AT2007]') AND name = N'AT2007_Index10')
DROP INDEX [AT2007_Index10] ON [dbo].[AT2007] WITH ( ONLINE = OFF )
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[AT2007]') AND name = N'AT2007_Index11')
DROP INDEX [AT2007_Index11] ON [dbo].[AT2007] WITH ( ONLINE = OFF )
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[AT2007]') AND name = N'AT2007_Index12')
DROP INDEX [AT2007_Index12] ON [dbo].[AT2007] WITH ( ONLINE = OFF )
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[AT2007]') AND name = N'AT2007_Index13')
DROP INDEX [AT2007_Index13] ON [dbo].[AT2007] WITH ( ONLINE = OFF )
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[AT2007]') AND name = N'AT2007_Index14')
DROP INDEX [AT2007_Index14] ON [dbo].[AT2007] WITH ( ONLINE = OFF )