/****** Object:  Index [AT0303_Index1]    Script Date: 07/06/2019 - Kim Thư ******/
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[AT0303]') AND name = N'AT0303_Index1')
DROP INDEX [AT0303_Index1] ON [dbo].[AT0303] WITH ( ONLINE = OFF )
CREATE NONCLUSTERED INDEX [AT0303_Index1] ON [dbo].[AT0303] 
(
	[DivisionID] ASC,
	[DebitTableID] ASC,
	[DebitVoucherID] ASC,
	[DebitBatchid] ASC
	
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]

IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[AT0303]') AND name = N'AT0303_Index2')
DROP INDEX [AT0303_Index2] ON [dbo].[AT0303] WITH ( ONLINE = OFF )
CREATE NONCLUSTERED INDEX [AT0303_Index2] ON [dbo].[AT0303] 
(	
	[CreditVoucherID] ASC	
	
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]

