/****** Object:  Index [AT1202_Index1]    Script Date: 07/06/2019 - Kim Thư ******/
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[AT1202]') AND name = N'AT1202_Index1')
DROP INDEX [AT1202_Index1] ON [dbo].[AT1202] WITH ( ONLINE = OFF )
CREATE NONCLUSTERED INDEX [AT1202_Index1] ON [dbo].[AT1202] 
(
	[DivisionID] ASC,
	[Disabled] ASC,
	[ObjectID] ASC
	
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
