/****** Object:  Index [MT0810_Index1]    Script Date: 20/03/2019 Kim Thư ******/
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[MT0810]') AND name = N'MT0810_Index1')
DROP INDEX [MT0810_Index1] ON [dbo].[MT0810] WITH ( ONLINE = OFF )
GO
CREATE NONCLUSTERED INDEX [MT0810_Index1] ON [dbo].[MT0810] 
(
	[DivisionID] ASC,
	[PeriodID] ASC,
	[VoucherID] ASC,
	[ResultTypeID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO