/****** Object:  Index [MT1001_Index1]    Script Date: 20/03/2019 Kim Thư ******/
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[MT1001]') AND name = N'MT1001_Index1')
DROP INDEX [MT1001_Index1] ON [dbo].[MT1001] WITH ( ONLINE = OFF )
GO
CREATE NONCLUSTERED INDEX [MT1001_Index1] ON [dbo].[MT1001] 
(
	[DivisionID] ASC,
	[VoucherID] ASC,
	[TransactionID] ASC,
	[ProductID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO