IF NOT EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[APT0016]') AND TYPE IN (N'U'))
BEGIN
     CREATE TABLE [dbo].[APT0016]
     (
		[APK] UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL,
		[UserID] VARCHAR(50) NOT NULL,
		[Token] NVARCHAR(250) NOT NULL,
		[Platform] NVARCHAR(50) NULL,
		[ClientID] NVARCHAR(250) NULL,
		[ARN] VARCHAR(512) NULL,
		[Disabled] TINYINT DEFAULT (0) NULL,
		[CreateUserID] VARCHAR(50) NULL,
		[LastModifyUserID] VARCHAR(50) NULL,
		[CreateDate] DATETIME2 DEFAULT SYSUTCDATETIME() NULL,
		[LastModifyDate] DATETIME2 DEFAULT SYSUTCDATETIME() NULL

		CONSTRAINT [PK_APT0016] PRIMARY KEY CLUSTERED
		(
			[UserID],
			[Token]
		)
		WITH (
			PAD_INDEX  = OFF,
			STATISTICS_NORECOMPUTE  = OFF,
			IGNORE_DUP_KEY = OFF,
			ALLOW_ROW_LOCKS  = ON,
			ALLOW_PAGE_LOCKS  = ON
			)
		ON [PRIMARY]
     )
	 ON [PRIMARY]
END

-- APK index
IF(EXISTS(
	SELECT *
	FROM sys.indexes
	WHERE name='IDX_APT0016_APK' AND object_id = OBJECT_ID('[dbo].[APT0016]')
))
BEGIN
	DROP INDEX [IDX_APT0016_APK] ON dbo.[APT0016];
END

CREATE NONCLUSTERED INDEX [IDX_APT0016_APK] ON [dbo].[APT0016]([APK])
