IF NOT EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[APT0017]') AND TYPE IN (N'U'))
BEGIN
     CREATE TABLE [dbo].[APT0017]
     (
		[APK] UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL,
		[APKToken] UNIQUEIDENTIFIER NOT NULL,
		[GroupID] VARCHAR(256) NOT NULL,
		[SubscriptionARN] VARCHAR(512) NOT NULL,
		[Disabled] TINYINT DEFAULT (0) NULL,
		[CreateUserID] VARCHAR(50) NULL,
		[LastModifyUserID] VARCHAR(50) NULL,
		[CreateDate] DATETIME2 DEFAULT SYSUTCDATETIME() NULL,
		[LastModifyDate] DATETIME2 DEFAULT SYSUTCDATETIME() NULL

		CONSTRAINT [PK_APT0017] PRIMARY KEY CLUSTERED
		(
			[APKToken],
			[GroupID]
		)
		WITH (
			PAD_INDEX  = OFF,
			STATISTICS_NORECOMPUTE  = OFF,
			IGNORE_DUP_KEY = OFF,
			ALLOW_ROW_LOCKS  = ON,
			ALLOW_PAGE_LOCKS  = ON
			)
		ON [PRIMARY]
     )
	 ON [PRIMARY]
END

-- APK index
IF(EXISTS(
	SELECT *
	FROM sys.indexes
	WHERE name='IDX_APT0017_APK' AND object_id = OBJECT_ID('[dbo].[APT0017]')
))
BEGIN
	DROP INDEX [IDX_APT0017_APK] ON dbo.[APT0017];
END

CREATE NONCLUSTERED INDEX [IDX_APT0017_APK] ON [dbo].[APT0017]([APK])