IF NOT EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[CIT1013]') AND TYPE IN (N'U'))
BEGIN
     CREATE TABLE [dbo].[CIT1013]
     (
      [APK] UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL,
      [DivisionID] VARCHAR(50) NULL,
      [TeamID] VARCHAR(50) NOT NULL,
      [EmployeeID] VARCHAR(50) NOT NULL,
      [CreateUserID] VARCHAR(50) NULL,
      [CreateDate] DATETIME NULL
    CONSTRAINT [PK_CIT1013] PRIMARY KEY CLUSTERED
      (
      [TeamID],
      [EmployeeID]
      )
WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
     )
 ON [PRIMARY]
END