---- Create by Cao Thị Phượng on 9/11/2017 3:59:53 PM
---- Thiết lập chi tiết cấp duyệt

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[CIT1202]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[CIT1202]
(
  [APK] UNIQUEIDENTIFIER DEFAULT newid() NOT NULL,
  [APKMaster] UNIQUEIDENTIFIER DEFAULT newid() NOT NULL,
  [DivisionID] VARCHAR(50) NOT NULL,
  [RollLevel] INT NULL,
  [DutyID] VARCHAR(50) NULL
CONSTRAINT [PK_CIT1202] PRIMARY KEY CLUSTERED
(
  [APK]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END