IF EXISTS (SELECT TOP 1 1 FROM DBO.SYSOBJECTS WHERE ID = OBJECT_ID(N'[DBO].[BEMP9000]') AND  OBJECTPROPERTY(ID, N'IsProcedure') = 1)			
DROP PROCEDURE [DBO].[BEMP9000]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO



-- <Summary>
-- Kiểm tra dữ liệu đã được duyệt hay chưa trước khi xóa
-- <Param>
-- <Return>
-- <Reference>
-- <History>
-- <Created by>: Tấn Thành, Date: 20/11/2015
-- <Example>

CREATE PROCEDURE [dbo].[BEMP9000] 	
(
	@DivisionID VARCHAR(50),
	@FormID NVARCHAR(50),
	@TableID NVARCHAR(50) = NULL,
	@APK UNIQUEIDENTIFIER = NULL, 
	@ID VARCHAR(MAX) = NULL, 
	@TranMonth INT = NULL, 
	@TranYear INT = NULL,
	@Status TINYINT OUTPUT
)
AS 
DECLARE @Message AS NVARCHAR(250)


IF @TableID = 'BEMT2020' 
	BEGIN
		IF EXISTS(SELECT TOP 1 1 FROM BEMT2020 B1 WITH (NOLOCK) 
					LEFT JOIN OOT9000 O1 WITH (NOLOCK) ON B1.APKMaster_9000 = O1.APK
					LEFT JOIN OOT9001 O2 WITH (NOLOCK) ON O2.APKMaster = O1.APK AND O2.DivisionID = @DivisionID
					WHERE B1.APK = @APK AND B1.DivisionID = @DivisionID AND O2.[Status] = 1)
		BEGIN
			SET @Status = 1
			SET @Message = N'00ML000117'
			GOTO Mess
		END
	END

IF @TableID = 'BEMT2030' 
	BEGIN
		IF EXISTS(SELECT TOP 1 1 FROM BEMT2030 B1 WITH (NOLOCK) 
					LEFT JOIN OOT9000 O1 WITH (NOLOCK) ON B1.APKMaster_9000 = O1.APK
					LEFT JOIN OOT9001 O2 WITH (NOLOCK) ON O2.APKMaster = O1.APK AND O2.DivisionID = @DivisionID
					WHERE B1.APK = @APK AND B1.DivisionID = @DivisionID AND O2.[Status] = 1)
		BEGIN
			SET @Status = 1
			SET @Message = N'00ML000117'
			GOTO Mess
		END
	END

IF @TableID = 'BEMT2040' 
	BEGIN
		IF EXISTS(SELECT TOP 1 1 FROM BEMT2040 B1 WITH (NOLOCK) 
					LEFT JOIN OOT9000 O1 WITH (NOLOCK) ON B1.APKMaster_9000 = O1.APK
					LEFT JOIN OOT9001 O2 WITH (NOLOCK) ON O2.APKMaster = O1.APK AND O2.DivisionID = @DivisionID
					WHERE B1.APK = @APK AND B1.DivisionID = @DivisionID AND O2.[Status] = 1)
		BEGIN
			SET @Status = 1
			SET @Message = N'00ML000117'
			GOTO Mess
		END
	END

IF @TableID = 'BEMT2050' 
	BEGIN
		IF EXISTS(SELECT TOP 1 1 FROM BEMT2050 B1 WITH (NOLOCK) 
					LEFT JOIN OOT9000 O1 WITH (NOLOCK) ON B1.APKMaster_9000 = O1.APK
					LEFT JOIN OOT9001 O2 WITH (NOLOCK) ON O2.APKMaster = O1.APK AND O2.DivisionID = @DivisionID
					WHERE B1.APK = @APK AND B1.DivisionID = @DivisionID AND O2.[Status] = 1)
		BEGIN
			SET @Status = 1
			SET @Message = N'00ML000117'
			GOTO Mess
		END
	END

IF @TableID = 'BEMT2010'
	BEGIN 
		IF EXISTS(SELECT TOP 1 1 FROM BEMT2010 B1 WITH (NOLOCK) 
					LEFT JOIN OOT9000 O1 WITH (NOLOCK) ON B1.APKMaster_9000 = O1.APK
					LEFT JOIN OOT9001 O2 WITH (NOLOCK) ON O2.APKMaster = O1.APK AND O2.DivisionID = @DivisionID
					WHERE B1.APK = @APK AND B1.DivisionID = @DivisionID AND O2.[Status] = 1)
			BEGIN
				SET @Status = 1
				SET @Message = N'00ML000117'
				GOTO Mess
			END

				IF EXISTS(SELECT TOP 1 1 FROM BEMT2020 B1 WITH (NOLOCK) 
							LEFT JOIN OOT9000 O1 WITH (NOLOCK) ON B1.APKMaster_9000 = O1.APK
							LEFT JOIN OOT9001 O2 WITH (NOLOCK) ON O2.APKMaster = O1.APK AND O2.DivisionID = @DivisionID
							WHERE B1.APKMaster = @APK AND B1.DivisionID = @DivisionID AND O2.[Status] = 1)
					BEGIN
						SET @Status = 1
						SET @Message = N'00ML000117'
						GOTO Mess
					END
				IF EXISTS(SELECT TOP 1 1 FROM BEMT2030 B1 WITH (NOLOCK) 
							LEFT JOIN OOT9000 O1 WITH (NOLOCK) ON B1.APKMaster_9000 = O1.APK
							LEFT JOIN OOT9001 O2 WITH (NOLOCK) ON O2.APKMaster = O1.APK AND O2.DivisionID = @DivisionID
							WHERE B1.APKMaster = @APK AND B1.DivisionID = @DivisionID AND O2.[Status] = 1)
					BEGIN
						SET @Status = 1
						SET @Message = N'00ML000117'
						GOTO Mess
					END
				IF EXISTS(SELECT TOP 1 1 FROM BEMT2040 B1 WITH (NOLOCK) 
							LEFT JOIN OOT9000 O1 WITH (NOLOCK) ON B1.APKMaster_9000 = O1.APK
							LEFT JOIN OOT9001 O2 WITH (NOLOCK) ON O2.APKMaster = O1.APK AND O2.DivisionID = @DivisionID
							WHERE B1.APKMaster = @APK AND B1.DivisionID = @DivisionID AND O2.[Status] = 1)
					BEGIN
						SET @Status = 1
						SET @Message = N'00ML000117'
						GOTO Mess
					END
				IF EXISTS(SELECT TOP 1 1 FROM BEMT2050 B1 WITH (NOLOCK) 
							LEFT JOIN OOT9000 O1 WITH (NOLOCK) ON B1.APKMaster_9000 = O1.APK
							LEFT JOIN OOT9001 O2 WITH (NOLOCK) ON O2.APKMaster = O1.APK AND O2.DivisionID = @DivisionID
							WHERE B1.APKMaster = @APK AND B1.DivisionID = @DivisionID AND O2.[Status] = 1)
					BEGIN
						SET @Status = 1
						SET @Message = N'00ML000117'
						GOTO Mess
					END
	END

IF @TableID = 'BEMT2000'
	BEGIN 
	-- Kiểm tra phiếu đã được duyệt.
		IF (EXISTS(SELECT TOP 1 1 FROM BEMT2000 B1 WITH (NOLOCK) 
					LEFT JOIN OOT9000 O1 WITH (NOLOCK) ON B1.APKMaster_9000 = O1.APK
					LEFT JOIN OOT9001 O2 WITH (NOLOCK) ON O2.APKMaster = O1.APK AND O2.DivisionID = @DivisionID
					WHERE B1.APK = @APK AND B1.DivisionID = @DivisionID AND O2.[Status] = 1)
			OR EXISTS(SELECT TOP 1 1 FROM BEMT2001 B1 WITH (NOLOCK) 
					LEFT JOIN OOT9000 O1 WITH (NOLOCK) ON B1.APKMaster_9000 = O1.APK
					LEFT JOIN OOT9001 O2 WITH (NOLOCK) ON O2.APKMaster = O1.APK AND O2.DivisionID = @DivisionID
					WHERE B1.APKMaster = @APK AND B1.DivisionID = @DivisionID AND O2.[Status] = 1))
			BEGIN
				SET @Status = 1
				SET @Message = N'00ML000117'
				GOTO Mess
			END

	-- Kiểm tra phiếu đã được kế thừa.
		IF EXISTS(SELECT TOP 1 1
					FROM BEMT2000 B1 WITH (NOLOCK)
						LEFT JOIN BEMT2001 B2 WITH (NOLOCK) ON B2.APKMaster = B1.APK AND B2.DivisionID = B1.DivisionID
						LEFT JOIN BEMT2000 B3 WITH (NOLOCK) ON B3.DivisionID = B1.DivisionID
						LEFT JOIN BEMT2001 B4 WITH (NOLOCK) ON B4.APKMaster = B3.APK AND B4.DivisionID = B1.DivisionID
					WHERE B1.DivisionID = @DivisionID AND B1.APK = @APK AND (B3.APKInherited = B1.APK OR B4.APKDInherited = B2.APK OR B4.APKMInherited = B1.APK))
			BEGIN
				SET @Status = 1
				SET @Message = N'00ML000179'
				GOTO Mess
			END
				
	END

IF @TableID = 'BEMT1000'
	BEGIN
		IF(EXISTS(
			SELECT TOP 1 1 
			FROM BEMT1000 B1 WITH (NOLOCK)
				INNER JOIN BEMT2021 B2 WITH (NOLOCK) ON B2.FeeID = B1.FeeID AND B2.DivisionID = B1.DivisionID
			WHERE B1.APK = @APK AND B1.DivisionID = @DivisionID))

			BEGIN
				SET @Status = 1
				SET @Message = N'00ML000165' 
				GOTO Mess
			END
			
	END
Mess:



GO
SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
