IF EXISTS (SELECT TOP 1 1 FROM DBO.SYSOBJECTS WHERE ID = OBJECT_ID(N'[DBO].[ATX1202]') AND OBJECTPROPERTY(ID, N'IsTrigger') = 1)
DROP TRIGGER [DBO].ATX1202
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE TRIGGER [dbo].[ATX1202] ON [dbo].[AT1202] 
FOR DELETE
AS

DECLARE @DivisionID NVARCHAR(50),
		@ObjectID VARCHAR(50),
		@ObjectTypeID VARCHAR(50),
		@ObjectName NVARCHAR(250)
		
SELECT @DivisionID = DivisionID, @ObjectID = ObjectID, @ObjectTypeID = ObjectTypeID, @ObjectName = ObjectName
FROM DELETED 

IF (EXISTS (SELECT TOP 1 1 FROM MTT2000 WHERE DivisionID = @DivisionID AND StudentID = @ObjectID)
AND NOT EXISTS (SELECT TOP 1 1 FROM MTT2010 WHERE DivisionID = @DivisionID AND StudentID = @ObjectID))
DELETE FROM MTT2000 WHERE DivisionID = @DivisionID AND StudentID = @ObjectID

GO
SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
