-- <Summary>
---- Template import data: Nghiệp vụ phân hệ ERP9
-- <History>
---- Create on 11/06/2021 by Đức Tuyên: Thêm dữ liệu Nghiệp vụ kế hoạch sản xuất

---- <Example>
	--SELECT * FROM A00065 WHERE ImportTransTypeID = N'SupplierQuotes'
	----------------------- Nghiệp vụ kế hoạch sản xuất ----------------------- 
IF NOT EXISTS (SELECT TOP 1 1 FROM A01065 WHERE ImportTemplateID = 'ProductionPlan')
BEGIN
	INSERT INTO A01065(ImportTemplateID, ImportTemplateName, ImportTransTypeID, DefaultSheet, AnchorCol, StartRow, DataFolder, DefaultFileName, 
	[Disabled],CreateUserID, CreateDate, LastModifyUserID, LastModifyDate) 
	VALUES ('ProductionPlan', N'Kế hoạch sản xuất', 'ProductionPlan', 'Data', N'A', 10, N'C:\IMPORTS', N'Import_Excel_KeHoachSanXuat', 0,
	'ASOFTADMIN', GETDATE(), 'ASOFTADMIN', GETDATE())
END

DELETE FROM A00065 WHERE ImportTransTypeID = N'ProductionPlan'

INSERT INTO A00065(ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ScreenID, TemplateFileName, ExecSQL, OrderNum, ColID, ColName, ColNameEng, 
InputMask, ColWidth, ColLength, ColType, ColSQLDataType, CheckExpression, IsObligated, DataCol)
VALUES (N'ProductionPlan', N'Kế hoạch sản xuất', N'ProductionPlan', N'MF2140', N'Import_Excel_KeHoachSanXuat', N'EXEC MP21410 @DivisionID = @DivisionID, @UserID = @UserID, @ImportTemplateID = @ImportTemplateID, @ImportTransTypeID = @ImportTransTypeID, @XML = @XML', 1
, N'DivisionID', N'Đơn vị', N'DivisionID', N'', 80, 50, 0, N'varchar(50)', N'', 1, N'B3')

INSERT INTO A00065(ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ScreenID, TemplateFileName, ExecSQL, OrderNum, ColID, ColName, ColNameEng, 
InputMask, ColWidth, ColLength, ColType, ColSQLDataType, CheckExpression, IsObligated, DataCol)
VALUES (N'ProductionPlan', N'Kế hoạch sản xuất', N'ProductionPlan', N'MF2140', N'Import_Excel_KeHoachSanXuat', N'EXEC MP21410 @DivisionID = @DivisionID, @UserID = @UserID, @ImportTemplateID = @ImportTemplateID, @ImportTransTypeID = @ImportTransTypeID, @XML = @XML', 2
, N'Period', N'Kỳ kế toán', N'Period', N'', 80, 50, 0, N'varchar(50)', N'', 0, N'B4')

INSERT INTO A00065(ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ScreenID, TemplateFileName, ExecSQL, OrderNum, ColID, ColName, ColNameEng, 
InputMask, ColWidth, ColLength, ColType, ColSQLDataType, CheckExpression, IsObligated, DataCol)
VALUES (N'ProductionPlan', N'Kế hoạch sản xuất', N'ProductionPlan', N'MF2140', N'Import_Excel_KeHoachSanXuat', N'EXEC MP21410 @DivisionID = @DivisionID, @UserID = @UserID, @ImportTemplateID = @ImportTemplateID, @ImportTransTypeID = @ImportTransTypeID, @XML = @XML', 3
, N'VoucherTypeID', N'Loại chứng từ', N'VoucherTypeID', N'', 80, 50, 0, N'varchar(50)', N'', 0, N'B5')

--Data Master
INSERT INTO A00065(ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ScreenID, TemplateFileName, ExecSQL, OrderNum, ColID, ColName, ColNameEng, 
InputMask, ColWidth, ColLength, ColType, ColSQLDataType, CheckExpression, IsObligated, DataCol)
VALUES (N'ProductionPlan', N'Kế hoạch sản xuất', N'ProductionPlan', N'MF2140', N'Import_Excel_KeHoachSanXuat', N'EXEC MP21410 @DivisionID = @DivisionID, @UserID = @UserID, @ImportTemplateID = @ImportTemplateID, @ImportTransTypeID = @ImportTransTypeID, @XML = @XML', 4
, N'VoucherNo', N'Số đơn hàng', N'VoucherNo', N'', 80, 50, 0, N'varchar(50)', N'', 1, N'A')

INSERT INTO A00065(ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ScreenID, TemplateFileName, ExecSQL, OrderNum, ColID, ColName, ColNameEng, 
InputMask, ColWidth, ColLength, ColType, ColSQLDataType, CheckExpression, IsObligated, DataCol)
VALUES (N'ProductionPlan', N'Kế hoạch sản xuất', N'ProductionPlan', N'MF2140', N'Import_Excel_KeHoachSanXuat', N'EXEC MP21410 @DivisionID = @DivisionID, @UserID = @UserID, @ImportTemplateID = @ImportTemplateID, @ImportTransTypeID = @ImportTransTypeID, @XML = @XML', 5
, N'VoucherDate', N'Ngày đơn hàng', N'VoucherDate', N'', 80, 50, 2, N'DATETIME', N'', 1, N'B')

INSERT INTO A00065(ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ScreenID, TemplateFileName, ExecSQL, OrderNum, ColID, ColName, ColNameEng, 
InputMask, ColWidth, ColLength, ColType, ColSQLDataType, CheckExpression, IsObligated, DataCol)
VALUES (N'ProductionPlan', N'Kế hoạch sản xuất', N'ProductionPlan', N'MF2140', N'Import_Excel_KeHoachSanXuat', N'EXEC MP21410 @DivisionID = @DivisionID, @UserID = @UserID, @ImportTemplateID = @ImportTemplateID, @ImportTransTypeID = @ImportTransTypeID, @XML = @XML', 6
, N'Description', N'Diễn gải', N'Description', N'', 150, 250, 0, N'nvarchar(MAX)', N'', 0, N'C')

--Detail thông tin sản xuất
INSERT INTO A00065(ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ScreenID, TemplateFileName, ExecSQL, OrderNum, ColID, ColName, ColNameEng, 
InputMask, ColWidth, ColLength, ColType, ColSQLDataType, CheckExpression, IsObligated, DataCol)
VALUES (N'ProductionPlan', N'Kế hoạch sản xuất', N'ProductionPlan', N'MF2140', N'Import_Excel_KeHoachSanXuat', N'EXEC MP21410 @DivisionID = @DivisionID, @UserID = @UserID, @ImportTemplateID = @ImportTemplateID, @ImportTransTypeID = @ImportTransTypeID, @XML = @XML', 7
, N'VoucherNoProduct', N'Phiếu dụ trù', N'VoucherNoProduct', N'', 80, 50, 0, N'varchar(50)', N'', 1, N'D')

INSERT INTO A00065(ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ScreenID, TemplateFileName, ExecSQL, OrderNum, ColID, ColName, ColNameEng, 
InputMask, ColWidth, ColLength, ColType, ColSQLDataType, CheckExpression, IsObligated, DataCol)
VALUES (N'ProductionPlan', N'Kế hoạch sản xuất', N'ProductionPlan', N'MF2140', N'Import_Excel_KeHoachSanXuat', N'EXEC MP21410 @DivisionID = @DivisionID, @UserID = @UserID, @ImportTemplateID = @ImportTemplateID, @ImportTransTypeID = @ImportTransTypeID, @XML = @XML', 8
, N'InventoryID', N'Mã sản phẩm', N'InventoryID', N'', 80, 50, 0, N'varchar(25)', N'', 1, N'E')

INSERT INTO A00065(ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ScreenID, TemplateFileName, ExecSQL, OrderNum, ColID, ColName, ColNameEng, 
InputMask, ColWidth, ColLength, ColType, ColSQLDataType, CheckExpression, IsObligated, DataCol)
VALUES (N'ProductionPlan', N'Kế hoạch sản xuất', N'ProductionPlan', N'MF2140', N'Import_Excel_KeHoachSanXuat', N'EXEC MP21410 @DivisionID = @DivisionID, @UserID = @UserID, @ImportTemplateID = @ImportTemplateID, @ImportTransTypeID = @ImportTransTypeID, @XML = @XML', 9
, N'DateDelivery', N'Ngày giao hàng', N'DateDelivery', N'', 80, 50, 2, N'DATETIME', N'', 1, N'F')

INSERT INTO A00065(ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ScreenID, TemplateFileName, ExecSQL, OrderNum, ColID, ColName, ColNameEng, 
InputMask, ColWidth, ColLength, ColType, ColSQLDataType, CheckExpression, IsObligated, DataCol)
VALUES (N'ProductionPlan', N'Kế hoạch sản xuất', N'ProductionPlan', N'MF2140', N'Import_Excel_KeHoachSanXuat', N'EXEC MP21410 @DivisionID = @DivisionID, @UserID = @UserID, @ImportTemplateID = @ImportTemplateID, @ImportTransTypeID = @ImportTransTypeID, @XML = @XML', 10
, N'StartDate', N'Ngày bắt đầu sản xuất', N'StartDate', N'', 80, 50, 2, N'DATETIME', N'', 1, N'G')

INSERT INTO A00065(ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ScreenID, TemplateFileName, ExecSQL, OrderNum, ColID, ColName, ColNameEng, 
InputMask, ColWidth, ColLength, ColType, ColSQLDataType, CheckExpression, IsObligated, DataCol)
VALUES (N'ProductionPlan', N'Kế hoạch sản xuất', N'ProductionPlan', N'MF2140', N'Import_Excel_KeHoachSanXuat', N'EXEC MP21410 @DivisionID = @DivisionID, @UserID = @UserID, @ImportTemplateID = @ImportTemplateID, @ImportTransTypeID = @ImportTransTypeID, @XML = @XML', 11
, N'EndDate', N'Ngày sản xuất hoàn thành', N'EndDate', N'', 80, 50, 2, N'DATETIME', N'', 1, N'H')

INSERT INTO A00065(ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ScreenID, TemplateFileName, ExecSQL, OrderNum, ColID, ColName, ColNameEng, 
InputMask, ColWidth, ColLength, ColType, ColSQLDataType, CheckExpression, IsObligated, DataCol)
VALUES (N'ProductionPlan', N'Kế hoạch sản xuất', N'ProductionPlan', N'MF2140', N'Import_Excel_KeHoachSanXuat', N'EXEC MP21410 @DivisionID = @DivisionID, @UserID = @UserID, @ImportTemplateID = @ImportTemplateID, @ImportTransTypeID = @ImportTransTypeID, @XML = @XML', 12
, N'StatusID', N'Tình trạng', N'StatusID', N'', 80, 50, 1, N'INT', N'', 1, N'I')

INSERT INTO A00065(ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ScreenID, TemplateFileName, ExecSQL, OrderNum, ColID, ColName, ColNameEng, 
InputMask, ColWidth, ColLength, ColType, ColSQLDataType, CheckExpression, IsObligated, DataCol)
VALUES (N'ProductionPlan', N'Kế hoạch sản xuất', N'ProductionPlan', N'MF2140', N'Import_Excel_KeHoachSanXuat', N'EXEC MP21410 @DivisionID = @DivisionID, @UserID = @UserID, @ImportTemplateID = @ImportTemplateID, @ImportTransTypeID = @ImportTransTypeID, @XML = @XML', 13
, N'nvarchar01', N'Số PO', N'nvarchar01', N'', 80, 50, 0, N'VARCHAR(25)', N'', 0, N'J')

--Detail thông tin máy
INSERT INTO A00065(ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ScreenID, TemplateFileName, ExecSQL, OrderNum, ColID, ColName, ColNameEng, 
InputMask, ColWidth, ColLength, ColType, ColSQLDataType, CheckExpression, IsObligated, DataCol)
VALUES (N'ProductionPlan', N'Kế hoạch sản xuất', N'ProductionPlan', N'MF2140', N'Import_Excel_KeHoachSanXuat', N'EXEC MP21410 @DivisionID = @DivisionID, @UserID = @UserID, @ImportTemplateID = @ImportTemplateID, @ImportTransTypeID = @ImportTransTypeID, @XML = @XML', 14
, N'PhaseID', N'Mã công đoạn', N'PhaseID', N'', 80, 50, 0, N'varchar(50)', N'', 1, N'K')

INSERT INTO A00065(ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ScreenID, TemplateFileName, ExecSQL, OrderNum, ColID, ColName, ColNameEng, 
InputMask, ColWidth, ColLength, ColType, ColSQLDataType, CheckExpression, IsObligated, DataCol)
VALUES (N'ProductionPlan', N'Kế hoạch sản xuất', N'ProductionPlan', N'MF2140', N'Import_Excel_KeHoachSanXuat', N'EXEC MP21410 @DivisionID = @DivisionID, @UserID = @UserID, @ImportTemplateID = @ImportTemplateID, @ImportTransTypeID = @ImportTransTypeID, @XML = @XML', 15
, N'MaterialID', N'Mã sản phẩm', N'MaterialID', N'', 150, 250, 0, N'varchar(50)', N'', 1, N'L')

INSERT INTO A00065(ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ScreenID, TemplateFileName, ExecSQL, OrderNum, ColID, ColName, ColNameEng, 
InputMask, ColWidth, ColLength, ColType, ColSQLDataType, CheckExpression, IsObligated, DataCol)
VALUES (N'ProductionPlan', N'Kế hoạch sản xuất', N'ProductionPlan', N'MF2140', N'Import_Excel_KeHoachSanXuat', N'EXEC MP21410 @DivisionID = @DivisionID, @UserID = @UserID, @ImportTemplateID = @ImportTemplateID, @ImportTransTypeID = @ImportTransTypeID, @XML = @XML', 16
, N'MachineName', N'Mã máy', N'MachineName', N'', 80, 50, 2, N'DATETIME', N'', 1, N'M')

INSERT INTO A00065(ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ScreenID, TemplateFileName, ExecSQL, OrderNum, ColID, ColName, ColNameEng, 
InputMask, ColWidth, ColLength, ColType, ColSQLDataType, CheckExpression, IsObligated, DataCol)
VALUES (N'ProductionPlan', N'Kế hoạch sản xuất', N'ProductionPlan', N'MF2140', N'Import_Excel_KeHoachSanXuat', N'EXEC MP21410 @DivisionID = @DivisionID, @UserID = @UserID, @ImportTemplateID = @ImportTemplateID, @ImportTransTypeID = @ImportTransTypeID, @XML = @XML', 17
, N'StartDateManufacturing', N'Ngày bắt đầu', N'StartDateManufacturing', N'', 80, 50, 1, N'varchar(50)', N'', 0, N'N')

INSERT INTO A00065(ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ScreenID, TemplateFileName, ExecSQL, OrderNum, ColID, ColName, ColNameEng, 
InputMask, ColWidth, ColLength, ColType, ColSQLDataType, CheckExpression, IsObligated, DataCol)
VALUES (N'ProductionPlan', N'Kế hoạch sản xuất', N'ProductionPlan', N'MF2140', N'Import_Excel_KeHoachSanXuat', N'EXEC MP21410 @DivisionID = @DivisionID, @UserID = @UserID, @ImportTemplateID = @ImportTemplateID, @ImportTransTypeID = @ImportTransTypeID, @XML = @XML', 18
, N'SpaceTimes', N'Khoảng cách ngày', N'SpaceTimes', N'', 80, 50, 1, N'INT', N'', 0, N'O')

INSERT INTO A00065(ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ScreenID, TemplateFileName, ExecSQL, OrderNum, ColID, ColName, ColNameEng, 
InputMask, ColWidth, ColLength, ColType, ColSQLDataType, CheckExpression, IsObligated, DataCol)
VALUES (N'ProductionPlan', N'Kế hoạch sản xuất', N'ProductionPlan', N'MF2140', N'Import_Excel_KeHoachSanXuat', N'EXEC MP21410 @DivisionID = @DivisionID, @UserID = @UserID, @ImportTemplateID = @ImportTemplateID, @ImportTransTypeID = @ImportTransTypeID, @XML = @XML', 19
, N'LineProduceID', N'Mã chuyền sản xuất', N'LineProduceID', N'', 80, 50, 0, N'varchar(250)', N'', 0, N'P')

INSERT INTO A00065(ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ScreenID, TemplateFileName, ExecSQL, OrderNum, ColID, ColName, ColNameEng, 
InputMask, ColWidth, ColLength, ColType, ColSQLDataType, CheckExpression, IsObligated, DataCol)
VALUES (N'ProductionPlan', N'Kế hoạch sản xuất', N'ProductionPlan', N'MF2140', N'Import_Excel_KeHoachSanXuat', N'EXEC MP21410 @DivisionID = @DivisionID, @UserID = @UserID, @ImportTemplateID = @ImportTemplateID, @ImportTransTypeID = @ImportTransTypeID, @XML = @XML', 20
, N'TotalQuantity', N'Tổng số lượng', N'TotalQuantity', N'', 150, 250, 1, N'DECIMAL(28,8)', N'', 0, N'Q')

--Detail ngày sản xuất
INSERT INTO A00065(ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ScreenID, TemplateFileName, ExecSQL, OrderNum, ColID, ColName, ColNameEng, InputMask, ColWidth, ColLength, ColType, ColSQLDataType, CheckExpression, IsObligated, DataCol) VALUES (N'ProductionPlan', N'Kế hoạch sản xuất', N'ProductionPlan', N'MF2140', N'Import_Excel_KeHoachSanXuat', N'EXEC MP21410 @DivisionID = @DivisionID, @UserID = @UserID, @ImportTemplateID = @ImportTemplateID, @ImportTransTypeID = @ImportTransTypeID, @XML = @XML', 21, N'Quantity01', N'Ngày sản xuất 01', N'Quantity01', N'', 80, 50, 2, N'DATETIME', N'', 0, N'R')
INSERT INTO A00065(ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ScreenID, TemplateFileName, ExecSQL, OrderNum, ColID, ColName, ColNameEng, InputMask, ColWidth, ColLength, ColType, ColSQLDataType, CheckExpression, IsObligated, DataCol) VALUES (N'ProductionPlan', N'Kế hoạch sản xuất', N'ProductionPlan', N'MF2140', N'Import_Excel_KeHoachSanXuat', N'EXEC MP21410 @DivisionID = @DivisionID, @UserID = @UserID, @ImportTemplateID = @ImportTemplateID, @ImportTransTypeID = @ImportTransTypeID, @XML = @XML', 22, N'Quantity02', N'Ngày sản xuất 02', N'Quantity02', N'', 80, 50, 2, N'DATETIME', N'', 0, N'S')
INSERT INTO A00065(ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ScreenID, TemplateFileName, ExecSQL, OrderNum, ColID, ColName, ColNameEng, InputMask, ColWidth, ColLength, ColType, ColSQLDataType, CheckExpression, IsObligated, DataCol) VALUES (N'ProductionPlan', N'Kế hoạch sản xuất', N'ProductionPlan', N'MF2140', N'Import_Excel_KeHoachSanXuat', N'EXEC MP21410 @DivisionID = @DivisionID, @UserID = @UserID, @ImportTemplateID = @ImportTemplateID, @ImportTransTypeID = @ImportTransTypeID, @XML = @XML', 23, N'Quantity03', N'Ngày sản xuất 03', N'Quantity03', N'', 80, 50, 2, N'DATETIME', N'', 0, N'T')
INSERT INTO A00065(ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ScreenID, TemplateFileName, ExecSQL, OrderNum, ColID, ColName, ColNameEng, InputMask, ColWidth, ColLength, ColType, ColSQLDataType, CheckExpression, IsObligated, DataCol) VALUES (N'ProductionPlan', N'Kế hoạch sản xuất', N'ProductionPlan', N'MF2140', N'Import_Excel_KeHoachSanXuat', N'EXEC MP21410 @DivisionID = @DivisionID, @UserID = @UserID, @ImportTemplateID = @ImportTemplateID, @ImportTransTypeID = @ImportTransTypeID, @XML = @XML', 24, N'Quantity04', N'Ngày sản xuất 04', N'Quantity04', N'', 80, 50, 2, N'DATETIME', N'', 0, N'U')
INSERT INTO A00065(ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ScreenID, TemplateFileName, ExecSQL, OrderNum, ColID, ColName, ColNameEng, InputMask, ColWidth, ColLength, ColType, ColSQLDataType, CheckExpression, IsObligated, DataCol) VALUES (N'ProductionPlan', N'Kế hoạch sản xuất', N'ProductionPlan', N'MF2140', N'Import_Excel_KeHoachSanXuat', N'EXEC MP21410 @DivisionID = @DivisionID, @UserID = @UserID, @ImportTemplateID = @ImportTemplateID, @ImportTransTypeID = @ImportTransTypeID, @XML = @XML', 25, N'Quantity05', N'Ngày sản xuất 05', N'Quantity05', N'', 80, 50, 2, N'DATETIME', N'', 0, N'V')
INSERT INTO A00065(ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ScreenID, TemplateFileName, ExecSQL, OrderNum, ColID, ColName, ColNameEng, InputMask, ColWidth, ColLength, ColType, ColSQLDataType, CheckExpression, IsObligated, DataCol) VALUES (N'ProductionPlan', N'Kế hoạch sản xuất', N'ProductionPlan', N'MF2140', N'Import_Excel_KeHoachSanXuat', N'EXEC MP21410 @DivisionID = @DivisionID, @UserID = @UserID, @ImportTemplateID = @ImportTemplateID, @ImportTransTypeID = @ImportTransTypeID, @XML = @XML', 26, N'Quantity06', N'Ngày sản xuất 06', N'Quantity06', N'', 80, 50, 2, N'DATETIME', N'', 0, N'W')
INSERT INTO A00065(ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ScreenID, TemplateFileName, ExecSQL, OrderNum, ColID, ColName, ColNameEng, InputMask, ColWidth, ColLength, ColType, ColSQLDataType, CheckExpression, IsObligated, DataCol) VALUES (N'ProductionPlan', N'Kế hoạch sản xuất', N'ProductionPlan', N'MF2140', N'Import_Excel_KeHoachSanXuat', N'EXEC MP21410 @DivisionID = @DivisionID, @UserID = @UserID, @ImportTemplateID = @ImportTemplateID, @ImportTransTypeID = @ImportTransTypeID, @XML = @XML', 27, N'Quantity07', N'Ngày sản xuất 07', N'Quantity07', N'', 80, 50, 2, N'DATETIME', N'', 0, N'X')
INSERT INTO A00065(ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ScreenID, TemplateFileName, ExecSQL, OrderNum, ColID, ColName, ColNameEng, InputMask, ColWidth, ColLength, ColType, ColSQLDataType, CheckExpression, IsObligated, DataCol) VALUES (N'ProductionPlan', N'Kế hoạch sản xuất', N'ProductionPlan', N'MF2140', N'Import_Excel_KeHoachSanXuat', N'EXEC MP21410 @DivisionID = @DivisionID, @UserID = @UserID, @ImportTemplateID = @ImportTemplateID, @ImportTransTypeID = @ImportTransTypeID, @XML = @XML', 28, N'Quantity08', N'Ngày sản xuất 08', N'Quantity08', N'', 80, 50, 2, N'DATETIME', N'', 0, N'Y')
INSERT INTO A00065(ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ScreenID, TemplateFileName, ExecSQL, OrderNum, ColID, ColName, ColNameEng, InputMask, ColWidth, ColLength, ColType, ColSQLDataType, CheckExpression, IsObligated, DataCol) VALUES (N'ProductionPlan', N'Kế hoạch sản xuất', N'ProductionPlan', N'MF2140', N'Import_Excel_KeHoachSanXuat', N'EXEC MP21410 @DivisionID = @DivisionID, @UserID = @UserID, @ImportTemplateID = @ImportTemplateID, @ImportTransTypeID = @ImportTransTypeID, @XML = @XML', 29, N'Quantity09', N'Ngày sản xuất 09', N'Quantity09', N'', 80, 50, 2, N'DATETIME', N'', 0, N'Z')
INSERT INTO A00065(ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ScreenID, TemplateFileName, ExecSQL, OrderNum, ColID, ColName, ColNameEng, InputMask, ColWidth, ColLength, ColType, ColSQLDataType, CheckExpression, IsObligated, DataCol) VALUES (N'ProductionPlan', N'Kế hoạch sản xuất', N'ProductionPlan', N'MF2140', N'Import_Excel_KeHoachSanXuat', N'EXEC MP21410 @DivisionID = @DivisionID, @UserID = @UserID, @ImportTemplateID = @ImportTemplateID, @ImportTransTypeID = @ImportTransTypeID, @XML = @XML', 30, N'Quantity10', N'Ngày sản xuất 10', N'Quantity10', N'', 80, 50, 2, N'DATETIME', N'', 0, N'AA')
INSERT INTO A00065(ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ScreenID, TemplateFileName, ExecSQL, OrderNum, ColID, ColName, ColNameEng, InputMask, ColWidth, ColLength, ColType, ColSQLDataType, CheckExpression, IsObligated, DataCol) VALUES (N'ProductionPlan', N'Kế hoạch sản xuất', N'ProductionPlan', N'MF2140', N'Import_Excel_KeHoachSanXuat', N'EXEC MP21410 @DivisionID = @DivisionID, @UserID = @UserID, @ImportTemplateID = @ImportTemplateID, @ImportTransTypeID = @ImportTransTypeID, @XML = @XML', 31, N'Quantity11', N'Ngày sản xuất 11', N'Quantity11', N'', 80, 50, 2, N'DATETIME', N'', 0, N'AB')
INSERT INTO A00065(ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ScreenID, TemplateFileName, ExecSQL, OrderNum, ColID, ColName, ColNameEng, InputMask, ColWidth, ColLength, ColType, ColSQLDataType, CheckExpression, IsObligated, DataCol) VALUES (N'ProductionPlan', N'Kế hoạch sản xuất', N'ProductionPlan', N'MF2140', N'Import_Excel_KeHoachSanXuat', N'EXEC MP21410 @DivisionID = @DivisionID, @UserID = @UserID, @ImportTemplateID = @ImportTemplateID, @ImportTransTypeID = @ImportTransTypeID, @XML = @XML', 32, N'Quantity12', N'Ngày sản xuất 12', N'Quantity12', N'', 80, 50, 2, N'DATETIME', N'', 0, N'AC')
INSERT INTO A00065(ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ScreenID, TemplateFileName, ExecSQL, OrderNum, ColID, ColName, ColNameEng, InputMask, ColWidth, ColLength, ColType, ColSQLDataType, CheckExpression, IsObligated, DataCol) VALUES (N'ProductionPlan', N'Kế hoạch sản xuất', N'ProductionPlan', N'MF2140', N'Import_Excel_KeHoachSanXuat', N'EXEC MP21410 @DivisionID = @DivisionID, @UserID = @UserID, @ImportTemplateID = @ImportTemplateID, @ImportTransTypeID = @ImportTransTypeID, @XML = @XML', 33, N'Quantity13', N'Ngày sản xuất 13', N'Quantity13', N'', 80, 50, 2, N'DATETIME', N'', 0, N'AD')
INSERT INTO A00065(ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ScreenID, TemplateFileName, ExecSQL, OrderNum, ColID, ColName, ColNameEng, InputMask, ColWidth, ColLength, ColType, ColSQLDataType, CheckExpression, IsObligated, DataCol) VALUES (N'ProductionPlan', N'Kế hoạch sản xuất', N'ProductionPlan', N'MF2140', N'Import_Excel_KeHoachSanXuat', N'EXEC MP21410 @DivisionID = @DivisionID, @UserID = @UserID, @ImportTemplateID = @ImportTemplateID, @ImportTransTypeID = @ImportTransTypeID, @XML = @XML', 34, N'Quantity14', N'Ngày sản xuất 14', N'Quantity14', N'', 80, 50, 2, N'DATETIME', N'', 0, N'AE')
INSERT INTO A00065(ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ScreenID, TemplateFileName, ExecSQL, OrderNum, ColID, ColName, ColNameEng, InputMask, ColWidth, ColLength, ColType, ColSQLDataType, CheckExpression, IsObligated, DataCol) VALUES (N'ProductionPlan', N'Kế hoạch sản xuất', N'ProductionPlan', N'MF2140', N'Import_Excel_KeHoachSanXuat', N'EXEC MP21410 @DivisionID = @DivisionID, @UserID = @UserID, @ImportTemplateID = @ImportTemplateID, @ImportTransTypeID = @ImportTransTypeID, @XML = @XML', 35, N'Quantity15', N'Ngày sản xuất 15', N'Quantity15', N'', 80, 50, 2, N'DATETIME', N'', 0, N'AF')
INSERT INTO A00065(ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ScreenID, TemplateFileName, ExecSQL, OrderNum, ColID, ColName, ColNameEng, InputMask, ColWidth, ColLength, ColType, ColSQLDataType, CheckExpression, IsObligated, DataCol) VALUES (N'ProductionPlan', N'Kế hoạch sản xuất', N'ProductionPlan', N'MF2140', N'Import_Excel_KeHoachSanXuat', N'EXEC MP21410 @DivisionID = @DivisionID, @UserID = @UserID, @ImportTemplateID = @ImportTemplateID, @ImportTransTypeID = @ImportTransTypeID, @XML = @XML', 36, N'Quantity16', N'Ngày sản xuất 16', N'Quantity16', N'', 80, 50, 2, N'DATETIME', N'', 0, N'AG')
INSERT INTO A00065(ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ScreenID, TemplateFileName, ExecSQL, OrderNum, ColID, ColName, ColNameEng, InputMask, ColWidth, ColLength, ColType, ColSQLDataType, CheckExpression, IsObligated, DataCol) VALUES (N'ProductionPlan', N'Kế hoạch sản xuất', N'ProductionPlan', N'MF2140', N'Import_Excel_KeHoachSanXuat', N'EXEC MP21410 @DivisionID = @DivisionID, @UserID = @UserID, @ImportTemplateID = @ImportTemplateID, @ImportTransTypeID = @ImportTransTypeID, @XML = @XML', 37, N'Quantity17', N'Ngày sản xuất 17', N'Quantity17', N'', 80, 50, 2, N'DATETIME', N'', 0, N'AH')
INSERT INTO A00065(ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ScreenID, TemplateFileName, ExecSQL, OrderNum, ColID, ColName, ColNameEng, InputMask, ColWidth, ColLength, ColType, ColSQLDataType, CheckExpression, IsObligated, DataCol) VALUES (N'ProductionPlan', N'Kế hoạch sản xuất', N'ProductionPlan', N'MF2140', N'Import_Excel_KeHoachSanXuat', N'EXEC MP21410 @DivisionID = @DivisionID, @UserID = @UserID, @ImportTemplateID = @ImportTemplateID, @ImportTransTypeID = @ImportTransTypeID, @XML = @XML', 38, N'Quantity18', N'Ngày sản xuất 18', N'Quantity18', N'', 80, 50, 2, N'DATETIME', N'', 0, N'AI')
INSERT INTO A00065(ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ScreenID, TemplateFileName, ExecSQL, OrderNum, ColID, ColName, ColNameEng, InputMask, ColWidth, ColLength, ColType, ColSQLDataType, CheckExpression, IsObligated, DataCol) VALUES (N'ProductionPlan', N'Kế hoạch sản xuất', N'ProductionPlan', N'MF2140', N'Import_Excel_KeHoachSanXuat', N'EXEC MP21410 @DivisionID = @DivisionID, @UserID = @UserID, @ImportTemplateID = @ImportTemplateID, @ImportTransTypeID = @ImportTransTypeID, @XML = @XML', 39, N'Quantity19', N'Ngày sản xuất 19', N'Quantity19', N'', 80, 50, 2, N'DATETIME', N'', 0, N'AJ')
INSERT INTO A00065(ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ScreenID, TemplateFileName, ExecSQL, OrderNum, ColID, ColName, ColNameEng, InputMask, ColWidth, ColLength, ColType, ColSQLDataType, CheckExpression, IsObligated, DataCol) VALUES (N'ProductionPlan', N'Kế hoạch sản xuất', N'ProductionPlan', N'MF2140', N'Import_Excel_KeHoachSanXuat', N'EXEC MP21410 @DivisionID = @DivisionID, @UserID = @UserID, @ImportTemplateID = @ImportTemplateID, @ImportTransTypeID = @ImportTransTypeID, @XML = @XML', 40, N'Quantity20', N'Ngày sản xuất 20', N'Quantity20', N'', 80, 50, 2, N'DATETIME', N'', 0, N'AK')
INSERT INTO A00065(ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ScreenID, TemplateFileName, ExecSQL, OrderNum, ColID, ColName, ColNameEng, InputMask, ColWidth, ColLength, ColType, ColSQLDataType, CheckExpression, IsObligated, DataCol) VALUES (N'ProductionPlan', N'Kế hoạch sản xuất', N'ProductionPlan', N'MF2140', N'Import_Excel_KeHoachSanXuat', N'EXEC MP21410 @DivisionID = @DivisionID, @UserID = @UserID, @ImportTemplateID = @ImportTemplateID, @ImportTransTypeID = @ImportTransTypeID, @XML = @XML', 41, N'Quantity21', N'Ngày sản xuất 21', N'Quantity21', N'', 80, 50, 2, N'DATETIME', N'', 0, N'AL')
INSERT INTO A00065(ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ScreenID, TemplateFileName, ExecSQL, OrderNum, ColID, ColName, ColNameEng, InputMask, ColWidth, ColLength, ColType, ColSQLDataType, CheckExpression, IsObligated, DataCol) VALUES (N'ProductionPlan', N'Kế hoạch sản xuất', N'ProductionPlan', N'MF2140', N'Import_Excel_KeHoachSanXuat', N'EXEC MP21410 @DivisionID = @DivisionID, @UserID = @UserID, @ImportTemplateID = @ImportTemplateID, @ImportTransTypeID = @ImportTransTypeID, @XML = @XML', 42, N'Quantity22', N'Ngày sản xuất 22', N'Quantity22', N'', 80, 50, 2, N'DATETIME', N'', 0, N'AM')
INSERT INTO A00065(ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ScreenID, TemplateFileName, ExecSQL, OrderNum, ColID, ColName, ColNameEng, InputMask, ColWidth, ColLength, ColType, ColSQLDataType, CheckExpression, IsObligated, DataCol) VALUES (N'ProductionPlan', N'Kế hoạch sản xuất', N'ProductionPlan', N'MF2140', N'Import_Excel_KeHoachSanXuat', N'EXEC MP21410 @DivisionID = @DivisionID, @UserID = @UserID, @ImportTemplateID = @ImportTemplateID, @ImportTransTypeID = @ImportTransTypeID, @XML = @XML', 43, N'Quantity23', N'Ngày sản xuất 23', N'Quantity23', N'', 80, 50, 2, N'DATETIME', N'', 0, N'AN')
INSERT INTO A00065(ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ScreenID, TemplateFileName, ExecSQL, OrderNum, ColID, ColName, ColNameEng, InputMask, ColWidth, ColLength, ColType, ColSQLDataType, CheckExpression, IsObligated, DataCol) VALUES (N'ProductionPlan', N'Kế hoạch sản xuất', N'ProductionPlan', N'MF2140', N'Import_Excel_KeHoachSanXuat', N'EXEC MP21410 @DivisionID = @DivisionID, @UserID = @UserID, @ImportTemplateID = @ImportTemplateID, @ImportTransTypeID = @ImportTransTypeID, @XML = @XML', 44, N'Quantity24', N'Ngày sản xuất 24', N'Quantity24', N'', 80, 50, 2, N'DATETIME', N'', 0, N'AO')
INSERT INTO A00065(ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ScreenID, TemplateFileName, ExecSQL, OrderNum, ColID, ColName, ColNameEng, InputMask, ColWidth, ColLength, ColType, ColSQLDataType, CheckExpression, IsObligated, DataCol) VALUES (N'ProductionPlan', N'Kế hoạch sản xuất', N'ProductionPlan', N'MF2140', N'Import_Excel_KeHoachSanXuat', N'EXEC MP21410 @DivisionID = @DivisionID, @UserID = @UserID, @ImportTemplateID = @ImportTemplateID, @ImportTransTypeID = @ImportTransTypeID, @XML = @XML', 45, N'Quantity25', N'Ngày sản xuất 25', N'Quantity25', N'', 80, 50, 2, N'DATETIME', N'', 0, N'AP')
INSERT INTO A00065(ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ScreenID, TemplateFileName, ExecSQL, OrderNum, ColID, ColName, ColNameEng, InputMask, ColWidth, ColLength, ColType, ColSQLDataType, CheckExpression, IsObligated, DataCol) VALUES (N'ProductionPlan', N'Kế hoạch sản xuất', N'ProductionPlan', N'MF2140', N'Import_Excel_KeHoachSanXuat', N'EXEC MP21410 @DivisionID = @DivisionID, @UserID = @UserID, @ImportTemplateID = @ImportTemplateID, @ImportTransTypeID = @ImportTransTypeID, @XML = @XML', 46, N'Quantity26', N'Ngày sản xuất 26', N'Quantity26', N'', 80, 50, 2, N'DATETIME', N'', 0, N'AQ')
INSERT INTO A00065(ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ScreenID, TemplateFileName, ExecSQL, OrderNum, ColID, ColName, ColNameEng, InputMask, ColWidth, ColLength, ColType, ColSQLDataType, CheckExpression, IsObligated, DataCol) VALUES (N'ProductionPlan', N'Kế hoạch sản xuất', N'ProductionPlan', N'MF2140', N'Import_Excel_KeHoachSanXuat', N'EXEC MP21410 @DivisionID = @DivisionID, @UserID = @UserID, @ImportTemplateID = @ImportTemplateID, @ImportTransTypeID = @ImportTransTypeID, @XML = @XML', 47, N'Quantity27', N'Ngày sản xuất 27', N'Quantity27', N'', 80, 50, 2, N'DATETIME', N'', 0, N'AR')
INSERT INTO A00065(ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ScreenID, TemplateFileName, ExecSQL, OrderNum, ColID, ColName, ColNameEng, InputMask, ColWidth, ColLength, ColType, ColSQLDataType, CheckExpression, IsObligated, DataCol) VALUES (N'ProductionPlan', N'Kế hoạch sản xuất', N'ProductionPlan', N'MF2140', N'Import_Excel_KeHoachSanXuat', N'EXEC MP21410 @DivisionID = @DivisionID, @UserID = @UserID, @ImportTemplateID = @ImportTemplateID, @ImportTransTypeID = @ImportTransTypeID, @XML = @XML', 48, N'Quantity28', N'Ngày sản xuất 28', N'Quantity28', N'', 80, 50, 2, N'DATETIME', N'', 0, N'AS')
INSERT INTO A00065(ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ScreenID, TemplateFileName, ExecSQL, OrderNum, ColID, ColName, ColNameEng, InputMask, ColWidth, ColLength, ColType, ColSQLDataType, CheckExpression, IsObligated, DataCol) VALUES (N'ProductionPlan', N'Kế hoạch sản xuất', N'ProductionPlan', N'MF2140', N'Import_Excel_KeHoachSanXuat', N'EXEC MP21410 @DivisionID = @DivisionID, @UserID = @UserID, @ImportTemplateID = @ImportTemplateID, @ImportTransTypeID = @ImportTransTypeID, @XML = @XML', 49, N'Quantity29', N'Ngày sản xuất 29', N'Quantity29', N'', 80, 50, 2, N'DATETIME', N'', 0, N'AT')
INSERT INTO A00065(ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ScreenID, TemplateFileName, ExecSQL, OrderNum, ColID, ColName, ColNameEng, InputMask, ColWidth, ColLength, ColType, ColSQLDataType, CheckExpression, IsObligated, DataCol) VALUES (N'ProductionPlan', N'Kế hoạch sản xuất', N'ProductionPlan', N'MF2140', N'Import_Excel_KeHoachSanXuat', N'EXEC MP21410 @DivisionID = @DivisionID, @UserID = @UserID, @ImportTemplateID = @ImportTemplateID, @ImportTransTypeID = @ImportTransTypeID, @XML = @XML', 50, N'Quantity30', N'Ngày sản xuất 30', N'Quantity30', N'', 80, 50, 2, N'DATETIME', N'', 0, N'AU')
INSERT INTO A00065(ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ScreenID, TemplateFileName, ExecSQL, OrderNum, ColID, ColName, ColNameEng, InputMask, ColWidth, ColLength, ColType, ColSQLDataType, CheckExpression, IsObligated, DataCol) VALUES (N'ProductionPlan', N'Kế hoạch sản xuất', N'ProductionPlan', N'MF2140', N'Import_Excel_KeHoachSanXuat', N'EXEC MP21410 @DivisionID = @DivisionID, @UserID = @UserID, @ImportTemplateID = @ImportTemplateID, @ImportTransTypeID = @ImportTransTypeID, @XML = @XML', 51, N'Quantity31', N'Ngày sản xuất 31', N'Quantity31', N'', 80, 50, 2, N'DATETIME', N'', 0, N'AV')
INSERT INTO A00065(ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ScreenID, TemplateFileName, ExecSQL, OrderNum, ColID, ColName, ColNameEng, InputMask, ColWidth, ColLength, ColType, ColSQLDataType, CheckExpression, IsObligated, DataCol) VALUES (N'ProductionPlan', N'Kế hoạch sản xuất', N'ProductionPlan', N'MF2140', N'Import_Excel_KeHoachSanXuat', N'EXEC MP21410 @DivisionID = @DivisionID, @UserID = @UserID, @ImportTemplateID = @ImportTemplateID, @ImportTransTypeID = @ImportTransTypeID, @XML = @XML', 52, N'Quantity32', N'Ngày sản xuất 32', N'Quantity32', N'', 80, 50, 2, N'DATETIME', N'', 0, N'AW')
INSERT INTO A00065(ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ScreenID, TemplateFileName, ExecSQL, OrderNum, ColID, ColName, ColNameEng, InputMask, ColWidth, ColLength, ColType, ColSQLDataType, CheckExpression, IsObligated, DataCol) VALUES (N'ProductionPlan', N'Kế hoạch sản xuất', N'ProductionPlan', N'MF2140', N'Import_Excel_KeHoachSanXuat', N'EXEC MP21410 @DivisionID = @DivisionID, @UserID = @UserID, @ImportTemplateID = @ImportTemplateID, @ImportTransTypeID = @ImportTransTypeID, @XML = @XML', 53, N'Quantity33', N'Ngày sản xuất 33', N'Quantity33', N'', 80, 50, 2, N'DATETIME', N'', 0, N'AX')
INSERT INTO A00065(ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ScreenID, TemplateFileName, ExecSQL, OrderNum, ColID, ColName, ColNameEng, InputMask, ColWidth, ColLength, ColType, ColSQLDataType, CheckExpression, IsObligated, DataCol) VALUES (N'ProductionPlan', N'Kế hoạch sản xuất', N'ProductionPlan', N'MF2140', N'Import_Excel_KeHoachSanXuat', N'EXEC MP21410 @DivisionID = @DivisionID, @UserID = @UserID, @ImportTemplateID = @ImportTemplateID, @ImportTransTypeID = @ImportTransTypeID, @XML = @XML', 54, N'Quantity34', N'Ngày sản xuất 34', N'Quantity34', N'', 80, 50, 2, N'DATETIME', N'', 0, N'AY')
INSERT INTO A00065(ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ScreenID, TemplateFileName, ExecSQL, OrderNum, ColID, ColName, ColNameEng, InputMask, ColWidth, ColLength, ColType, ColSQLDataType, CheckExpression, IsObligated, DataCol) VALUES (N'ProductionPlan', N'Kế hoạch sản xuất', N'ProductionPlan', N'MF2140', N'Import_Excel_KeHoachSanXuat', N'EXEC MP21410 @DivisionID = @DivisionID, @UserID = @UserID, @ImportTemplateID = @ImportTemplateID, @ImportTransTypeID = @ImportTransTypeID, @XML = @XML', 55, N'Quantity35', N'Ngày sản xuất 35', N'Quantity35', N'', 80, 50, 2, N'DATETIME', N'', 0, N'AZ')
INSERT INTO A00065(ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ScreenID, TemplateFileName, ExecSQL, OrderNum, ColID, ColName, ColNameEng, InputMask, ColWidth, ColLength, ColType, ColSQLDataType, CheckExpression, IsObligated, DataCol) VALUES (N'ProductionPlan', N'Kế hoạch sản xuất', N'ProductionPlan', N'MF2140', N'Import_Excel_KeHoachSanXuat', N'EXEC MP21410 @DivisionID = @DivisionID, @UserID = @UserID, @ImportTemplateID = @ImportTemplateID, @ImportTransTypeID = @ImportTransTypeID, @XML = @XML', 56, N'Quantity36', N'Ngày sản xuất 36', N'Quantity36', N'', 80, 50, 2, N'DATETIME', N'', 0, N'BA')
INSERT INTO A00065(ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ScreenID, TemplateFileName, ExecSQL, OrderNum, ColID, ColName, ColNameEng, InputMask, ColWidth, ColLength, ColType, ColSQLDataType, CheckExpression, IsObligated, DataCol) VALUES (N'ProductionPlan', N'Kế hoạch sản xuất', N'ProductionPlan', N'MF2140', N'Import_Excel_KeHoachSanXuat', N'EXEC MP21410 @DivisionID = @DivisionID, @UserID = @UserID, @ImportTemplateID = @ImportTemplateID, @ImportTransTypeID = @ImportTransTypeID, @XML = @XML', 57, N'Quantity37', N'Ngày sản xuất 37', N'Quantity37', N'', 80, 50, 2, N'DATETIME', N'', 0, N'BB')
INSERT INTO A00065(ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ScreenID, TemplateFileName, ExecSQL, OrderNum, ColID, ColName, ColNameEng, InputMask, ColWidth, ColLength, ColType, ColSQLDataType, CheckExpression, IsObligated, DataCol) VALUES (N'ProductionPlan', N'Kế hoạch sản xuất', N'ProductionPlan', N'MF2140', N'Import_Excel_KeHoachSanXuat', N'EXEC MP21410 @DivisionID = @DivisionID, @UserID = @UserID, @ImportTemplateID = @ImportTemplateID, @ImportTransTypeID = @ImportTransTypeID, @XML = @XML', 58, N'Quantity38', N'Ngày sản xuất 38', N'Quantity38', N'', 80, 50, 2, N'DATETIME', N'', 0, N'BC')
INSERT INTO A00065(ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ScreenID, TemplateFileName, ExecSQL, OrderNum, ColID, ColName, ColNameEng, InputMask, ColWidth, ColLength, ColType, ColSQLDataType, CheckExpression, IsObligated, DataCol) VALUES (N'ProductionPlan', N'Kế hoạch sản xuất', N'ProductionPlan', N'MF2140', N'Import_Excel_KeHoachSanXuat', N'EXEC MP21410 @DivisionID = @DivisionID, @UserID = @UserID, @ImportTemplateID = @ImportTemplateID, @ImportTransTypeID = @ImportTransTypeID, @XML = @XML', 59, N'Quantity39', N'Ngày sản xuất 39', N'Quantity39', N'', 80, 50, 2, N'DATETIME', N'', 0, N'BD')
INSERT INTO A00065(ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ScreenID, TemplateFileName, ExecSQL, OrderNum, ColID, ColName, ColNameEng, InputMask, ColWidth, ColLength, ColType, ColSQLDataType, CheckExpression, IsObligated, DataCol) VALUES (N'ProductionPlan', N'Kế hoạch sản xuất', N'ProductionPlan', N'MF2140', N'Import_Excel_KeHoachSanXuat', N'EXEC MP21410 @DivisionID = @DivisionID, @UserID = @UserID, @ImportTemplateID = @ImportTemplateID, @ImportTransTypeID = @ImportTransTypeID, @XML = @XML', 60, N'Quantity40', N'Ngày sản xuất 40', N'Quantity40', N'', 80, 50, 2, N'DATETIME', N'', 0, N'BE')
INSERT INTO A00065(ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ScreenID, TemplateFileName, ExecSQL, OrderNum, ColID, ColName, ColNameEng, InputMask, ColWidth, ColLength, ColType, ColSQLDataType, CheckExpression, IsObligated, DataCol) VALUES (N'ProductionPlan', N'Kế hoạch sản xuất', N'ProductionPlan', N'MF2140', N'Import_Excel_KeHoachSanXuat', N'EXEC MP21410 @DivisionID = @DivisionID, @UserID = @UserID, @ImportTemplateID = @ImportTemplateID, @ImportTransTypeID = @ImportTransTypeID, @XML = @XML', 61, N'Quantity41', N'Ngày sản xuất 41', N'Quantity41', N'', 80, 50, 2, N'DATETIME', N'', 0, N'BF')
INSERT INTO A00065(ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ScreenID, TemplateFileName, ExecSQL, OrderNum, ColID, ColName, ColNameEng, InputMask, ColWidth, ColLength, ColType, ColSQLDataType, CheckExpression, IsObligated, DataCol) VALUES (N'ProductionPlan', N'Kế hoạch sản xuất', N'ProductionPlan', N'MF2140', N'Import_Excel_KeHoachSanXuat', N'EXEC MP21410 @DivisionID = @DivisionID, @UserID = @UserID, @ImportTemplateID = @ImportTemplateID, @ImportTransTypeID = @ImportTransTypeID, @XML = @XML', 62, N'Quantity42', N'Ngày sản xuất 42', N'Quantity42', N'', 80, 50, 2, N'DATETIME', N'', 0, N'BG')
INSERT INTO A00065(ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ScreenID, TemplateFileName, ExecSQL, OrderNum, ColID, ColName, ColNameEng, InputMask, ColWidth, ColLength, ColType, ColSQLDataType, CheckExpression, IsObligated, DataCol) VALUES (N'ProductionPlan', N'Kế hoạch sản xuất', N'ProductionPlan', N'MF2140', N'Import_Excel_KeHoachSanXuat', N'EXEC MP21410 @DivisionID = @DivisionID, @UserID = @UserID, @ImportTemplateID = @ImportTemplateID, @ImportTransTypeID = @ImportTransTypeID, @XML = @XML', 63, N'Quantity43', N'Ngày sản xuất 43', N'Quantity43', N'', 80, 50, 2, N'DATETIME', N'', 0, N'BH')
INSERT INTO A00065(ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ScreenID, TemplateFileName, ExecSQL, OrderNum, ColID, ColName, ColNameEng, InputMask, ColWidth, ColLength, ColType, ColSQLDataType, CheckExpression, IsObligated, DataCol) VALUES (N'ProductionPlan', N'Kế hoạch sản xuất', N'ProductionPlan', N'MF2140', N'Import_Excel_KeHoachSanXuat', N'EXEC MP21410 @DivisionID = @DivisionID, @UserID = @UserID, @ImportTemplateID = @ImportTemplateID, @ImportTransTypeID = @ImportTransTypeID, @XML = @XML', 64, N'Quantity44', N'Ngày sản xuất 44', N'Quantity44', N'', 80, 50, 2, N'DATETIME', N'', 0, N'BI')
INSERT INTO A00065(ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ScreenID, TemplateFileName, ExecSQL, OrderNum, ColID, ColName, ColNameEng, InputMask, ColWidth, ColLength, ColType, ColSQLDataType, CheckExpression, IsObligated, DataCol) VALUES (N'ProductionPlan', N'Kế hoạch sản xuất', N'ProductionPlan', N'MF2140', N'Import_Excel_KeHoachSanXuat', N'EXEC MP21410 @DivisionID = @DivisionID, @UserID = @UserID, @ImportTemplateID = @ImportTemplateID, @ImportTransTypeID = @ImportTransTypeID, @XML = @XML', 65, N'Quantity45', N'Ngày sản xuất 45', N'Quantity45', N'', 80, 50, 2, N'DATETIME', N'', 0, N'BJ')
INSERT INTO A00065(ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ScreenID, TemplateFileName, ExecSQL, OrderNum, ColID, ColName, ColNameEng, InputMask, ColWidth, ColLength, ColType, ColSQLDataType, CheckExpression, IsObligated, DataCol) VALUES (N'ProductionPlan', N'Kế hoạch sản xuất', N'ProductionPlan', N'MF2140', N'Import_Excel_KeHoachSanXuat', N'EXEC MP21410 @DivisionID = @DivisionID, @UserID = @UserID, @ImportTemplateID = @ImportTemplateID, @ImportTransTypeID = @ImportTransTypeID, @XML = @XML', 66, N'Quantity46', N'Ngày sản xuất 46', N'Quantity46', N'', 80, 50, 2, N'DATETIME', N'', 0, N'BK')
INSERT INTO A00065(ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ScreenID, TemplateFileName, ExecSQL, OrderNum, ColID, ColName, ColNameEng, InputMask, ColWidth, ColLength, ColType, ColSQLDataType, CheckExpression, IsObligated, DataCol) VALUES (N'ProductionPlan', N'Kế hoạch sản xuất', N'ProductionPlan', N'MF2140', N'Import_Excel_KeHoachSanXuat', N'EXEC MP21410 @DivisionID = @DivisionID, @UserID = @UserID, @ImportTemplateID = @ImportTemplateID, @ImportTransTypeID = @ImportTransTypeID, @XML = @XML', 67, N'Quantity47', N'Ngày sản xuất 47', N'Quantity47', N'', 80, 50, 2, N'DATETIME', N'', 0, N'BL')
INSERT INTO A00065(ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ScreenID, TemplateFileName, ExecSQL, OrderNum, ColID, ColName, ColNameEng, InputMask, ColWidth, ColLength, ColType, ColSQLDataType, CheckExpression, IsObligated, DataCol) VALUES (N'ProductionPlan', N'Kế hoạch sản xuất', N'ProductionPlan', N'MF2140', N'Import_Excel_KeHoachSanXuat', N'EXEC MP21410 @DivisionID = @DivisionID, @UserID = @UserID, @ImportTemplateID = @ImportTemplateID, @ImportTransTypeID = @ImportTransTypeID, @XML = @XML', 68, N'Quantity48', N'Ngày sản xuất 48', N'Quantity48', N'', 80, 50, 2, N'DATETIME', N'', 0, N'BM')
INSERT INTO A00065(ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ScreenID, TemplateFileName, ExecSQL, OrderNum, ColID, ColName, ColNameEng, InputMask, ColWidth, ColLength, ColType, ColSQLDataType, CheckExpression, IsObligated, DataCol) VALUES (N'ProductionPlan', N'Kế hoạch sản xuất', N'ProductionPlan', N'MF2140', N'Import_Excel_KeHoachSanXuat', N'EXEC MP21410 @DivisionID = @DivisionID, @UserID = @UserID, @ImportTemplateID = @ImportTemplateID, @ImportTransTypeID = @ImportTransTypeID, @XML = @XML', 69, N'Quantity49', N'Ngày sản xuất 49', N'Quantity49', N'', 80, 50, 2, N'DATETIME', N'', 0, N'BN')
INSERT INTO A00065(ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ScreenID, TemplateFileName, ExecSQL, OrderNum, ColID, ColName, ColNameEng, InputMask, ColWidth, ColLength, ColType, ColSQLDataType, CheckExpression, IsObligated, DataCol) VALUES (N'ProductionPlan', N'Kế hoạch sản xuất', N'ProductionPlan', N'MF2140', N'Import_Excel_KeHoachSanXuat', N'EXEC MP21410 @DivisionID = @DivisionID, @UserID = @UserID, @ImportTemplateID = @ImportTemplateID, @ImportTransTypeID = @ImportTransTypeID, @XML = @XML', 70, N'Quantity50', N'Ngày sản xuất 50', N'Quantity50', N'', 80, 50, 2, N'DATETIME', N'', 0, N'BO')
INSERT INTO A00065(ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ScreenID, TemplateFileName, ExecSQL, OrderNum, ColID, ColName, ColNameEng, InputMask, ColWidth, ColLength, ColType, ColSQLDataType, CheckExpression, IsObligated, DataCol) VALUES (N'ProductionPlan', N'Kế hoạch sản xuất', N'ProductionPlan', N'MF2140', N'Import_Excel_KeHoachSanXuat', N'EXEC MP21410 @DivisionID = @DivisionID, @UserID = @UserID, @ImportTemplateID = @ImportTemplateID, @ImportTransTypeID = @ImportTransTypeID, @XML = @XML', 81, N'Quantity51', N'Ngày sản xuất 51', N'Quantity51', N'', 80, 50, 2, N'DATETIME', N'', 0, N'BP')
INSERT INTO A00065(ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ScreenID, TemplateFileName, ExecSQL, OrderNum, ColID, ColName, ColNameEng, InputMask, ColWidth, ColLength, ColType, ColSQLDataType, CheckExpression, IsObligated, DataCol) VALUES (N'ProductionPlan', N'Kế hoạch sản xuất', N'ProductionPlan', N'MF2140', N'Import_Excel_KeHoachSanXuat', N'EXEC MP21410 @DivisionID = @DivisionID, @UserID = @UserID, @ImportTemplateID = @ImportTemplateID, @ImportTransTypeID = @ImportTransTypeID, @XML = @XML', 82, N'Quantity52', N'Ngày sản xuất 52', N'Quantity52', N'', 80, 50, 2, N'DATETIME', N'', 0, N'BQ')
INSERT INTO A00065(ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ScreenID, TemplateFileName, ExecSQL, OrderNum, ColID, ColName, ColNameEng, InputMask, ColWidth, ColLength, ColType, ColSQLDataType, CheckExpression, IsObligated, DataCol) VALUES (N'ProductionPlan', N'Kế hoạch sản xuất', N'ProductionPlan', N'MF2140', N'Import_Excel_KeHoachSanXuat', N'EXEC MP21410 @DivisionID = @DivisionID, @UserID = @UserID, @ImportTemplateID = @ImportTemplateID, @ImportTransTypeID = @ImportTransTypeID, @XML = @XML', 83, N'Quantity53', N'Ngày sản xuất 53', N'Quantity53', N'', 80, 50, 2, N'DATETIME', N'', 0, N'BR')
INSERT INTO A00065(ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ScreenID, TemplateFileName, ExecSQL, OrderNum, ColID, ColName, ColNameEng, InputMask, ColWidth, ColLength, ColType, ColSQLDataType, CheckExpression, IsObligated, DataCol) VALUES (N'ProductionPlan', N'Kế hoạch sản xuất', N'ProductionPlan', N'MF2140', N'Import_Excel_KeHoachSanXuat', N'EXEC MP21410 @DivisionID = @DivisionID, @UserID = @UserID, @ImportTemplateID = @ImportTemplateID, @ImportTransTypeID = @ImportTransTypeID, @XML = @XML', 84, N'Quantity54', N'Ngày sản xuất 54', N'Quantity54', N'', 80, 50, 2, N'DATETIME', N'', 0, N'BS')
INSERT INTO A00065(ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ScreenID, TemplateFileName, ExecSQL, OrderNum, ColID, ColName, ColNameEng, InputMask, ColWidth, ColLength, ColType, ColSQLDataType, CheckExpression, IsObligated, DataCol) VALUES (N'ProductionPlan', N'Kế hoạch sản xuất', N'ProductionPlan', N'MF2140', N'Import_Excel_KeHoachSanXuat', N'EXEC MP21410 @DivisionID = @DivisionID, @UserID = @UserID, @ImportTemplateID = @ImportTemplateID, @ImportTransTypeID = @ImportTransTypeID, @XML = @XML', 85, N'Quantity55', N'Ngày sản xuất 55', N'Quantity55', N'', 80, 50, 2, N'DATETIME', N'', 0, N'BT')
INSERT INTO A00065(ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ScreenID, TemplateFileName, ExecSQL, OrderNum, ColID, ColName, ColNameEng, InputMask, ColWidth, ColLength, ColType, ColSQLDataType, CheckExpression, IsObligated, DataCol) VALUES (N'ProductionPlan', N'Kế hoạch sản xuất', N'ProductionPlan', N'MF2140', N'Import_Excel_KeHoachSanXuat', N'EXEC MP21410 @DivisionID = @DivisionID, @UserID = @UserID, @ImportTemplateID = @ImportTemplateID, @ImportTransTypeID = @ImportTransTypeID, @XML = @XML', 86, N'Quantity56', N'Ngày sản xuất 56', N'Quantity56', N'', 80, 50, 2, N'DATETIME', N'', 0, N'BU')
INSERT INTO A00065(ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ScreenID, TemplateFileName, ExecSQL, OrderNum, ColID, ColName, ColNameEng, InputMask, ColWidth, ColLength, ColType, ColSQLDataType, CheckExpression, IsObligated, DataCol) VALUES (N'ProductionPlan', N'Kế hoạch sản xuất', N'ProductionPlan', N'MF2140', N'Import_Excel_KeHoachSanXuat', N'EXEC MP21410 @DivisionID = @DivisionID, @UserID = @UserID, @ImportTemplateID = @ImportTemplateID, @ImportTransTypeID = @ImportTransTypeID, @XML = @XML', 87, N'Quantity57', N'Ngày sản xuất 57', N'Quantity57', N'', 80, 50, 2, N'DATETIME', N'', 0, N'BV')
INSERT INTO A00065(ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ScreenID, TemplateFileName, ExecSQL, OrderNum, ColID, ColName, ColNameEng, InputMask, ColWidth, ColLength, ColType, ColSQLDataType, CheckExpression, IsObligated, DataCol) VALUES (N'ProductionPlan', N'Kế hoạch sản xuất', N'ProductionPlan', N'MF2140', N'Import_Excel_KeHoachSanXuat', N'EXEC MP21410 @DivisionID = @DivisionID, @UserID = @UserID, @ImportTemplateID = @ImportTemplateID, @ImportTransTypeID = @ImportTransTypeID, @XML = @XML', 88, N'Quantity58', N'Ngày sản xuất 58', N'Quantity58', N'', 80, 50, 2, N'DATETIME', N'', 0, N'BW')
INSERT INTO A00065(ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ScreenID, TemplateFileName, ExecSQL, OrderNum, ColID, ColName, ColNameEng, InputMask, ColWidth, ColLength, ColType, ColSQLDataType, CheckExpression, IsObligated, DataCol) VALUES (N'ProductionPlan', N'Kế hoạch sản xuất', N'ProductionPlan', N'MF2140', N'Import_Excel_KeHoachSanXuat', N'EXEC MP21410 @DivisionID = @DivisionID, @UserID = @UserID, @ImportTemplateID = @ImportTemplateID, @ImportTransTypeID = @ImportTransTypeID, @XML = @XML', 89, N'Quantity59', N'Ngày sản xuất 59', N'Quantity59', N'', 80, 50, 2, N'DATETIME', N'', 0, N'BX')
INSERT INTO A00065(ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ScreenID, TemplateFileName, ExecSQL, OrderNum, ColID, ColName, ColNameEng, InputMask, ColWidth, ColLength, ColType, ColSQLDataType, CheckExpression, IsObligated, DataCol) VALUES (N'ProductionPlan', N'Kế hoạch sản xuất', N'ProductionPlan', N'MF2140', N'Import_Excel_KeHoachSanXuat', N'EXEC MP21410 @DivisionID = @DivisionID, @UserID = @UserID, @ImportTemplateID = @ImportTemplateID, @ImportTransTypeID = @ImportTransTypeID, @XML = @XML', 90, N'Quantity60', N'Ngày sản xuất 60', N'Quantity60', N'', 80, 50, 2, N'DATETIME', N'', 0, N'BY')
