-- <Summary>
----
-- <Param>
----
-- <Return>
----
-- <Reference>
----
-- <History>
---- Create on 11/06/2021 by Viết Toàn: Thêm dữ liệu nghiệp vụ tiến độ giao hàng
---- Modified on ... by ...
-- <Example>

-----------------------------------------------------------------------------------------

DECLARE @CustomerName INT
SET @CustomerName = (SELECT CustomerName FROM CustomerIndex)


DELETE A00065 WHERE ImportTransTypeID = 'ShipmentStatus'
DELETE A01065 WHERE ImportTemplateID = 'ShipmentStatus'

INSERT INTO A00065 (ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ExecSQL, ScreenID, TemplateFileName,OrderNum, ColID, ColName, ColNameEng, ColSQLDataType, IsObligated, DataCol, ColWidth, InputMask) VALUES ('ShipmentStatus',N'Tiến độ giao hàng','ShipmentStatus','EXEC SOP2109 @DivisionID = @DivisionID, @UserID = @UserID, @TranMonth = @TranMonth, @TranYear = @TranYear,@Mode = @Mode, @ImportTransTypeID = @ImportTransTypeID, @TransactionKey = @TransactionKey, @XML = @XML','SOF2100', 'Import_Excel_TienDoGiaoHang.xlsx',1, 'DivisionID', N'Đơn vị', 'DivisionID', 'VARCHAR(50)', 1, 'B3',100, '') 
INSERT INTO A00065 (ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ExecSQL, ScreenID, TemplateFileName,OrderNum, ColID, ColName, ColNameEng, ColSQLDataType, IsObligated, DataCol, ColWidth, InputMask) VALUES ('ShipmentStatus',N'Tiến độ giao hàng','ShipmentStatus','EXEC SOP2109 @DivisionID = @DivisionID, @UserID = @UserID, @TranMonth = @TranMonth, @TranYear = @TranYear,@Mode = @Mode, @ImportTransTypeID = @ImportTransTypeID, @TransactionKey = @TransactionKey, @XML = @XML','SOF2100', 'Import_Excel_TienDoGiaoHang.xlsx',2, 'Period', N'Kỳ kế toán', 'Period', 'NVARCHAR(50)', 0, 'B4',100, '') 
INSERT INTO A00065 (ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ExecSQL, ScreenID, TemplateFileName,OrderNum, ColID, ColName, ColNameEng, ColSQLDataType, IsObligated, DataCol, ColWidth, InputMask) VALUES ('ShipmentStatus',N'Tiến độ giao hàng','ShipmentStatus','EXEC SOP2109 @DivisionID = @DivisionID, @UserID = @UserID, @TranMonth = @TranMonth, @TranYear = @TranYear,@Mode = @Mode, @ImportTransTypeID = @ImportTransTypeID, @TransactionKey = @TransactionKey, @XML = @XML','SOF2100', 'Import_Excel_TienDoGiaoHang.xlsx',3, 'VoucherNo', N'Số chứng từ', 'VoucherNo', 'NVARCHAR(50)', 1, 'A',500, '') 
INSERT INTO A00065 (ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ExecSQL, ScreenID, TemplateFileName,OrderNum, ColID, ColName, ColNameEng, ColSQLDataType, IsObligated, DataCol, ColWidth, InputMask) VALUES ('ShipmentStatus',N'Tiến độ giao hàng','ShipmentStatus','EXEC SOP2109 @DivisionID = @DivisionID, @UserID = @UserID, @TranMonth = @TranMonth, @TranYear = @TranYear,@Mode = @Mode, @ImportTransTypeID = @ImportTransTypeID, @TransactionKey = @TransactionKey, @XML = @XML','SOF2100', 'Import_Excel_TienDoGiaoHang.xlsx',4, 'VoucherDate', N'Ngày chứng từ', 'VoucherDate', 'DateTime', 1, 'B',100, '') 
INSERT INTO A00065 (ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ExecSQL, ScreenID, TemplateFileName,OrderNum, ColID, ColName, ColNameEng, ColSQLDataType, IsObligated, DataCol, ColWidth, InputMask) VALUES ('ShipmentStatus',N'Tiến độ giao hàng','ShipmentStatus','EXEC SOP2109 @DivisionID = @DivisionID, @UserID = @UserID, @TranMonth = @TranMonth, @TranYear = @TranYear,@Mode = @Mode, @ImportTransTypeID = @ImportTransTypeID, @TransactionKey = @TransactionKey, @XML = @XML','SOF2100', 'Import_Excel_TienDoGiaoHang.xlsx',5, 'ShipStartDate', N'Ngày tàu chạy', 'ShipStartDate', 'DateTime', 0, 'C',100, '') 
INSERT INTO A00065 (ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ExecSQL, ScreenID, TemplateFileName,OrderNum, ColID, ColName, ColNameEng, ColSQLDataType, IsObligated, DataCol, ColWidth, InputMask) VALUES ('ShipmentStatus',N'Tiến độ giao hàng','ShipmentStatus','EXEC SOP2109 @DivisionID = @DivisionID, @UserID = @UserID, @TranMonth = @TranMonth, @TranYear = @TranYear,@Mode = @Mode, @ImportTransTypeID = @ImportTransTypeID, @TransactionKey = @TransactionKey, @XML = @XML','SOF2100', 'Import_Excel_TienDoGiaoHang.xlsx',6, 'SOrderID', N'Đơn hàng bán', 'SOrderID', 'VARCHAR(50)', 1, 'D',100, '') 
INSERT INTO A00065 (ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ExecSQL, ScreenID, TemplateFileName,OrderNum, ColID, ColName, ColNameEng, ColSQLDataType, IsObligated, DataCol, ColWidth, InputMask) VALUES ('ShipmentStatus',N'Tiến độ giao hàng','ShipmentStatus','EXEC SOP2109 @DivisionID = @DivisionID, @UserID = @UserID, @TranMonth = @TranMonth, @TranYear = @TranYear,@Mode = @Mode, @ImportTransTypeID = @ImportTransTypeID, @TransactionKey = @TransactionKey, @XML = @XML','SOF2100', 'Import_Excel_TienDoGiaoHang.xlsx',7, 'ObjectID', N'Khách hàng', 'ObjectID', 'VARCHAR(250)', 1, 'E',100, '') 
INSERT INTO A00065 (ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ExecSQL, ScreenID, TemplateFileName,OrderNum, ColID, ColName, ColNameEng, ColSQLDataType, IsObligated, DataCol, ColWidth, InputMask) VALUES ('ShipmentStatus',N'Tiến độ giao hàng','ShipmentStatus','EXEC SOP2109 @DivisionID = @DivisionID, @UserID = @UserID, @TranMonth = @TranMonth, @TranYear = @TranYear,@Mode = @Mode, @ImportTransTypeID = @ImportTransTypeID, @TransactionKey = @TransactionKey, @XML = @XML','SOF2100', 'Import_Excel_TienDoGiaoHang.xlsx',8, 'Address', N'Địa chỉ giao hàng', 'Address', N'NVARCHAR(250)', 0, 'F',500, '') 
INSERT INTO A00065 (ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ExecSQL, ScreenID, TemplateFileName,OrderNum, ColID, ColName, ColNameEng, ColSQLDataType, IsObligated, DataCol, ColWidth, InputMask) VALUES ('ShipmentStatus',N'Tiến độ giao hàng','ShipmentStatus','EXEC SOP2109 @DivisionID = @DivisionID, @UserID = @UserID, @TranMonth = @TranMonth, @TranYear = @TranYear,@Mode = @Mode, @ImportTransTypeID = @ImportTransTypeID, @TransactionKey = @TransactionKey, @XML = @XML','SOF2100', 'Import_Excel_TienDoGiaoHang.xlsx',9, 'InventoryID', N'Mã hàng', 'InventoryID', 'VARCHAR(50)', 1, 'G',100, '') 
INSERT INTO A00065 (ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ExecSQL, ScreenID, TemplateFileName,OrderNum, ColID, ColName, ColNameEng, ColSQLDataType, IsObligated, DataCol, ColWidth, InputMask) VALUES ('ShipmentStatus',N'Tiến độ giao hàng','ShipmentStatus','EXEC SOP2109 @DivisionID = @DivisionID, @UserID = @UserID, @TranMonth = @TranMonth, @TranYear = @TranYear,@Mode = @Mode, @ImportTransTypeID = @ImportTransTypeID, @TransactionKey = @TransactionKey, @XML = @XML','SOF2100', 'Import_Excel_TienDoGiaoHang.xlsx',10, 'UnitID', N'Đơn vị tính', 'UnitID', 'VARCHAR(50)', 0, 'H',100, '') 
INSERT INTO A00065 (ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ExecSQL, ScreenID, TemplateFileName,OrderNum, ColID, ColName, ColNameEng, ColSQLDataType, IsObligated, DataCol, ColWidth, InputMask) VALUES ('ShipmentStatus',N'Tiến độ giao hàng','ShipmentStatus','EXEC SOP2109 @DivisionID = @DivisionID, @UserID = @UserID, @TranMonth = @TranMonth, @TranYear = @TranYear,@Mode = @Mode, @ImportTransTypeID = @ImportTransTypeID, @TransactionKey = @TransactionKey, @XML = @XML','SOF2100', 'Import_Excel_TienDoGiaoHang.xlsx',11, 'OrderQuantity', N'Số lượng', 'OrderQuantity', 'DECIMAL(28,8)', 0, 'I',100, '') 
INSERT INTO A00065 (ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ExecSQL, ScreenID, TemplateFileName,OrderNum, ColID, ColName, ColNameEng, ColSQLDataType, IsObligated, DataCol, ColWidth, InputMask) VALUES ('ShipmentStatus',N'Tiến độ giao hàng','ShipmentStatus','EXEC SOP2109 @DivisionID = @DivisionID, @UserID = @UserID, @TranMonth = @TranMonth, @TranYear = @TranYear,@Mode = @Mode, @ImportTransTypeID = @ImportTransTypeID, @TransactionKey = @TransactionKey, @XML = @XML','SOF2100', 'Import_Excel_TienDoGiaoHang.xlsx',12, 'Date01', N'Ngày 01', 'Date01', 'DateTime', 0, 'J',100, '')  
INSERT INTO A00065 (ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ExecSQL, ScreenID, TemplateFileName,OrderNum, ColID, ColName, ColNameEng, ColSQLDataType, IsObligated, DataCol, ColWidth, InputMask) VALUES ('ShipmentStatus',N'Tiến độ giao hàng','ShipmentStatus','EXEC SOP2109 @DivisionID = @DivisionID, @UserID = @UserID, @TranMonth = @TranMonth, @TranYear = @TranYear,@Mode = @Mode, @ImportTransTypeID = @ImportTransTypeID, @TransactionKey = @TransactionKey, @XML = @XML','SOF2100', 'Import_Excel_TienDoGiaoHang.xlsx',13, 'Quantity01', N'Giá trị 01', 'Quantity01', 'DECIMAL(28,8)', 0, 'K',100, '') 
INSERT INTO A00065 (ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ExecSQL, ScreenID, TemplateFileName,OrderNum, ColID, ColName, ColNameEng, ColSQLDataType, IsObligated, DataCol, ColWidth, InputMask) VALUES ('ShipmentStatus',N'Tiến độ giao hàng','ShipmentStatus','EXEC SOP2109 @DivisionID = @DivisionID, @UserID = @UserID, @TranMonth = @TranMonth, @TranYear = @TranYear,@Mode = @Mode, @ImportTransTypeID = @ImportTransTypeID, @TransactionKey = @TransactionKey, @XML = @XML','SOF2100', 'Import_Excel_TienDoGiaoHang.xlsx',14, 'Date02', N'Ngày 02', 'Date02', 'DateTime', 0, 'L',100, '')  
INSERT INTO A00065 (ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ExecSQL, ScreenID, TemplateFileName,OrderNum, ColID, ColName, ColNameEng, ColSQLDataType, IsObligated, DataCol, ColWidth, InputMask) VALUES ('ShipmentStatus',N'Tiến độ giao hàng','ShipmentStatus','EXEC SOP2109 @DivisionID = @DivisionID, @UserID = @UserID, @TranMonth = @TranMonth, @TranYear = @TranYear,@Mode = @Mode, @ImportTransTypeID = @ImportTransTypeID, @TransactionKey = @TransactionKey, @XML = @XML','SOF2100', 'Import_Excel_TienDoGiaoHang.xlsx',15, 'Quantity02', N'Giá trị 02', 'Quantity02', 'DECIMAL(28,8)', 0, 'M',100, '') 
INSERT INTO A00065 (ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ExecSQL, ScreenID, TemplateFileName,OrderNum, ColID, ColName, ColNameEng, ColSQLDataType, IsObligated, DataCol, ColWidth, InputMask) VALUES ('ShipmentStatus',N'Tiến độ giao hàng','ShipmentStatus','EXEC SOP2109 @DivisionID = @DivisionID, @UserID = @UserID, @TranMonth = @TranMonth, @TranYear = @TranYear,@Mode = @Mode, @ImportTransTypeID = @ImportTransTypeID, @TransactionKey = @TransactionKey, @XML = @XML','SOF2100', 'Import_Excel_TienDoGiaoHang.xlsx',16, 'Date03', N'Ngày 03', 'Date03', 'DateTime', 0, 'N',100, '') 
INSERT INTO A00065 (ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ExecSQL, ScreenID, TemplateFileName,OrderNum, ColID, ColName, ColNameEng, ColSQLDataType, IsObligated, DataCol, ColWidth, InputMask) VALUES ('ShipmentStatus',N'Tiến độ giao hàng','ShipmentStatus','EXEC SOP2109 @DivisionID = @DivisionID, @UserID = @UserID, @TranMonth = @TranMonth, @TranYear = @TranYear,@Mode = @Mode, @ImportTransTypeID = @ImportTransTypeID, @TransactionKey = @TransactionKey, @XML = @XML','SOF2100', 'Import_Excel_TienDoGiaoHang.xlsx',17, 'Quantity03', N'Giá trị 03', 'Quantity03', 'DECIMAL(28,8)', 0, 'O',100, '') 
INSERT INTO A00065 (ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ExecSQL, ScreenID, TemplateFileName,OrderNum, ColID, ColName, ColNameEng, ColSQLDataType, IsObligated, DataCol, ColWidth, InputMask) VALUES ('ShipmentStatus',N'Tiến độ giao hàng','ShipmentStatus','EXEC SOP2109 @DivisionID = @DivisionID, @UserID = @UserID, @TranMonth = @TranMonth, @TranYear = @TranYear,@Mode = @Mode, @ImportTransTypeID = @ImportTransTypeID, @TransactionKey = @TransactionKey, @XML = @XML','SOF2100', 'Import_Excel_TienDoGiaoHang.xlsx',18, 'Date04', N'Ngày 04', 'Date04', 'DateTime', 0, 'P',100, '') 
INSERT INTO A00065 (ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ExecSQL, ScreenID, TemplateFileName,OrderNum, ColID, ColName, ColNameEng, ColSQLDataType, IsObligated, DataCol, ColWidth, InputMask) VALUES ('ShipmentStatus',N'Tiến độ giao hàng','ShipmentStatus','EXEC SOP2109 @DivisionID = @DivisionID, @UserID = @UserID, @TranMonth = @TranMonth, @TranYear = @TranYear,@Mode = @Mode, @ImportTransTypeID = @ImportTransTypeID, @TransactionKey = @TransactionKey, @XML = @XML','SOF2100', 'Import_Excel_TienDoGiaoHang.xlsx',19, 'Quantity04', N'Giá trị 04', 'Quantity04', 'DECIMAL(28,8)', 0, 'Q',100, '') 
INSERT INTO A00065 (ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ExecSQL, ScreenID, TemplateFileName,OrderNum, ColID, ColName, ColNameEng, ColSQLDataType, IsObligated, DataCol, ColWidth, InputMask) VALUES ('ShipmentStatus',N'Tiến độ giao hàng','ShipmentStatus','EXEC SOP2109 @DivisionID = @DivisionID, @UserID = @UserID, @TranMonth = @TranMonth, @TranYear = @TranYear,@Mode = @Mode, @ImportTransTypeID = @ImportTransTypeID, @TransactionKey = @TransactionKey, @XML = @XML','SOF2100', 'Import_Excel_TienDoGiaoHang.xlsx',20, 'Date05', N'Ngày 05', 'Date05', 'DateTime', 0, 'R',100, '') 
INSERT INTO A00065 (ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ExecSQL, ScreenID, TemplateFileName,OrderNum, ColID, ColName, ColNameEng, ColSQLDataType, IsObligated, DataCol, ColWidth, InputMask) VALUES ('ShipmentStatus',N'Tiến độ giao hàng','ShipmentStatus','EXEC SOP2109 @DivisionID = @DivisionID, @UserID = @UserID, @TranMonth = @TranMonth, @TranYear = @TranYear,@Mode = @Mode, @ImportTransTypeID = @ImportTransTypeID, @TransactionKey = @TransactionKey, @XML = @XML','SOF2100', 'Import_Excel_TienDoGiaoHang.xlsx',21, 'Quantity05', N'Giá trị 05', 'Quantity05', 'DECIMAL(28,8)', 0, 'S',100, '') 
INSERT INTO A00065 (ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ExecSQL, ScreenID, TemplateFileName,OrderNum, ColID, ColName, ColNameEng, ColSQLDataType, IsObligated, DataCol, ColWidth, InputMask) VALUES ('ShipmentStatus',N'Tiến độ giao hàng','ShipmentStatus','EXEC SOP2109 @DivisionID = @DivisionID, @UserID = @UserID, @TranMonth = @TranMonth, @TranYear = @TranYear,@Mode = @Mode, @ImportTransTypeID = @ImportTransTypeID, @TransactionKey = @TransactionKey, @XML = @XML','SOF2100', 'Import_Excel_TienDoGiaoHang.xlsx',22, 'Date06', N'Ngày 06', 'Date06', 'DateTime', 0, 'T',100, '') 
INSERT INTO A00065 (ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ExecSQL, ScreenID, TemplateFileName,OrderNum, ColID, ColName, ColNameEng, ColSQLDataType, IsObligated, DataCol, ColWidth, InputMask) VALUES ('ShipmentStatus',N'Tiến độ giao hàng','ShipmentStatus','EXEC SOP2109 @DivisionID = @DivisionID, @UserID = @UserID, @TranMonth = @TranMonth, @TranYear = @TranYear,@Mode = @Mode, @ImportTransTypeID = @ImportTransTypeID, @TransactionKey = @TransactionKey, @XML = @XML','SOF2100', 'Import_Excel_TienDoGiaoHang.xlsx',23, 'Quantity06', N'Giá trị 06', 'Quantity06', 'DECIMAL(28,8)', 0, 'U',100, '') 
INSERT INTO A00065 (ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ExecSQL, ScreenID, TemplateFileName,OrderNum, ColID, ColName, ColNameEng, ColSQLDataType, IsObligated, DataCol, ColWidth, InputMask) VALUES ('ShipmentStatus',N'Tiến độ giao hàng','ShipmentStatus','EXEC SOP2109 @DivisionID = @DivisionID, @UserID = @UserID, @TranMonth = @TranMonth, @TranYear = @TranYear,@Mode = @Mode, @ImportTransTypeID = @ImportTransTypeID, @TransactionKey = @TransactionKey, @XML = @XML','SOF2100', 'Import_Excel_TienDoGiaoHang.xlsx',24, 'Date07', N'Ngày 07', 'Date07', 'DateTime', 0, 'V',100, '') 
INSERT INTO A00065 (ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ExecSQL, ScreenID, TemplateFileName,OrderNum, ColID, ColName, ColNameEng, ColSQLDataType, IsObligated, DataCol, ColWidth, InputMask) VALUES ('ShipmentStatus',N'Tiến độ giao hàng','ShipmentStatus','EXEC SOP2109 @DivisionID = @DivisionID, @UserID = @UserID, @TranMonth = @TranMonth, @TranYear = @TranYear,@Mode = @Mode, @ImportTransTypeID = @ImportTransTypeID, @TransactionKey = @TransactionKey, @XML = @XML','SOF2100', 'Import_Excel_TienDoGiaoHang.xlsx',25, 'Quantity07', N'Giá trị 07', 'Quantity07', 'DECIMAL(28,8)', 0, 'W',100, '') 
INSERT INTO A00065 (ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ExecSQL, ScreenID, TemplateFileName,OrderNum, ColID, ColName, ColNameEng, ColSQLDataType, IsObligated, DataCol, ColWidth, InputMask) VALUES ('ShipmentStatus',N'Tiến độ giao hàng','ShipmentStatus','EXEC SOP2109 @DivisionID = @DivisionID, @UserID = @UserID, @TranMonth = @TranMonth, @TranYear = @TranYear,@Mode = @Mode, @ImportTransTypeID = @ImportTransTypeID, @TransactionKey = @TransactionKey, @XML = @XML','SOF2100', 'Import_Excel_TienDoGiaoHang.xlsx',26, 'Date08', N'Ngày 08', 'Date08', 'DateTime', 0, 'X',100, '') 
INSERT INTO A00065 (ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ExecSQL, ScreenID, TemplateFileName,OrderNum, ColID, ColName, ColNameEng, ColSQLDataType, IsObligated, DataCol, ColWidth, InputMask) VALUES ('ShipmentStatus',N'Tiến độ giao hàng','ShipmentStatus','EXEC SOP2109 @DivisionID = @DivisionID, @UserID = @UserID, @TranMonth = @TranMonth, @TranYear = @TranYear,@Mode = @Mode, @ImportTransTypeID = @ImportTransTypeID, @TransactionKey = @TransactionKey, @XML = @XML','SOF2100', 'Import_Excel_TienDoGiaoHang.xlsx',27, 'Quantity08', N'Giá trị 08', 'Quantity08', 'DECIMAL(28,8)', 0, 'Y',100, '') 
INSERT INTO A00065 (ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ExecSQL, ScreenID, TemplateFileName,OrderNum, ColID, ColName, ColNameEng, ColSQLDataType, IsObligated, DataCol, ColWidth, InputMask) VALUES ('ShipmentStatus',N'Tiến độ giao hàng','ShipmentStatus','EXEC SOP2109 @DivisionID = @DivisionID, @UserID = @UserID, @TranMonth = @TranMonth, @TranYear = @TranYear,@Mode = @Mode, @ImportTransTypeID = @ImportTransTypeID, @TransactionKey = @TransactionKey, @XML = @XML','SOF2100', 'Import_Excel_TienDoGiaoHang.xlsx',28, 'Date09', N'Ngày 09', 'Date09', 'DateTime', 0, 'Z',100, '') 
INSERT INTO A00065 (ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ExecSQL, ScreenID, TemplateFileName,OrderNum, ColID, ColName, ColNameEng, ColSQLDataType, IsObligated, DataCol, ColWidth, InputMask) VALUES ('ShipmentStatus',N'Tiến độ giao hàng','ShipmentStatus','EXEC SOP2109 @DivisionID = @DivisionID, @UserID = @UserID, @TranMonth = @TranMonth, @TranYear = @TranYear,@Mode = @Mode, @ImportTransTypeID = @ImportTransTypeID, @TransactionKey = @TransactionKey, @XML = @XML','SOF2100', 'Import_Excel_TienDoGiaoHang.xlsx',29, 'Quantity09', N'Giá trị 09', 'Quantity09', 'DECIMAL(28,8)', 0, 'AA',100, '') 
INSERT INTO A00065 (ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ExecSQL, ScreenID, TemplateFileName,OrderNum, ColID, ColName, ColNameEng, ColSQLDataType, IsObligated, DataCol, ColWidth, InputMask) VALUES ('ShipmentStatus',N'Tiến độ giao hàng','ShipmentStatus','EXEC SOP2109 @DivisionID = @DivisionID, @UserID = @UserID, @TranMonth = @TranMonth, @TranYear = @TranYear,@Mode = @Mode, @ImportTransTypeID = @ImportTransTypeID, @TransactionKey = @TransactionKey, @XML = @XML','SOF2100', 'Import_Excel_TienDoGiaoHang.xlsx',30, 'Date10', N'Ngày 10', 'Date10', 'DateTime', 0, 'AB',100, '') 
INSERT INTO A00065 (ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ExecSQL, ScreenID, TemplateFileName,OrderNum, ColID, ColName, ColNameEng, ColSQLDataType, IsObligated, DataCol, ColWidth, InputMask) VALUES ('ShipmentStatus',N'Tiến độ giao hàng','ShipmentStatus','EXEC SOP2109 @DivisionID = @DivisionID, @UserID = @UserID, @TranMonth = @TranMonth, @TranYear = @TranYear,@Mode = @Mode, @ImportTransTypeID = @ImportTransTypeID, @TransactionKey = @TransactionKey, @XML = @XML','SOF2100', 'Import_Excel_TienDoGiaoHang.xlsx',31, 'Quantity10', N'Giá trị 10', 'Quantity10', 'DECIMAL(28,8)', 0, 'AC',100, '') 
INSERT INTO A00065 (ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ExecSQL, ScreenID, TemplateFileName,OrderNum, ColID, ColName, ColNameEng, ColSQLDataType, IsObligated, DataCol, ColWidth, InputMask) VALUES ('ShipmentStatus',N'Tiến độ giao hàng','ShipmentStatus','EXEC SOP2109 @DivisionID = @DivisionID, @UserID = @UserID, @TranMonth = @TranMonth, @TranYear = @TranYear,@Mode = @Mode, @ImportTransTypeID = @ImportTransTypeID, @TransactionKey = @TransactionKey, @XML = @XML','SOF2100', 'Import_Excel_TienDoGiaoHang.xlsx',32, 'Date11', N'Ngày 11', 'Date11', 'DateTime', 0, 'AD',100, '') 
INSERT INTO A00065 (ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ExecSQL, ScreenID, TemplateFileName,OrderNum, ColID, ColName, ColNameEng, ColSQLDataType, IsObligated, DataCol, ColWidth, InputMask) VALUES ('ShipmentStatus',N'Tiến độ giao hàng','ShipmentStatus','EXEC SOP2109 @DivisionID = @DivisionID, @UserID = @UserID, @TranMonth = @TranMonth, @TranYear = @TranYear,@Mode = @Mode, @ImportTransTypeID = @ImportTransTypeID, @TransactionKey = @TransactionKey, @XML = @XML','SOF2100', 'Import_Excel_TienDoGiaoHang.xlsx',33, 'Quantity11', N'Giá trị 11', 'Quantity11', 'DECIMAL(28,8)', 0, 'AE',100, '') 
INSERT INTO A00065 (ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ExecSQL, ScreenID, TemplateFileName,OrderNum, ColID, ColName, ColNameEng, ColSQLDataType, IsObligated, DataCol, ColWidth, InputMask) VALUES ('ShipmentStatus',N'Tiến độ giao hàng','ShipmentStatus','EXEC SOP2109 @DivisionID = @DivisionID, @UserID = @UserID, @TranMonth = @TranMonth, @TranYear = @TranYear,@Mode = @Mode, @ImportTransTypeID = @ImportTransTypeID, @TransactionKey = @TransactionKey, @XML = @XML','SOF2100', 'Import_Excel_TienDoGiaoHang.xlsx',34, 'Date12', N'Ngày 12', 'Date12', 'DateTime', 0, 'AF',100, '') 
INSERT INTO A00065 (ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ExecSQL, ScreenID, TemplateFileName,OrderNum, ColID, ColName, ColNameEng, ColSQLDataType, IsObligated, DataCol, ColWidth, InputMask) VALUES ('ShipmentStatus',N'Tiến độ giao hàng','ShipmentStatus','EXEC SOP2109 @DivisionID = @DivisionID, @UserID = @UserID, @TranMonth = @TranMonth, @TranYear = @TranYear,@Mode = @Mode, @ImportTransTypeID = @ImportTransTypeID, @TransactionKey = @TransactionKey, @XML = @XML','SOF2100', 'Import_Excel_TienDoGiaoHang.xlsx',35, 'Quantity12', N'Giá trị 12', 'Quantity12', 'DECIMAL(28,8)', 0, 'AG',100, '') 
INSERT INTO A00065 (ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ExecSQL, ScreenID, TemplateFileName,OrderNum, ColID, ColName, ColNameEng, ColSQLDataType, IsObligated, DataCol, ColWidth, InputMask) VALUES ('ShipmentStatus',N'Tiến độ giao hàng','ShipmentStatus','EXEC SOP2109 @DivisionID = @DivisionID, @UserID = @UserID, @TranMonth = @TranMonth, @TranYear = @TranYear,@Mode = @Mode, @ImportTransTypeID = @ImportTransTypeID, @TransactionKey = @TransactionKey, @XML = @XML','SOF2100', 'Import_Excel_TienDoGiaoHang.xlsx',36, 'Date13', N'Ngày 13', 'Date13', 'DateTime', 0, 'AH',100, '') 
INSERT INTO A00065 (ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ExecSQL, ScreenID, TemplateFileName,OrderNum, ColID, ColName, ColNameEng, ColSQLDataType, IsObligated, DataCol, ColWidth, InputMask) VALUES ('ShipmentStatus',N'Tiến độ giao hàng','ShipmentStatus','EXEC SOP2109 @DivisionID = @DivisionID, @UserID = @UserID, @TranMonth = @TranMonth, @TranYear = @TranYear,@Mode = @Mode, @ImportTransTypeID = @ImportTransTypeID, @TransactionKey = @TransactionKey, @XML = @XML','SOF2100', 'Import_Excel_TienDoGiaoHang.xlsx',37, 'Quantity13', N'Giá trị 13', 'Quantity13', 'DECIMAL(28,8)', 0, 'AI',100, '') 
INSERT INTO A00065 (ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ExecSQL, ScreenID, TemplateFileName,OrderNum, ColID, ColName, ColNameEng, ColSQLDataType, IsObligated, DataCol, ColWidth, InputMask) VALUES ('ShipmentStatus',N'Tiến độ giao hàng','ShipmentStatus','EXEC SOP2109 @DivisionID = @DivisionID, @UserID = @UserID, @TranMonth = @TranMonth, @TranYear = @TranYear,@Mode = @Mode, @ImportTransTypeID = @ImportTransTypeID, @TransactionKey = @TransactionKey, @XML = @XML','SOF2100', 'Import_Excel_TienDoGiaoHang.xlsx',38, 'Date14', N'Ngày 14', 'Date14', 'DateTime', 0, 'AJ',100, '') 
INSERT INTO A00065 (ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ExecSQL, ScreenID, TemplateFileName,OrderNum, ColID, ColName, ColNameEng, ColSQLDataType, IsObligated, DataCol, ColWidth, InputMask) VALUES ('ShipmentStatus',N'Tiến độ giao hàng','ShipmentStatus','EXEC SOP2109 @DivisionID = @DivisionID, @UserID = @UserID, @TranMonth = @TranMonth, @TranYear = @TranYear,@Mode = @Mode, @ImportTransTypeID = @ImportTransTypeID, @TransactionKey = @TransactionKey, @XML = @XML','SOF2100', 'Import_Excel_TienDoGiaoHang.xlsx',39, 'Quantity14', N'Giá trị 14', 'Quantity14', 'DECIMAL(28,8)', 0, 'AK',100, '') 
INSERT INTO A00065 (ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ExecSQL, ScreenID, TemplateFileName,OrderNum, ColID, ColName, ColNameEng, ColSQLDataType, IsObligated, DataCol, ColWidth, InputMask) VALUES ('ShipmentStatus',N'Tiến độ giao hàng','ShipmentStatus','EXEC SOP2109 @DivisionID = @DivisionID, @UserID = @UserID, @TranMonth = @TranMonth, @TranYear = @TranYear,@Mode = @Mode, @ImportTransTypeID = @ImportTransTypeID, @TransactionKey = @TransactionKey, @XML = @XML','SOF2100', 'Import_Excel_TienDoGiaoHang.xlsx',40, 'Date15', N'Ngày 15', 'Date15', 'DateTime', 0, 'AL',100, '')
INSERT INTO A00065 (ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ExecSQL, ScreenID, TemplateFileName,OrderNum, ColID, ColName, ColNameEng, ColSQLDataType, IsObligated, DataCol, ColWidth, InputMask) VALUES ('ShipmentStatus',N'Tiến độ giao hàng','ShipmentStatus','EXEC SOP2109 @DivisionID = @DivisionID, @UserID = @UserID, @TranMonth = @TranMonth, @TranYear = @TranYear,@Mode = @Mode, @ImportTransTypeID = @ImportTransTypeID, @TransactionKey = @TransactionKey, @XML = @XML','SOF2100', 'Import_Excel_TienDoGiaoHang.xlsx',41, 'Quantity15', N'Giá trị 15', 'Quantity15', 'DECIMAL(28,8)', 0, 'AM',100, '')  
INSERT INTO A00065 (ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ExecSQL, ScreenID, TemplateFileName,OrderNum, ColID, ColName, ColNameEng, ColSQLDataType, IsObligated, DataCol, ColWidth, InputMask) VALUES ('ShipmentStatus',N'Tiến độ giao hàng','ShipmentStatus','EXEC SOP2109 @DivisionID = @DivisionID, @UserID = @UserID, @TranMonth = @TranMonth, @TranYear = @TranYear,@Mode = @Mode, @ImportTransTypeID = @ImportTransTypeID, @TransactionKey = @TransactionKey, @XML = @XML','SOF2100', 'Import_Excel_TienDoGiaoHang.xlsx',42, 'Date16', N'Ngày 16', 'Date16', 'DateTime', 0, 'AN',100, '') 
INSERT INTO A00065 (ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ExecSQL, ScreenID, TemplateFileName,OrderNum, ColID, ColName, ColNameEng, ColSQLDataType, IsObligated, DataCol, ColWidth, InputMask) VALUES ('ShipmentStatus',N'Tiến độ giao hàng','ShipmentStatus','EXEC SOP2109 @DivisionID = @DivisionID, @UserID = @UserID, @TranMonth = @TranMonth, @TranYear = @TranYear,@Mode = @Mode, @ImportTransTypeID = @ImportTransTypeID, @TransactionKey = @TransactionKey, @XML = @XML','SOF2100', 'Import_Excel_TienDoGiaoHang.xlsx',43, 'Quantity16', N'Giá trị 16', 'Quantity16', 'DECIMAL(28,8)', 0, 'AO',100, '') 
INSERT INTO A00065 (ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ExecSQL, ScreenID, TemplateFileName,OrderNum, ColID, ColName, ColNameEng, ColSQLDataType, IsObligated, DataCol, ColWidth, InputMask) VALUES ('ShipmentStatus',N'Tiến độ giao hàng','ShipmentStatus','EXEC SOP2109 @DivisionID = @DivisionID, @UserID = @UserID, @TranMonth = @TranMonth, @TranYear = @TranYear,@Mode = @Mode, @ImportTransTypeID = @ImportTransTypeID, @TransactionKey = @TransactionKey, @XML = @XML','SOF2100', 'Import_Excel_TienDoGiaoHang.xlsx',44, 'Date17', N'Ngày 17', 'Date17', 'DateTime', 0, 'AP',100, '') 
INSERT INTO A00065 (ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ExecSQL, ScreenID, TemplateFileName,OrderNum, ColID, ColName, ColNameEng, ColSQLDataType, IsObligated, DataCol, ColWidth, InputMask) VALUES ('ShipmentStatus',N'Tiến độ giao hàng','ShipmentStatus','EXEC SOP2109 @DivisionID = @DivisionID, @UserID = @UserID, @TranMonth = @TranMonth, @TranYear = @TranYear,@Mode = @Mode, @ImportTransTypeID = @ImportTransTypeID, @TransactionKey = @TransactionKey, @XML = @XML','SOF2100', 'Import_Excel_TienDoGiaoHang.xlsx',45, 'Quantity17', N'Giá trị 17', 'Quantity17', 'DECIMAL(28,8)', 0, 'AQ',100, '') 
INSERT INTO A00065 (ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ExecSQL, ScreenID, TemplateFileName,OrderNum, ColID, ColName, ColNameEng, ColSQLDataType, IsObligated, DataCol, ColWidth, InputMask) VALUES ('ShipmentStatus',N'Tiến độ giao hàng','ShipmentStatus','EXEC SOP2109 @DivisionID = @DivisionID, @UserID = @UserID, @TranMonth = @TranMonth, @TranYear = @TranYear,@Mode = @Mode, @ImportTransTypeID = @ImportTransTypeID, @TransactionKey = @TransactionKey, @XML = @XML','SOF2100', 'Import_Excel_TienDoGiaoHang.xlsx',46, 'Date18', N'Ngày 18', 'Date18', 'DateTime', 0, 'AR',100, '') 
INSERT INTO A00065 (ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ExecSQL, ScreenID, TemplateFileName,OrderNum, ColID, ColName, ColNameEng, ColSQLDataType, IsObligated, DataCol, ColWidth, InputMask) VALUES ('ShipmentStatus',N'Tiến độ giao hàng','ShipmentStatus','EXEC SOP2109 @DivisionID = @DivisionID, @UserID = @UserID, @TranMonth = @TranMonth, @TranYear = @TranYear,@Mode = @Mode, @ImportTransTypeID = @ImportTransTypeID, @TransactionKey = @TransactionKey, @XML = @XML','SOF2100', 'Import_Excel_TienDoGiaoHang.xlsx',47, 'Quantity18', N'Giá trị 18', 'Quantity18', 'DECIMAL(28,8)', 0, 'AS',100, '') 
INSERT INTO A00065 (ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ExecSQL, ScreenID, TemplateFileName,OrderNum, ColID, ColName, ColNameEng, ColSQLDataType, IsObligated, DataCol, ColWidth, InputMask) VALUES ('ShipmentStatus',N'Tiến độ giao hàng','ShipmentStatus','EXEC SOP2109 @DivisionID = @DivisionID, @UserID = @UserID, @TranMonth = @TranMonth, @TranYear = @TranYear,@Mode = @Mode, @ImportTransTypeID = @ImportTransTypeID, @TransactionKey = @TransactionKey, @XML = @XML','SOF2100', 'Import_Excel_TienDoGiaoHang.xlsx',48, 'Date19', N'Ngày 19', 'Date19', 'DateTime', 0, 'AT',100, '') 
INSERT INTO A00065 (ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ExecSQL, ScreenID, TemplateFileName,OrderNum, ColID, ColName, ColNameEng, ColSQLDataType, IsObligated, DataCol, ColWidth, InputMask) VALUES ('ShipmentStatus',N'Tiến độ giao hàng','ShipmentStatus','EXEC SOP2109 @DivisionID = @DivisionID, @UserID = @UserID, @TranMonth = @TranMonth, @TranYear = @TranYear,@Mode = @Mode, @ImportTransTypeID = @ImportTransTypeID, @TransactionKey = @TransactionKey, @XML = @XML','SOF2100', 'Import_Excel_TienDoGiaoHang.xlsx',49, 'Quantity19', N'Giá trị 19', 'Quantity19', 'DECIMAL(28,8)', 0, 'AU',100, '') 
INSERT INTO A00065 (ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ExecSQL, ScreenID, TemplateFileName,OrderNum, ColID, ColName, ColNameEng, ColSQLDataType, IsObligated, DataCol, ColWidth, InputMask) VALUES ('ShipmentStatus',N'Tiến độ giao hàng','ShipmentStatus','EXEC SOP2109 @DivisionID = @DivisionID, @UserID = @UserID, @TranMonth = @TranMonth, @TranYear = @TranYear,@Mode = @Mode, @ImportTransTypeID = @ImportTransTypeID, @TransactionKey = @TransactionKey, @XML = @XML','SOF2100', 'Import_Excel_TienDoGiaoHang.xlsx',50, 'Date20', N'Ngày 20', 'Date20', 'DateTime', 0, 'AV',100, '') 
INSERT INTO A00065 (ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ExecSQL, ScreenID, TemplateFileName,OrderNum, ColID, ColName, ColNameEng, ColSQLDataType, IsObligated, DataCol, ColWidth, InputMask) VALUES ('ShipmentStatus',N'Tiến độ giao hàng','ShipmentStatus','EXEC SOP2109 @DivisionID = @DivisionID, @UserID = @UserID, @TranMonth = @TranMonth, @TranYear = @TranYear,@Mode = @Mode, @ImportTransTypeID = @ImportTransTypeID, @TransactionKey = @TransactionKey, @XML = @XML','SOF2100', 'Import_Excel_TienDoGiaoHang.xlsx',51, 'Quantity20', N'Giá trị 20', 'Quantity20', 'DECIMAL(28,8)', 0, 'AW',100, '') 
INSERT INTO A00065 (ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ExecSQL, ScreenID, TemplateFileName,OrderNum, ColID, ColName, ColNameEng, ColSQLDataType, IsObligated, DataCol, ColWidth, InputMask) VALUES ('ShipmentStatus',N'Tiến độ giao hàng','ShipmentStatus','EXEC SOP2109 @DivisionID = @DivisionID, @UserID = @UserID, @TranMonth = @TranMonth, @TranYear = @TranYear,@Mode = @Mode, @ImportTransTypeID = @ImportTransTypeID, @TransactionKey = @TransactionKey, @XML = @XML','SOF2100', 'Import_Excel_TienDoGiaoHang.xlsx',52, 'Date21', N'Ngày 21', 'Date21', 'DateTime', 0, 'AX',100, '') 
INSERT INTO A00065 (ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ExecSQL, ScreenID, TemplateFileName,OrderNum, ColID, ColName, ColNameEng, ColSQLDataType, IsObligated, DataCol, ColWidth, InputMask) VALUES ('ShipmentStatus',N'Tiến độ giao hàng','ShipmentStatus','EXEC SOP2109 @DivisionID = @DivisionID, @UserID = @UserID, @TranMonth = @TranMonth, @TranYear = @TranYear,@Mode = @Mode, @ImportTransTypeID = @ImportTransTypeID, @TransactionKey = @TransactionKey, @XML = @XML','SOF2100', 'Import_Excel_TienDoGiaoHang.xlsx',53, 'Quantity21', N'Giá trị 21', 'Quantity21', 'DECIMAL(28,8)', 0, 'AY',100, '') 
INSERT INTO A00065 (ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ExecSQL, ScreenID, TemplateFileName,OrderNum, ColID, ColName, ColNameEng, ColSQLDataType, IsObligated, DataCol, ColWidth, InputMask) VALUES ('ShipmentStatus',N'Tiến độ giao hàng','ShipmentStatus','EXEC SOP2109 @DivisionID = @DivisionID, @UserID = @UserID, @TranMonth = @TranMonth, @TranYear = @TranYear,@Mode = @Mode, @ImportTransTypeID = @ImportTransTypeID, @TransactionKey = @TransactionKey, @XML = @XML','SOF2100', 'Import_Excel_TienDoGiaoHang.xlsx',54, 'Date22', N'Ngày 22', 'Date22', 'DateTime', 0, 'AZ',100, '') 
INSERT INTO A00065 (ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ExecSQL, ScreenID, TemplateFileName,OrderNum, ColID, ColName, ColNameEng, ColSQLDataType, IsObligated, DataCol, ColWidth, InputMask) VALUES ('ShipmentStatus',N'Tiến độ giao hàng','ShipmentStatus','EXEC SOP2109 @DivisionID = @DivisionID, @UserID = @UserID, @TranMonth = @TranMonth, @TranYear = @TranYear,@Mode = @Mode, @ImportTransTypeID = @ImportTransTypeID, @TransactionKey = @TransactionKey, @XML = @XML','SOF2100', 'Import_Excel_TienDoGiaoHang.xlsx',55, 'Quantity22', N'Giá trị 22', 'Quantity22', 'DECIMAL(28,8)', 0, 'BA',100, '') 
INSERT INTO A00065 (ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ExecSQL, ScreenID, TemplateFileName,OrderNum, ColID, ColName, ColNameEng, ColSQLDataType, IsObligated, DataCol, ColWidth, InputMask) VALUES ('ShipmentStatus',N'Tiến độ giao hàng','ShipmentStatus','EXEC SOP2109 @DivisionID = @DivisionID, @UserID = @UserID, @TranMonth = @TranMonth, @TranYear = @TranYear,@Mode = @Mode, @ImportTransTypeID = @ImportTransTypeID, @TransactionKey = @TransactionKey, @XML = @XML','SOF2100', 'Import_Excel_TienDoGiaoHang.xlsx',56, 'Date23', N'Ngày 23', 'Date23', 'DateTime', 0, 'BB',100, '') 
INSERT INTO A00065 (ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ExecSQL, ScreenID, TemplateFileName,OrderNum, ColID, ColName, ColNameEng, ColSQLDataType, IsObligated, DataCol, ColWidth, InputMask) VALUES ('ShipmentStatus',N'Tiến độ giao hàng','ShipmentStatus','EXEC SOP2109 @DivisionID = @DivisionID, @UserID = @UserID, @TranMonth = @TranMonth, @TranYear = @TranYear,@Mode = @Mode, @ImportTransTypeID = @ImportTransTypeID, @TransactionKey = @TransactionKey, @XML = @XML','SOF2100', 'Import_Excel_TienDoGiaoHang.xlsx',57, 'Quantity23', N'Giá trị 23', 'Quantity23', 'DECIMAL(28,8)', 0, 'BC',100, '') 
INSERT INTO A00065 (ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ExecSQL, ScreenID, TemplateFileName,OrderNum, ColID, ColName, ColNameEng, ColSQLDataType, IsObligated, DataCol, ColWidth, InputMask) VALUES ('ShipmentStatus',N'Tiến độ giao hàng','ShipmentStatus','EXEC SOP2109 @DivisionID = @DivisionID, @UserID = @UserID, @TranMonth = @TranMonth, @TranYear = @TranYear,@Mode = @Mode, @ImportTransTypeID = @ImportTransTypeID, @TransactionKey = @TransactionKey, @XML = @XML','SOF2100', 'Import_Excel_TienDoGiaoHang.xlsx',58, 'Date24', N'Ngày 24', 'Date24', 'DateTime', 0, 'BD',100, '') 
INSERT INTO A00065 (ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ExecSQL, ScreenID, TemplateFileName,OrderNum, ColID, ColName, ColNameEng, ColSQLDataType, IsObligated, DataCol, ColWidth, InputMask) VALUES ('ShipmentStatus',N'Tiến độ giao hàng','ShipmentStatus','EXEC SOP2109 @DivisionID = @DivisionID, @UserID = @UserID, @TranMonth = @TranMonth, @TranYear = @TranYear,@Mode = @Mode, @ImportTransTypeID = @ImportTransTypeID, @TransactionKey = @TransactionKey, @XML = @XML','SOF2100', 'Import_Excel_TienDoGiaoHang.xlsx',59, 'Quantity24', N'Giá trị 24', 'Quantity24', 'DECIMAL(28,8)', 0, 'BE',100, '') 
INSERT INTO A00065 (ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ExecSQL, ScreenID, TemplateFileName,OrderNum, ColID, ColName, ColNameEng, ColSQLDataType, IsObligated, DataCol, ColWidth, InputMask) VALUES ('ShipmentStatus',N'Tiến độ giao hàng','ShipmentStatus','EXEC SOP2109 @DivisionID = @DivisionID, @UserID = @UserID, @TranMonth = @TranMonth, @TranYear = @TranYear,@Mode = @Mode, @ImportTransTypeID = @ImportTransTypeID, @TransactionKey = @TransactionKey, @XML = @XML','SOF2100', 'Import_Excel_TienDoGiaoHang.xlsx',60, 'Date25', N'Ngày 25', 'Date25', 'DateTime', 0, 'BF',100, '') 
INSERT INTO A00065 (ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ExecSQL, ScreenID, TemplateFileName,OrderNum, ColID, ColName, ColNameEng, ColSQLDataType, IsObligated, DataCol, ColWidth, InputMask) VALUES ('ShipmentStatus',N'Tiến độ giao hàng','ShipmentStatus','EXEC SOP2109 @DivisionID = @DivisionID, @UserID = @UserID, @TranMonth = @TranMonth, @TranYear = @TranYear,@Mode = @Mode, @ImportTransTypeID = @ImportTransTypeID, @TransactionKey = @TransactionKey, @XML = @XML','SOF2100', 'Import_Excel_TienDoGiaoHang.xlsx',61, 'Quantity25', N'Giá trị 25', 'Quantity25', 'DECIMAL(28,8)', 0, 'BG',100, '') 
INSERT INTO A00065 (ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ExecSQL, ScreenID, TemplateFileName,OrderNum, ColID, ColName, ColNameEng, ColSQLDataType, IsObligated, DataCol, ColWidth, InputMask) VALUES ('ShipmentStatus',N'Tiến độ giao hàng','ShipmentStatus','EXEC SOP2109 @DivisionID = @DivisionID, @UserID = @UserID, @TranMonth = @TranMonth, @TranYear = @TranYear,@Mode = @Mode, @ImportTransTypeID = @ImportTransTypeID, @TransactionKey = @TransactionKey, @XML = @XML','SOF2100', 'Import_Excel_TienDoGiaoHang.xlsx',62, 'Date26', N'Ngày 26', 'Date26', 'DateTime', 0, 'BH',100, '') 
INSERT INTO A00065 (ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ExecSQL, ScreenID, TemplateFileName,OrderNum, ColID, ColName, ColNameEng, ColSQLDataType, IsObligated, DataCol, ColWidth, InputMask) VALUES ('ShipmentStatus',N'Tiến độ giao hàng','ShipmentStatus','EXEC SOP2109 @DivisionID = @DivisionID, @UserID = @UserID, @TranMonth = @TranMonth, @TranYear = @TranYear,@Mode = @Mode, @ImportTransTypeID = @ImportTransTypeID, @TransactionKey = @TransactionKey, @XML = @XML','SOF2100', 'Import_Excel_TienDoGiaoHang.xlsx',63, 'Quantity26', N'Giá trị 26', 'Quantity26', 'DECIMAL(28,8)', 0, 'BI',100, '') 
INSERT INTO A00065 (ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ExecSQL, ScreenID, TemplateFileName,OrderNum, ColID, ColName, ColNameEng, ColSQLDataType, IsObligated, DataCol, ColWidth, InputMask) VALUES ('ShipmentStatus',N'Tiến độ giao hàng','ShipmentStatus','EXEC SOP2109 @DivisionID = @DivisionID, @UserID = @UserID, @TranMonth = @TranMonth, @TranYear = @TranYear,@Mode = @Mode, @ImportTransTypeID = @ImportTransTypeID, @TransactionKey = @TransactionKey, @XML = @XML','SOF2100', 'Import_Excel_TienDoGiaoHang.xlsx',64, 'Date27', N'Ngày 27', 'Date27', 'DateTime', 0, 'BJ',100, '') 
INSERT INTO A00065 (ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ExecSQL, ScreenID, TemplateFileName,OrderNum, ColID, ColName, ColNameEng, ColSQLDataType, IsObligated, DataCol, ColWidth, InputMask) VALUES ('ShipmentStatus',N'Tiến độ giao hàng','ShipmentStatus','EXEC SOP2109 @DivisionID = @DivisionID, @UserID = @UserID, @TranMonth = @TranMonth, @TranYear = @TranYear,@Mode = @Mode, @ImportTransTypeID = @ImportTransTypeID, @TransactionKey = @TransactionKey, @XML = @XML','SOF2100', 'Import_Excel_TienDoGiaoHang.xlsx',65, 'Quantity27', N'Giá trị 27', 'Quantity27', 'DECIMAL(28,8)', 0, 'BK',100, '') 
INSERT INTO A00065 (ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ExecSQL, ScreenID, TemplateFileName,OrderNum, ColID, ColName, ColNameEng, ColSQLDataType, IsObligated, DataCol, ColWidth, InputMask) VALUES ('ShipmentStatus',N'Tiến độ giao hàng','ShipmentStatus','EXEC SOP2109 @DivisionID = @DivisionID, @UserID = @UserID, @TranMonth = @TranMonth, @TranYear = @TranYear,@Mode = @Mode, @ImportTransTypeID = @ImportTransTypeID, @TransactionKey = @TransactionKey, @XML = @XML','SOF2100', 'Import_Excel_TienDoGiaoHang.xlsx',66, 'Date28', N'Ngày 28', 'Date28', 'DateTime', 0, 'BL',100, '') 
INSERT INTO A00065 (ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ExecSQL, ScreenID, TemplateFileName,OrderNum, ColID, ColName, ColNameEng, ColSQLDataType, IsObligated, DataCol, ColWidth, InputMask) VALUES ('ShipmentStatus',N'Tiến độ giao hàng','ShipmentStatus','EXEC SOP2109 @DivisionID = @DivisionID, @UserID = @UserID, @TranMonth = @TranMonth, @TranYear = @TranYear,@Mode = @Mode, @ImportTransTypeID = @ImportTransTypeID, @TransactionKey = @TransactionKey, @XML = @XML','SOF2100', 'Import_Excel_TienDoGiaoHang.xlsx',67, 'Quantity28', N'Giá trị 28', 'Quantity28', 'DECIMAL(28,8)', 0, 'BM',100, '') 
INSERT INTO A00065 (ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ExecSQL, ScreenID, TemplateFileName,OrderNum, ColID, ColName, ColNameEng, ColSQLDataType, IsObligated, DataCol, ColWidth, InputMask) VALUES ('ShipmentStatus',N'Tiến độ giao hàng','ShipmentStatus','EXEC SOP2109 @DivisionID = @DivisionID, @UserID = @UserID, @TranMonth = @TranMonth, @TranYear = @TranYear,@Mode = @Mode, @ImportTransTypeID = @ImportTransTypeID, @TransactionKey = @TransactionKey, @XML = @XML','SOF2100', 'Import_Excel_TienDoGiaoHang.xlsx',68, 'Date29', N'Ngày 29', 'Date29', 'DateTime', 0, 'BN',100, '') 
INSERT INTO A00065 (ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ExecSQL, ScreenID, TemplateFileName,OrderNum, ColID, ColName, ColNameEng, ColSQLDataType, IsObligated, DataCol, ColWidth, InputMask) VALUES ('ShipmentStatus',N'Tiến độ giao hàng','ShipmentStatus','EXEC SOP2109 @DivisionID = @DivisionID, @UserID = @UserID, @TranMonth = @TranMonth, @TranYear = @TranYear,@Mode = @Mode, @ImportTransTypeID = @ImportTransTypeID, @TransactionKey = @TransactionKey, @XML = @XML','SOF2100', 'Import_Excel_TienDoGiaoHang.xlsx',69, 'Quantity29', N'Giá trị 29', 'Quantity29', 'DECIMAL(28,8)', 0, 'BO',100, '') 
INSERT INTO A00065 (ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ExecSQL, ScreenID, TemplateFileName,OrderNum, ColID, ColName, ColNameEng, ColSQLDataType, IsObligated, DataCol, ColWidth, InputMask) VALUES ('ShipmentStatus',N'Tiến độ giao hàng','ShipmentStatus','EXEC SOP2109 @DivisionID = @DivisionID, @UserID = @UserID, @TranMonth = @TranMonth, @TranYear = @TranYear,@Mode = @Mode, @ImportTransTypeID = @ImportTransTypeID, @TransactionKey = @TransactionKey, @XML = @XML','SOF2100', 'Import_Excel_TienDoGiaoHang.xlsx',70, 'Date30', N'Ngày 30', 'Date30', 'DateTime', 0, 'BP',100, '') 
INSERT INTO A00065 (ImportTransTypeID, ImportTransTypeName, ImportTransTypeNameEng, ExecSQL, ScreenID, TemplateFileName,OrderNum, ColID, ColName, ColNameEng, ColSQLDataType, IsObligated, DataCol, ColWidth, InputMask) VALUES ('ShipmentStatus',N'Tiến độ giao hàng','ShipmentStatus','EXEC SOP2109 @DivisionID = @DivisionID, @UserID = @UserID, @TranMonth = @TranMonth, @TranYear = @TranYear,@Mode = @Mode, @ImportTransTypeID = @ImportTransTypeID, @TransactionKey = @TransactionKey, @XML = @XML','SOF2100', 'Import_Excel_TienDoGiaoHang.xlsx',71, 'Quantity30', N'Giá trị 30', 'Quantity30', 'DECIMAL(28,8)', 0, 'BQ',100, '') 
IF NOT EXISTS (SELECT TOP 1 1 FROM A01065 WHERE ImportTemplateID = 'ShipmentStatus')
exec sp_executesql N'
      INSERT INTO A01065(
      ImportTemplateID,
      ImportTemplateName,
      ImportTransTypeID,
      DefaultSheet,
      AnchorCol,
      StartRow,
      DataFolder,
      DefaultFileName,
      Disabled,
      CreateUserID,
      CreateDate,
      LastModifyUserID,
      LastModifyDate
      ) VALUES (
      @ImportTemplateID,
      @ImportTemplateName,
      @ImportTransTypeID,
      @DefaultSheet,
      @AnchorCol,
      @StartRow,
      @DataFolder,
      @DefaultFileName,
      @Disabled,
      ''ASOFTADMIN'',
      GETDATE(),
      ''ASOFTADMIN'',
      GETDATE()
      )
    ',N'@ImportTemplateID nvarchar(50),@ImportTemplateName nvarchar(50),@ImportTransTypeID nvarchar(50),@DefaultSheet nvarchar(4),@AnchorCol nvarchar(1),@StartRow int,@DataFolder nvarchar(10),@DefaultFileName nvarchar(50),@Disabled tinyint',@ImportTemplateID=N'ShipmentStatus',@ImportTemplateName=N'Tiến độ giao hàng',@ImportTransTypeID=N'ShipmentStatus',@DefaultSheet=N'Data',@AnchorCol=N'A',@StartRow=10,@DataFolder=N'C:\IMPORTS',@DefaultFileName=N'Import_Excel_TienDoGiaoHang.xlsx',@Disabled=0
