DECLARE @DivisionID VARCHAR(50),
		@Cur CURSOR

SET @Cur = CURSOR SCROLL KEYSET FOR
SELECT DivisionID FROM AT0001 WITH (NOLOCK)
OPEN @Cur
FETCH NEXT FROM @Cur INTO @DivisionID
WHILE @@FETCH_STATUS = 0
BEGIN
	IF NOT EXISTS (SELECT TOP 1 1 FROM OOT0060 WHERE DivisionID = @DivisionID)
		INSERT INTO OOT0060 (DivisionID) VALUES (@DivisionID)
	FETCH NEXT FROM @Cur INTO @DivisionID
END
CLOSE @Cur