-- <Summary>
---- Data Dữ liệu ngầm bảng định nghĩa tham số
-- <History>
---- Create on 19/04/2017 by Thị Phượng
---- Modified on ... by ...
---- <Example> 

DECLARE @DivisionID VARCHAR(50) =  (SELECT TOP 1 DivisionID FROM CRMT00000)

IF NOT EXISTS(SELECT TOP 1 1 FROM CRMT00001 WHERE TypeID =N'C01')
	INSERT INTO CRMT00001(DivisionID, TypeID, SystemName, UserName, IsUsed, UserNameE, SystemNameE, TransactionID)
	VALUES (@DivisionID, N'C01', N'Tham số 01', N'Tham số 01', 0, N'Parameter 01', N'Parameter 01', N'Customer')
IF NOT EXISTS(SELECT TOP 1 1 FROM CRMT00001 WHERE TypeID =N'C02')
	INSERT INTO CRMT00001(DivisionID, TypeID, SystemName, UserName, IsUsed, UserNameE, SystemNameE, TransactionID)
	VALUES (@DivisionID, N'C02', N'Tham số 02', N'Tham số 02', 0, N'Parameter 02', N'Parameter 02', N'Customer')
IF NOT EXISTS(SELECT TOP 1 1 FROM CRMT00001 WHERE TypeID =N'C03')
	INSERT INTO CRMT00001(DivisionID, TypeID, SystemName, UserName, IsUsed, UserNameE, SystemNameE, TransactionID)
	VALUES (@DivisionID, N'C03', N'Tham số 03', N'Tham số 03', 0, N'Parameter 03', N'Parameter 03', N'Customer')
IF NOT EXISTS(SELECT TOP 1 1 FROM CRMT00001 WHERE TypeID =N'C04')
	INSERT INTO CRMT00001(DivisionID, TypeID, SystemName, UserName, IsUsed, UserNameE, SystemNameE, TransactionID)
	VALUES (@DivisionID, N'C04', N'Tham số 04', N'Tham số 04', 0, N'Parameter 04', N'Parameter 04', N'Customer')
IF NOT EXISTS(SELECT TOP 1 1 FROM CRMT00001 WHERE TypeID =N'C05')
	INSERT INTO CRMT00001(DivisionID, TypeID, SystemName, UserName, IsUsed, UserNameE, SystemNameE, TransactionID)
	VALUES (@DivisionID, N'C05', N'Tham số 05', N'Tham số 05', 0, N'Parameter 05', N'Parameter 05', N'Customer')
IF NOT EXISTS(SELECT TOP 1 1 FROM CRMT00001 WHERE TypeID =N'C06')
	INSERT INTO CRMT00001(DivisionID, TypeID, SystemName, UserName, IsUsed, UserNameE, SystemNameE, TransactionID)
	VALUES (@DivisionID, N'C06', N'Tham số 06', N'Tham số 06', 0, N'Parameter 06', N'Parameter 06', N'Customer')
IF NOT EXISTS(SELECT TOP 1 1 FROM CRMT00001 WHERE TypeID =N'C07')
	INSERT INTO CRMT00001(DivisionID, TypeID, SystemName, UserName, IsUsed, UserNameE, SystemNameE, TransactionID)
	VALUES (@DivisionID, N'C07', N'Tham số 07', N'Tham số 07', 0, N'Parameter 07', N'Parameter 07', N'Customer')
IF NOT EXISTS(SELECT TOP 1 1 FROM CRMT00001 WHERE TypeID =N'C08')
	INSERT INTO CRMT00001(DivisionID, TypeID, SystemName, UserName, IsUsed, UserNameE, SystemNameE, TransactionID)
	VALUES (@DivisionID, N'C08', N'Tham số 08', N'Tham số 08', 0, N'Parameter 08', N'Parameter 08', N'Customer')
IF NOT EXISTS(SELECT TOP 1 1 FROM CRMT00001 WHERE TypeID =N'C09')
	INSERT INTO CRMT00001(DivisionID, TypeID, SystemName, UserName, IsUsed, UserNameE, SystemNameE, TransactionID)
	VALUES (@DivisionID, N'C09', N'Tham số 09', N'Tham số 09', 0, N'Parameter 09', N'Parameter 09', N'Customer')
IF NOT EXISTS(SELECT TOP 1 1 FROM CRMT00001 WHERE TypeID =N'C10')
	INSERT INTO CRMT00001(DivisionID, TypeID, SystemName, UserName, IsUsed, UserNameE, SystemNameE, TransactionID)
	VALUES (@DivisionID, N'C10', N'Tham số 10', N'Tham số 10', 0, N'Parameter 10', N'Parameter 10', N'Customer')
IF NOT EXISTS(SELECT TOP 1 1 FROM CRMT00001 WHERE TypeID =N'C11')
	INSERT INTO CRMT00001(DivisionID, TypeID, SystemName, UserName, IsUsed, UserNameE, SystemNameE, TransactionID)
	VALUES (@DivisionID, N'C11', N'Tham số 11', N'Tham số 11', 0, N'Parameter 11', N'Parameter 11', N'Customer')
IF NOT EXISTS(SELECT TOP 1 1 FROM CRMT00001 WHERE TypeID =N'C12')
	INSERT INTO CRMT00001(DivisionID, TypeID, SystemName, UserName, IsUsed, UserNameE, SystemNameE, TransactionID)
	VALUES (@DivisionID, N'C12', N'Tham số 12', N'Tham số 12', 0, N'Parameter 12', N'Parameter 12', N'Customer')
IF NOT EXISTS(SELECT TOP 1 1 FROM CRMT00001 WHERE TypeID =N'C13')
	INSERT INTO CRMT00001(DivisionID, TypeID, SystemName, UserName, IsUsed, UserNameE, SystemNameE, TransactionID)
	VALUES (@DivisionID, N'C13', N'Tham số 13', N'Tham số 13', 0, N'Parameter 13', N'Parameter 13', N'Customer')
IF NOT EXISTS(SELECT TOP 1 1 FROM CRMT00001 WHERE TypeID =N'C14')
	INSERT INTO CRMT00001(DivisionID, TypeID, SystemName, UserName, IsUsed, UserNameE, SystemNameE, TransactionID)
	VALUES (@DivisionID, N'C14', N'Tham số 14', N'Tham số 14', 0, N'Parameter 14', N'Parameter 14', N'Customer')
IF NOT EXISTS(SELECT TOP 1 1 FROM CRMT00001 WHERE TypeID =N'C15')
	INSERT INTO CRMT00001(DivisionID, TypeID, SystemName, UserName, IsUsed, UserNameE, SystemNameE, TransactionID)
	VALUES (@DivisionID, N'C15', N'Tham số 15', N'Tham số 15', 0, N'Parameter 15', N'Parameter 15', N'Customer')
IF NOT EXISTS(SELECT TOP 1 1 FROM CRMT00001 WHERE TypeID =N'C16')
	INSERT INTO CRMT00001(DivisionID, TypeID, SystemName, UserName, IsUsed, UserNameE, SystemNameE, TransactionID)
	VALUES (@DivisionID, N'C16', N'Tham số 16', N'Tham số 16', 0, N'Parameter 16', N'Parameter 16', N'Customer')
IF NOT EXISTS(SELECT TOP 1 1 FROM CRMT00001 WHERE TypeID =N'C17')
	INSERT INTO CRMT00001(DivisionID, TypeID, SystemName, UserName, IsUsed, UserNameE, SystemNameE, TransactionID)
	VALUES (@DivisionID, N'C17', N'Tham số 17', N'Tham số 17', 0, N'Parameter 17', N'Parameter 17', N'Customer')
IF NOT EXISTS(SELECT TOP 1 1 FROM CRMT00001 WHERE TypeID =N'C18')
	INSERT INTO CRMT00001(DivisionID, TypeID, SystemName, UserName, IsUsed, UserNameE, SystemNameE, TransactionID)
	VALUES (@DivisionID, N'C18', N'Tham số 18', N'Tham số 18', 0, N'Parameter 18', N'Parameter 18', N'Customer')
IF NOT EXISTS(SELECT TOP 1 1 FROM CRMT00001 WHERE TypeID =N'C19')
	INSERT INTO CRMT00001(DivisionID, TypeID, SystemName, UserName, IsUsed, UserNameE, SystemNameE, TransactionID)
	VALUES (@DivisionID, N'C19', N'Tham số 19', N'Tham số 19', 0, N'Parameter 19', N'Parameter 19', N'Customer')
IF NOT EXISTS(SELECT TOP 1 1 FROM CRMT00001 WHERE TypeID =N'C20')
	INSERT INTO CRMT00001(DivisionID, TypeID, SystemName, UserName, IsUsed, UserNameE, SystemNameE, TransactionID)
	VALUES (@DivisionID, N'C20', N'Tham số 20', N'Tham số 20', 0, N'Parameter 20', N'Parameter 20', N'Customer')