IF NOT EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[A00008]') AND TYPE IN (N'U'))
BEGIN
     CREATE TABLE [dbo].[A00008]
     (
      [APK] UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL,
      [DivisionID] VARCHAR(50) NULL,
	  [ID] VARCHAR(50) NOT NULL,
	  [Name] VARCHAR(50) NOT NULL,
	  [ModuleID] VARCHAR(50) NOT NULL,
      [ScreenID] VARCHAR(50) NOT NULL,
      [KeyLanguage] NVARCHAR(4000) NULL,
      [Url] NVARCHAR(4000) NULL,
      [ParentID] NVARCHAR(4000) NULL,
      [Level] INT NOT NULL,
      [Enable] BIT DEFAULT (1) NOT NULL,
	  [Order] INT NOT NULL,
	  [Visible] BIT NOT NULL,
      [CreateUserID] VARCHAR(50) NULL,
      [CreateDate] DATETIME NULL,
      [LastModifyUserID] VARCHAR(50) NULL,
      [LastModifyDate] DATETIME NULL
    CONSTRAINT [PK_A00008] PRIMARY KEY CLUSTERED
      (
      [ID]
      )
WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
     )
 ON [PRIMARY]
END


