---- Create by Khâu Vĩnh Tâm on 9/25/2020 11:15:05 AM
---- Thông tin đăng nhập

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[AT0013]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[AT0013]
(
  [APK] UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL,
  [APKMaster] UNIQUEIDENTIFIER NULL,
  [DivisionID] VARCHAR(50) NULL,
  [UserID] VARCHAR(50) NULL,
  [UserName] NVARCHAR(250) NULL,
  [Type] INT NULL,
  [ServerTime] DATETIME2 NULL,
  [ClientTime] DATETIME2 NULL,
  [Status] VARCHAR(50) NULL,
  [IPLogin] VARCHAR(50) NULL,
  [BrowserName] NVARCHAR(250) NULL,
  [BrowserVersion] VARCHAR(50) NULL,
  [Note] NVARCHAR(MAX) NULL
CONSTRAINT [PK_AT0013] PRIMARY KEY CLUSTERED
(
  [APK]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END