---- Create by Cao Thị Phượng on 2/21/2017 10:08:43 AM
---- Email và đối tượng liên quan
----- MODIFY by Tấn Lộc - 26/09/2020 - Thay đổi cấu trúc bảng CMNT90051_REL
IF EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[CMNT90051]') AND TYPE IN (N'U'))
	AND NOT EXISTS (SELECT * FROM syscolumns col INNER JOIN sysobjects tab 
	   ON col.id = tab.id WHERE tab.name = 'CMNT90051_REL' AND col.name = 'APKRelBusiness')
BEGIN
	DROP TABLE CMNT90051_REL
END

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[CMNT90051_REL]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[CMNT90051_REL]
(
  [APK] UNIQUEIDENTIFIER DEFAULT newid() NOT NULL,
  [DivisionID] VARCHAR(50) NULL,
  [APKEmail] VARCHAR(250) NULL,
  [APKRelBusiness] VARCHAR(250) NULL,
  [RelTableID] VARCHAR(250) NULL,
  [TypeOfEmail] VARCHAR(50) NULL,
  [CreateDate] DATETIME NULL,
  [CreateUserID] VARCHAR(50) NULL,
  [LastModifyDate] DATETIME NULL,
  [LastModifyUserID] VARCHAR(50) NULL
CONSTRAINT [PK_CMNT90051_REL] PRIMARY KEY CLUSTERED
(
  [APK]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END