---- Create by Kiều Nga on 11/04/2020
---- Dữ liệu Người được quyền kế thừa

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[CMNT0030]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[CMNT0030]
(
  [APK] UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL,
  [DivisionID] VARCHAR(50) NULL,
  [APKMaster] UNIQUEIDENTIFIER NULL,
  [RelatedToID] VARCHAR(50) NULL,
  [TableID] VARCHAR(50) NULL,
  [UserID] VARCHAR(50) NULL,
  [Type] TINYINT DEFAULT 0 NULL,
  [CreateDate] DATETIME NULL,
  [CreateUserID] VARCHAR(50) NULL,
  [RelatedToTypeID] INT NULL
CONSTRAINT [PK_CMNT0030] PRIMARY KEY CLUSTERED
(
  [APK]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END
