---- Create by Dũng DV on 15/11/2019
---- Danh mục kế hoạch bán hàng
 
IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[SOT2070]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[SOT2070]
(
  [APK] UNIQUEIDENTIFIER DEFAULT newid() NOT NULL,	
  [DivisionID] VARCHAR(50) NOT NULL,
  [VoucherNo] VARCHAR(50) NOT NULL,
  [VoucherDate] DATETIME NULL,
  [ObjectID] VARCHAR(50) NOT NULL,
  [Type] TINYINT NOT NULL,
  [YearPlan] INT NOT NULL,
  
  [DeleteFlg] TINYINT DEFAULT (0) NULL,
  [IsCommon] TINYINT DEFAULT (0) NULL,
  [Disabled] TINYINT DEFAULT (0) NULL,
 
  [CreateUserID] VARCHAR(50) NULL,
  [CreateDate] DATETIME DEFAULT GETDATE() NOT NULL,
  [LastModifyDate] DATETIME NULL,
  [LastModifyUserID] VARCHAR(50) NULL
CONSTRAINT [PK_SOT2070] PRIMARY KEY CLUSTERED
(
  [APK],
  [DivisionID],
  [VoucherNo]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END

