---- Create by Dũng DV on 14/09/2019
---- Thông tin linh kiện thay thế/dịch vụ
IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[SOT2071]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[SOT2071]
(
  [APK] UNIQUEIDENTIFIER DEFAULT newid() NOT NULL,
  [APKMaster] UNIQUEIDENTIFIER NOT NULL,
  [DivisionID] VARCHAR(50) NOT NULL,
  [InventoryID] VARCHAR(50) NULL,
  [InventoryName] NVARCHAR(250) NULL,
  [UnitID] VARCHAR(50) NULL,
  [UnitPrice] DECIMAL(28,8) NULL,
  [Quantity1] DECIMAL(28,8) NULL,
  [Quantity2] DECIMAL(28,8) NULL,
  [Quantity3] DECIMAL(28,8) NULL,
  [Quantity4] DECIMAL(28,8) NULL,
  [Quantity5] DECIMAL(28,8) NULL,
  [Quantity6] DECIMAL(28,8) NULL,
  [Quantity7] DECIMAL(28,8) NULL,
  [Quantity8] DECIMAL(28,8) NULL,
  [Quantity9] DECIMAL(28,8) NULL,
  [Quantity10] DECIMAL(28,8) NULL,
  [Quantity11] DECIMAL(28,8) NULL,
  [Quantity12] DECIMAL(28,8) NULL,
  [S01ID] VARCHAR(25) NULL,
  [S02ID] VARCHAR(25) NULL,
  [S03ID] VARCHAR(25) NULL,
  [S04ID] VARCHAR(25) NULL,
  [S05ID] VARCHAR(25) NULL,
  [S06ID] VARCHAR(25) NULL,
  [S07ID] VARCHAR(25) NULL,
  [S08ID] VARCHAR(25) NULL,
  [S09ID] VARCHAR(25) NULL,
  [S10ID] VARCHAR(25) NULL,
  [S11ID] VARCHAR(25) NULL,
  [S12ID] VARCHAR(25) NULL,
  [S13ID] VARCHAR(25) NULL,
  [S14ID] VARCHAR(25) NULL,
  [S15ID] VARCHAR(25) NULL,
  [S16ID] VARCHAR(25) NULL,
  [S17ID] VARCHAR(25) NULL,
  [S18ID] VARCHAR(25) NULL,
  [S19ID] VARCHAR(25) NULL,
  [S20ID] VARCHAR(25) NULL,
  [Notes] NVARCHAR(250)  NULL,  
  
  [CreateUserID] VARCHAR(50) NULL,
  [CreateDate] DATETIME DEFAULT GETDATE() NULL,
  [LastModifyDate] DATETIME NULL,
  [LastModifyUserID] VARCHAR(50) NULL
CONSTRAINT [PK_SOT2071] PRIMARY KEY CLUSTERED
(
  [APK]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END

