---- Create by Phan Hải Long on 9/13/2017 1:42:46 PM
---- Danh mục khóa đào tạo

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[HRMT1050]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[HRMT1050]
(
  [APK] UNIQUEIDENTIFIER DEFAULT newid() NOT NULL,
  [DivisionID] NVARCHAR(50) NOT NULL,
  [TrainingCourseID] NVARCHAR(50) NOT NULL,
  [TrainingFieldID] NVARCHAR(50) NULL,
  [TrainingType] NVARCHAR(50) NULL,
  [ObjectID] NVARCHAR(50) NULL,
  [Address] NVARCHAR(500) NULL,
  [Description] NVARCHAR(1000) NULL,
  [Disabled] TINYINT DEFAULT (0) NULL,
  [IsCommon] TINYINT DEFAULT (0) NULL,
  [CreateUserID] NVARCHAR(50) NULL,
  [CreateDate] DATETIME NULL,
  [LastModifyUserID] NVARCHAR(50) NULL,
  [LastModifyDate] DATETIME NULL
CONSTRAINT [PK_HRMT1050] PRIMARY KEY CLUSTERED
(
  [DivisionID],
  [TrainingCourseID]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END
--Thu Hà Create 16/10/2023 --Bổ sung cột DeleteFlg
IF EXISTS (SELECT TOP 1 1 FROM sysobjects WHERE [name]='HRMT1050' AND xtype='U')
BEGIN
	IF NOT EXISTS (SELECT TOP 1 1 FROM syscolumns col INNER JOIN sysobjects tab
	ON col.id=tab.id WHERE tab.name='HRMT1050' and col.name='DeleteFlg')
	ALTER TABLE HRMT1050 ADD DeleteFlg TINYINT DEFAULT 0 NULL
END

