---- Create by Phan Hải Long on 9/15/2017 8:20:21 AM
---- Kế hoạch đào tạo định kỳ (Master)

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[HRMT2070]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[HRMT2070]
(
  [APK] UNIQUEIDENTIFIER DEFAULT newid() NULL,
  [DivisionID] NVARCHAR(50) NOT NULL,
  [TrainingPlanID] NVARCHAR(50) NOT NULL,
  [AssignedToUserID] NVARCHAR(50) NULL,
  [Description] NVARCHAR(250) NULL,
  [CreateUserID] NVARCHAR(50) NULL,
  [CreateDate] DATETIME NULL,
  [LastModifyUserID] NVARCHAR(50) NULL,
  [LastModifyDate] DATETIME NULL
CONSTRAINT [PK_HRMT2070] PRIMARY KEY CLUSTERED
(
  [DivisionID],
  [TrainingPlanID]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END
--- 17/10/2023 - Minh Trí: Bổ sung cột DeleteFlg
IF EXISTS (SELECT TOP 1 1 FROM sysobjects WHERE NAME='HRMT2070' AND xtype='U')
	BEGIN
	IF NOT EXISTS (SELECT TOP 1 1 FROM syscolumns col INNER JOIN sysobjects tab 
		ON col.id=tab.id WHERE tab.name='HRMT2070' AND col.name='DeleteFlg')
		ALTER TABLE HRMT2070 ADD DeleteFlg TINYINT DEFAULT (0) NULL
	END
