---- Create by Nguyễn Hoàng Bảo Thy on 7/17/2017 4:38:49 PM
---- Danh mục nguồn tuyển dụng

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[HRMT1000]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[HRMT1000]
(
  [APK] UNIQUEIDENTIFIER DEFAULT newid() NOT NULL,
  [DivisionID] VARCHAR(50) NOT NULL,
  [ResourceID] VARCHAR(50) NOT NULL,
  [ResourceName] NVARCHAR(1000) NULL,
  [Note] NVARCHAR(1000) NULL,
  [Disabled] TINYINT DEFAULT (0) NULL,
  [IsCommon] TINYINT DEFAULT (0) NULL,
  [CreateUserID] VARCHAR(50) NULL,
  [CreateDate] DATETIME NULL,
  [LastModifyUserID] VARCHAR(50) NULL,
  [LastModifyDate] DATETIME NULL
CONSTRAINT [PK_HRMT1000] PRIMARY KEY CLUSTERED
(
  [DivisionID],
  [ResourceID]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END

--- 12/10/2023 - Phương Thảo: Bổ sung cột DeleteFlg
IF EXISTS (SELECT TOP 1 1 FROM sysobjects WHERE NAME='HRMT1000' AND xtype='U')
	BEGIN
	IF NOT EXISTS (SELECT TOP 1 1 FROM syscolumns col INNER JOIN sysobjects tab 
		ON col.id=tab.id WHERE tab.name='HRMT1000' AND col.name='DeleteFlg')
		ALTER TABLE HRMT1000 ADD DeleteFlg TINYINT DEFAULT (0) NULL
	END
