---- Create by Thái Huỳnh Khả Vi on 12/7/2017 5:31:00 PM
---- Thiết lập mã tăng tự động cho module tuyển dụng

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[HRMT0010]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[HRMT0010]
(
  [APK] UNIQUEIDENTIFIER DEFAULT newid() NULL,
  [DivisionID] VARCHAR(50) NOT NULL,
  [VoucherTypeID] VARCHAR(50) NOT NULL,
  [GroupID] VARCHAR(50) NULL
CONSTRAINT [PK_HRMT0010] PRIMARY KEY CLUSTERED
(
  [DivisionID],  [VoucherTypeID]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END


