---- Create by Phan Hải Long on 9/22/2017 1:45:02 PM
---- Ghi nhận chi phí (detail)

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[HRMT2131]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[HRMT2131]
(
  [APK] UNIQUEIDENTIFIER DEFAULT newid() NULL,
  [DivisionID] NVARCHAR(50) NOT NULL,
  [TransactionID] NVARCHAR(50) NOT NULL,
  [TrainingCostID] NVARCHAR(50) NOT NULL,
  [EmployeeID] NVARCHAR(50) NULL,  
  [DepartmentID] NVARCHAR(50) NULL,  
  [CostAmount] DECIMAL(28,8) NULL,      
  [Notes] NVARCHAR(250) NULL,
  [Orders] TINYINT NULL,
  [InheritID] NVARCHAR(50) NULL,  
  [InheritTransactionID] NVARCHAR(50) NULL
CONSTRAINT [PK_HRMT2131] PRIMARY KEY CLUSTERED
(
  [DivisionID],
  [TransactionID],
  [TrainingCostID]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END
