---- Create by Nguyễn Hoàng Bảo Thy on 8/14/2017 2:03:50 PM
---- Đợt tuyển dụng: Vòng phỏng vấn

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[HRMT2021]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[HRMT2021]
(
  [APK] UNIQUEIDENTIFIER DEFAULT newid() NOT NULL,
  [DivisionID] VARCHAR(50) NOT NULL,
  [RecruitPeriodID] VARCHAR(50) NOT NULL,
  [InterviewLevel] INT NOT NULL,
  [InterviewTypeID] VARCHAR(50) NOT NULL,
  [InterviewAddress] NVARCHAR(1000) NULL,
  [DetailTypeID] VARCHAR(50) NULL,
  [CreateUserID] VARCHAR(50) NULL,
  [CreateDate] DATETIME NULL,
  [LastModifyUserID] VARCHAR(50) NULL,
  [LastModifyDate] DATETIME NULL
CONSTRAINT [PK_HRMT2021] PRIMARY KEY CLUSTERED
(
  [APK],
  [DivisionID]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END
