---- Create by Phan Hải Long on 9/15/2017 8:21:26 AM
---- Kế hoạch đào tạo định kỳ (Detail)

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[HRMT2071]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[HRMT2071]
(
  [APK] UNIQUEIDENTIFIER DEFAULT newid() NULL,
  [DivisionID] NVARCHAR(50) NOT NULL,
  [TransactionID] NVARCHAR(50) NOT NULL,
  [TrainingPlanID] NVARCHAR(50) NOT NULL,
  [IsAll] TINYINT DEFAULT (0) NULL,
  [DepartmentID] NVARCHAR(50) NULL,
  [TrainingFieldID] NVARCHAR(50) NULL,
  [StartDate] DATETIME NULL,
  [DurationPlan] INT NULL,
  [RepeatTypeID] NVARCHAR(50) NULL,
  [RepeatTime] TINYINT NULL,
  [Notes] NVARCHAR(250) NULL,
  [Orders] TINYINT NULL  
CONSTRAINT [PK_HRMT2071] PRIMARY KEY CLUSTERED
(
  [DivisionID],
  [TransactionID]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END