---- Create by Nguyễn Hoàng Bảo Thy on 8/21/2017 2:01:34 PM
---- Lịch phỏng vấn (detail)

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[HRMT2031]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[HRMT2031]
(
  [APK] UNIQUEIDENTIFIER DEFAULT newid() NOT NULL,
  [DivisionID] VARCHAR(50) NOT NULL,
  [InterviewScheduleID] VARCHAR(50) NOT NULL,
  [CandidateID] VARCHAR(50) NOT NULL,
  [InterviewDate] DATETIME NULL,
  [ConfirmID] TINYINT DEFAULT (0) NULL,
  [Notes] NVARCHAR(250) NULL
CONSTRAINT [PK_HRMT2031] PRIMARY KEY CLUSTERED
(
  [APK],
  [DivisionID]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END