---- Create by Nguyễn Hoàng Bảo Thy on 7/18/2017 2:10:23 PM
---- Danh mục hình thức phỏng vấn (Detail)

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[HRMT1011]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[HRMT1011]
(
  [APK] UNIQUEIDENTIFIER DEFAULT newid() NOT NULL,
  [DivisionID] VARCHAR(50) NOT NULL,
  [InterviewTypeID] VARCHAR(50) NOT NULL,
  [DutyID] VARCHAR(50) NOT NULL,
  [DetailTypeID] VARCHAR(50) NOT NULL,
  [Description] NVARCHAR(1000) NULL,
  [ResultFormat] TINYINT DEFAULT (0) NULL,
  [FromValue] DECIMAL(28,8) NULL,
  [ToValue] DECIMAL(28,8) NULL,
  [Notes] NVARCHAR(1000) NULL
CONSTRAINT [PK_HRMT1011] PRIMARY KEY CLUSTERED
(
  [APK],
  [DivisionID]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END