---- Create by Nguyễn Hoàng Bảo Thy on 7/20/2017 9:10:59 AM
---- Định biên tuyển dụng (detail)

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[HRMT1021]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[HRMT1021]
(
  [APK] UNIQUEIDENTIFIER DEFAULT newid() NOT NULL,
  [DivisionID] VARCHAR(50) NOT NULL,
  [BoundaryID] VARCHAR(50) NOT NULL,
  [DepartmentID] VARCHAR(50) NOT NULL,
  [DutyID] VARCHAR(50) NOT NULL,
  [QuantityBoundary] INT NULL,
  [Notes] NVARCHAR(250) NULL
CONSTRAINT [PK_HRMT1021] PRIMARY KEY CLUSTERED
(
  [APK],
  [DivisionID]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END