---- Create by Khâu Vĩnh Tâm on 8/15/2019 11:06:35 PM
---- Bảng quy định hệ số lương mềm

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[KPIT2030]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[KPIT2030]
(
  [APK] UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL,
  [DivisionID] VARCHAR(50) NULL,
  [TableID] VARCHAR(50) NULL,
  [TableName] NVARCHAR(250) NULL,
  [IsCommon] TINYINT DEFAULT 0 NULL,
  [Disabled] TINYINT DEFAULT 0 NULL,
  [DeleteFlg] TINYINT DEFAULT 0 NULL,
  [CreateUserID] VARCHAR(50) NULL,
  [CreateDate] DATETIME NULL,
  [LastModifyUserID] VARCHAR(50) NULL,
  [LastModifyDate] DATETIME NULL
CONSTRAINT [PK_KPIT2030] PRIMARY KEY CLUSTERED
(
  [APK]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END