---- Create by Truong Lam on 03/09/2019
---- Chi tiết kỳ

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[KPIT2042]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[KPIT2042]
(
  [APK] UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL,
  [PeriodID] VARCHAR(50) NULL,
  [StartPeriod] DATETIME NULL,
  [EndPeriod] DATETIME NULL,
  [Lock] TINYINT NULL
CONSTRAINT [PK_KPIT2042] PRIMARY KEY CLUSTERED
(
  [APK]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END

-------------------- 08/10/2019 - Truong Lam: add Locked --------------------
IF NOT EXISTS (SELECT * FROM syscolumns col INNER JOIN sysobjects tab 
	   ON col.id = tab.id WHERE tab.name = 'KPIT2042' AND col.name = 'Locked')
BEGIN
	ALTER TABLE KPIT2042 ADD Locked TINYINT NULL
END