IF EXISTS (SELECT TOP 1 * FROM DBO.SYSOBJECTS WHERE name = N'S123' AND XTYPE IN (N'FN', N'IF', N'TF'))
DROP FUNCTION [dbo].[S123]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE FUNCTION S123
( 
	@DivisionID VARCHAR(50),
	@VoucherIDTypeID VARCHAR(50),
	@TranMonth INT,
	@TranYear INT
)
RETURNS @RtnValue TABLE 
(
    S1 NVARCHAR(50),
    S2 NVARCHAR(50),
    S3 NVARCHAR(50)
) 
AS
BEGIN
	DECLARE @S1 NVARCHAR(50) = '', @S2 NVARCHAR(50) = '', @S3 NVARCHAR(50) = '', @S1Type TINYINT, @S2Type TINYINT, @S3Type TINYINT
	
	SELECT @S1 = S1, @S2 = s2, @S3 = S3, @S1Type = S1Type, @S2Type = S2Type, @S3Type = S3Type FROM AT1007 
		WHERE DivisionID = @DivisionID AND VoucherTypeID = @VoucherIDTypeID
	
	IF @S1Type = 1 SET @S1 = (CASE WHEN @TranMonth < 10 THEN '0' + CONVERT(VARCHAR(1), @TranMonth) ELSE CONVERT(VARCHAR(2), @TranMonth) END)
	IF @S2Type = 1 SET @S2 = (CASE WHEN @TranMonth < 10 THEN '0' + CONVERT(VARCHAR(1), @TranMonth) ELSE CONVERT(VARCHAR(2), @TranMonth) END)
	IF @S3Type = 1 SET @S3 = (CASE WHEN @TranMonth < 10 THEN '0' + CONVERT(VARCHAR(1), @TranMonth) ELSE CONVERT(VARCHAR(2), @TranMonth) END)
	
	IF @S1Type = 2 SET @S1 = CONVERT(VARCHAR(4), @TranYear)
	IF @S2Type = 2 SET @S2 = CONVERT(VARCHAR(4), @TranYear)
	IF @S3Type = 2 SET @S3 = CONVERT(VARCHAR(4), @TranYear)
	
	IF @S1Type = 6 SET @S1 = RIGHT(CONVERT(VARCHAR(4), @TranYear), 2)
	IF @S2Type = 6 SET @S2 = RIGHT(CONVERT(VARCHAR(4), @TranYear), 2)
	IF @S3Type = 6 SET @S3 = RIGHT(CONVERT(VARCHAR(4), @TranYear), 2)
	
	INSERT INTO @RtnValue (S1, S2, S3) VALUES (@S1, @S2, @S3)
	
	RETURN
END
GO
SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO

