IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[MT0122]') AND TYPE IN (N'U'))
BEGIN
     CREATE TABLE [dbo].[MT0122]
     (
		[APK] UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL,
		[Quantity] DECIMAL(28,8) NULL,
		[DivisionID] VARCHAR(50) NULL,
		[VoucherID] VARCHAR(50) NULL,
		[MaterialID] VARCHAR(50) NULL,
		[WareHouseID] VARCHAR(50) NULL
	CONSTRAINT [PK_MT0122] PRIMARY KEY CLUSTERED
      (
		[APK]
      )
WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
		)
	ON [PRIMARY]
END
