IF NOT EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[MT0125]') AND TYPE IN (N'U'))
BEGIN
     CREATE TABLE [dbo].[MT0125]
     (
      [APK] UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL,
      [DivisionID] VARCHAR(50) NOT NULL,
      [CriteriaID] VARCHAR(50) NOT NULL,
      [PhaseID] VARCHAR(50) NOT NULL,
      [MachineID] NVARCHAR(50) NULL,
      [HourAvg] DECIMAL(28,8) NULL,
      [TCGCCoefficient] DECIMAL(28,8) NULL,
	  [HourCriteria] DECIMAL(28,8) NULL,
	  [QtyCriteria1h] DECIMAL(28,8) NULL,
	  [QtyCriteria8h] DECIMAL(28,8) NULL,
	  [QtyCriteria12h] DECIMAL(28,8) NULL,
	  [Notes] NVARCHAR(500)
    CONSTRAINT [PK_MT0125] PRIMARY KEY CLUSTERED
      (
	  [APK]
      )
WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
     )
 ON [PRIMARY]
END
