 
IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[MT0121]') AND TYPE IN (N'U'))
BEGIN
     CREATE TABLE [dbo].[MT0121]
     (
		[APK] UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL,
		[IsFinish] TINYINT DEFAULT (0) NULL,
		[TranMonth] INT NOT NULL,
		[TranYear] INT NOT NULL,
		[VoucherDate] DATETIME NULL,
		[CreateDate] DATETIME NULL,
		[LastModifyDate] DATETIME NULL,
		[DivisionID] VARCHAR(50) NULL,
		[VoucherID] VARCHAR(50) NOT NULL,
		[VoucherTypeID] VARCHAR(50) NULL,
		[VoucherNo] VARCHAR(50) NULL,
		[PlanID] VARCHAR(50) NULL,
		[PlanDetailID] VARCHAR(50) NULL,
		[CommandPersonID] VARCHAR(50) NULL,
		[EmployeeID] VARCHAR(50) NULL,
		[CreateUserID] VARCHAR(50) NULL,
		[LastModifyUserID] VARCHAR(50) NULL,
		[Description] NVARCHAR(500) NULL
	CONSTRAINT [PK_MT0121] PRIMARY KEY CLUSTERED
      (
		[VoucherID]
      )
WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
		)
	ON [PRIMARY]
END
