IF EXISTS (SELECT TOP 1 1 FROM DBO.SYSOBJECTS WHERE ID = OBJECT_ID(N'[DBO].[CP0036]') AND  OBJECTPROPERTY(ID, N'IsProcedure') = 1)			
DROP PROCEDURE [DBO].[CP0036]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


-- <Summary>
---- Load Combo tình trạng bảng giá (ANGEL) 
---- EXEC CP0036 @DivisionID = 'ANG'
-- <Param>

CREATE PROCEDURE [dbo].[CP0036] 
		@DivisionID NVARCHAR(50)			
AS
DECLARE @sSQL NVARCHAR(MAX)

SET @sSQL = N'
SELECT 0 AS Status, N''Chưa chấp nhận'' AS LanguageID
UNION ALL
SELECT 1 AS Status, N''Chấp nhận'' AS LanguageID
'

PRINT @sSQL
EXEC (@sSQL)

GO
SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
             