IF EXISTS (SELECT TOP 1 1 FROM DBO.SYSOBJECTS WHERE ID = OBJECT_ID(N'[DBO].[CP0037]') AND  OBJECTPROPERTY(ID, N'IsProcedure') = 1)			
DROP PROCEDURE [DBO].[CP0037]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


-- <Summary>
---- Load Combo đổ dữ liệu cho combo duyệt bảng giá (ANGEL) 
---- EXEC CP0037 @DivisionID = 'ANG'
-- <Param>

CREATE PROCEDURE [dbo].[CP0037] 
		@DivisionID NVARCHAR(50)			
AS
DECLARE @sSQL NVARCHAR(MAX)

SET @sSQL = N'
SELECT 1 AS ID, N''Duyệt bảng giá 1 cấp'' AS Name
UNION ALL
SELECT 2 AS ID, N''Duyệt bảng giá 2 cấp'' AS Name
'

PRINT @sSQL
EXEC (@sSQL)

GO
SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
             