---- Create by Le Hoang on 24/11/2020
---- Bảng thiet lap loai chung tu mac dinh

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[QCT0000]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[QCT0000](
	APK UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
	DivisionID VARCHAR(50) NOT NULL,
	VoucherFirstShift VARCHAR(50) NULL,
	VoucherQuantity VARCHAR(50) NULL,
	VoucherOperateParam VARCHAR(50) NULL,
	VoucherTechniqueParam VARCHAR(50) NULL,
	VoucherMaterial VARCHAR(50) NULL,
	VoucherDefective VARCHAR(50) NULL,
	CreateUserID VARCHAR(50) NULL,
	CreateDate DATETIME NULL DEFAULT GETDATE(),
	LastModifyUserID VARCHAR(50) NULL,
	LastModifyDate DATETIME NULL DEFAULT GETDATE()
 CONSTRAINT [PK_QCT0000] PRIMARY KEY CLUSTERED 
(
	[APK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
