---- Create by Le Hoang on 07/11/2020
---- Bảng dữ liệu Cấu hình 

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[QCT1010]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[QCT1010](
	[APK] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
	[ComputerName] NVARCHAR(50) NULL,
	[DeviceID] NVARCHAR(50) NULL,
	[PortName] NVARCHAR(50) NULL,
	[BaudRate] INT NULL,
	[Parity] VARCHAR(50) NULL,
	[DataBits] INT NULL,
	[StopBits] FLOAT NULL,
	[ReceivedValue] DECIMAL(28,8) NULL
 CONSTRAINT [PK_QCT1010] PRIMARY KEY CLUSTERED 
(
	[APK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END