---- Create by Trương Ngọc Phương Thảo on 8/18/2017 2:19:40 PM
---- Thiết lập bước sản xuất

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[OT0167]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[OT0167]
(
  [DivisionID] NVARCHAR(50) NOT NULL,
  [StepID] NVARCHAR(50) NOT NULL,
  [StepName] NVARCHAR(50) NULL,    
  [Disabled] TINYINT DEFAULT (0) NULL,
  [CreateUserID] NVARCHAR(50) NULL,
  [CreateDate] DATETIME NULL,
  [LastModifyUserID] NVARCHAR(50) NULL,
  [LastModifyDate] DATETIME NULL
CONSTRAINT [PK_OT0167] PRIMARY KEY CLUSTERED
(
  [DivisionID],
  [StepID]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END