IF EXISTS (SELECT TOP 1 1 FROM DBO.SYSOBJECTS WHERE ID = OBJECT_ID(N'[DBO].[HX1403]') AND OBJECTPROPERTY(ID, N'IsTrigger') = 1)
DROP TRIGGER [DBO].[HX1403]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
----- Thêm vào HT1403_CT khi Xóa thông tin hồ sơ nhân viên
----- Created by Bảo Thy, Date 16/03/2016


CREATE TRIGGER HX1403 ON HT1403
FOR DELETE
AS

IF EXISTS (SELECT TOP 1 1 FROM DELETED)
 insert into [HT1403_CT]([Operation], 
	[APK] ,
	[DivisionID] ,
	[EmployeeID],
	[SalaryCoefficient],
	[DutyCoefficient] ,
	[TimeCoefficient],
	[DepartmentID],
	[TeamID],
	[DutyID],
	[TaxObjectID],
	[EmployeeStatus],
	[Experience],
	[SuggestSalary],
	[RecruitDate],
	[RecruitPlace],
	workdate,
	[C01] ,
	[C02] ,
	[C03] ,
	[C04] ,
	[C05],
	[C06] ,
	[C07] ,
	[C08] ,
	[C09] ,
	[C10] ,
	[BaseSalary] ,
	[InsuranceSalary],
	[Salary01] ,
	[Salary02] ,
	[Salary03],
	[Target01ID],
	[Target02ID] ,
	[Target03ID] ,
	[Target04ID],
	[Target05ID],
	[Target06ID],
	[Target07ID],
	[Target08ID] ,
	[Target09ID] ,
	[Target10ID] ,
	[TargetAmount01] ,
	[TargetAmount02] ,
	[TargetAmount03] ,
	[TargetAmount04],
	[TargetAmount05] ,
	[TargetAmount06] ,
	[TargetAmount07] ,
	[TargetAmount08] ,
	[TargetAmount09] ,
	[TargetAmount10],
	[LeaveDate],
	[LoaCondID],
	[IsOtherDayPerMonth],
	[FileID],
	[ApplyDate],
	[BeginProbationDate],
	[EndProbationDate],
	[ProbationNote],
	[QuitJobID],
	[C11] ,
	[C12] ,
	[C13],
	[ExpenseAccountID],
	[PayableAccountID],
	[PerInTaxID],
	[C14] ,
	[C15] ,
	[C16] ,
	[C17] ,
	[C18] ,
	[C19] ,
	[C20] ,
	[C21] ,
	[C22] ,
	[C23] ,
	[C24] ,
	[C25],
	[CompanyDate],
	[IsJobWage],
	[IsPiecework],
	[TitleID],
	[SalaryLevel] ,
	[SalaryLevelDate],
	[MidEmployeeID],
	[LeaveToDate],
	[Notes],
	[IsManager],
	[CreateDate],
	[CreateUserID],
	[LastModifyDate],
	[LastModifyUserID],
	[ReAPK])  
	SELECT 1 AS [Operation], 
	[APK] ,
	[DivisionID] ,
	[EmployeeID],
	[SalaryCoefficient],
	[DutyCoefficient] ,
	[TimeCoefficient],
	[DepartmentID],
	[TeamID],
	[DutyID],
	[TaxObjectID],
	[EmployeeStatus],
	[Experience],
	[SuggestSalary],
	[RecruitDate],
	[RecruitPlace],
	workdate,
	[C01] ,
	[C02] ,
	[C03] ,
	[C04] ,
	[C05],
	[C06] ,
	[C07] ,
	[C08] ,
	[C09] ,
	[C10] ,
	[BaseSalary] ,
	[InsuranceSalary],
	[Salary01] ,
	[Salary02] ,
	[Salary03],
	[Target01ID],
	[Target02ID] ,
	[Target03ID] ,
	[Target04ID],
	[Target05ID],
	[Target06ID],
	[Target07ID],
	[Target08ID] ,
	[Target09ID] ,
	[Target10ID] ,
	[TargetAmount01] ,
	[TargetAmount02] ,
	[TargetAmount03] ,
	[TargetAmount04],
	[TargetAmount05] ,
	[TargetAmount06] ,
	[TargetAmount07] ,
	[TargetAmount08] ,
	[TargetAmount09] ,
	[TargetAmount10],
	[LeaveDate],
	[LoaCondID],
	[IsOtherDayPerMonth],
	[FileID],
	[ApplyDate],
	[BeginProbationDate],
	[EndProbationDate],
	[ProbationNote],
	[QuitJobID],
	[C11] ,
	[C12] ,
	[C13],
	[ExpenseAccountID],
	[PayableAccountID],
	[PerInTaxID],
	[C14] ,
	[C15] ,
	[C16] ,
	[C17] ,
	[C18] ,
	[C19] ,
	[C20] ,
	[C21] ,
	[C22] ,
	[C23] ,
	[C24] ,
	[C25],
	[CompanyDate],
	[IsJobWage],
	[IsPiecework],
	[TitleID],
	[SalaryLevel] ,
	[SalaryLevelDate],
	[MidEmployeeID],
	[LeaveToDate],
	[Notes],
	[IsManager],
	[CreateDate],
	[CreateUserID],
	GETDATE(),
	[LastModifyUserID],
	[ReAPK]  FROM deleted
      
GO
SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
