IF EXISTS (SELECT TOP 1 1 FROM DBO.SYSOBJECTS WHERE ID = OBJECT_ID(N'[DBO].[HX1400]') AND OBJECTPROPERTY(ID, N'IsTrigger') = 1)
DROP TRIGGER [DBO].[HX1400]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
----- Thêm vào HT1400_CT khi Xóa thông tin hồ sơ nhân viên
----- Created by Bảo Thy, Date 16/03/2016


CREATE TRIGGER HX1400 ON HT1400 
FOR DELETE
AS

IF EXISTS (SELECT TOP 1 1 FROM DELETED) AND (SELECT CustomerName FROM CustomerIndex) = 50 ---Customize MEIKO
 INSERT INTO [HT1400_CT]
		(Operation, [APK]
      ,[DivisionID]
      ,[EmployeeID]
      ,[Orders]
      ,[DepartmentID]
      ,[TeamID]
      ,[LastName]
      ,[MiddleName]
      ,[FirstName]
      ,[ShortName]
      ,[Alias]
      ,[Birthday]
      ,[BornPlace]
      ,[IsMale]
      ,[NativeCountry]
      ,[PermanentAddress]
      ,[TemporaryAddress]
      ,[PassportNo]
      ,[PassportDate]
      ,[PassportEnd]
      ,[IdentifyCardNo]
      ,[IdentifyDate]
      ,[IdentifyPlace]
      ,[IsSingle]
      --,[ImageID]
      ,[CountryID]
      ,[CityID]
      ,[DistrictID]
      ,[EthnicID]
      ,[ReligionID]
      ,[Notes]
      ,[HealthStatus]
      ,[HomePhone]
      ,[HomeFax]
      ,[MobiPhone]
      ,[Email]
      ,[CreateDate]
      ,[CreateUserID]
      ,[LastModifyDate]
      ,[LastModifyUserID]
      ,[S1]
      ,[S2]
      ,[S3]
      ,[EmployeeStatus]
      ,[IsForeigner]
      ,[RecruitTimeID]
      ,[IdentifyCityID]
      ,[NoResident]
      ,[DrivingLicenceNo]
      ,[DrivingLicenceDate]
      ,[DrivingLicenceEnd]
      ,[DrivingLicencePlace]
      ,[IdentifyEnd]
      ,[Ana01ID]
      ,[Ana02ID]
      ,[Ana03ID]
      ,[Ana04ID]
      ,[Ana05ID]
      ,[Ana06ID]
      ,[Ana07ID]
      ,[Ana08ID]
      ,[Ana09ID]
      ,[Ana10ID]
      ,[IsAutoCreateUser],ReAPK)  
     SELECT 1 AS Operation, [APK]
      ,[DivisionID]
      ,[EmployeeID]
      ,[Orders]
      ,[DepartmentID]
      ,[TeamID]
      ,[LastName]
      ,[MiddleName]
      ,[FirstName]
      ,[ShortName]
      ,[Alias]
      ,[Birthday]
      ,[BornPlace]
      ,[IsMale]
      ,[NativeCountry]
      ,[PermanentAddress]
      ,[TemporaryAddress]
      ,[PassportNo]
      ,[PassportDate]
      ,[PassportEnd]
      ,[IdentifyCardNo]
      ,[IdentifyDate]
      ,[IdentifyPlace]
      ,[IsSingle]
      --,[ImageID]
      ,[CountryID]
      ,[CityID]
      ,[DistrictID]
      ,[EthnicID]
      ,[ReligionID]
      ,[Notes]
      ,[HealthStatus]
      ,[HomePhone]
      ,[HomeFax]
      ,[MobiPhone]
      ,[Email]
      ,[CreateDate]
      ,[CreateUserID]
      ,GETDATE()
      ,[LastModifyUserID]
      ,[S1]
      ,[S2]
      ,[S3]
      ,[EmployeeStatus]
      ,[IsForeigner]
      ,[RecruitTimeID]
      ,[IdentifyCityID]
      ,[NoResident]
      ,[DrivingLicenceNo]
      ,[DrivingLicenceDate]
      ,[DrivingLicenceEnd]
      ,[DrivingLicencePlace]
      ,[IdentifyEnd]
      ,[Ana01ID]
      ,[Ana02ID]
      ,[Ana03ID]
      ,[Ana04ID]
      ,[Ana05ID]
      ,[Ana06ID]
      ,[Ana07ID]
      ,[Ana08ID]
      ,[Ana09ID]
      ,[Ana10ID]
      ,[IsAutoCreateUser],ReAPK  FROM DELETED
     
GO
SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
