IF EXISTS (SELECT TOP 1 1 FROM DBO.SYSOBJECTS WHERE ID = OBJECT_ID(N'[DBO].[HZ1401]') AND OBJECTPROPERTY(ID, N'IsTrigger') = 1)
DROP TRIGGER [DBO].[HZ1401]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
----- Thêm vào HT1401_CT khi update thông tin hồ sơ nhân viên
----- Created by Bảo Thy, Date 16/03/2016


CREATE TRIGGER HZ1401 ON HT1401
FOR UPDATE
AS

IF EXISTS (SELECT TOP 1 1 FROM INSERTED)
BEGIN
	IF EXISTS (SELECT TOP 1 1 FROM DELETED)
		insert into [HT1401_CT]
               ([Operation],
				[APK],
				[DivisionID],
				[EmployeeID] ,
				[FatherName],
				[FatherYear],
				[FatherJob],
				[FatherAddress],
				[FatherNote],
				[IsFatherDeath],
				[MotherName],
				[MotherYear],
				[MotherJob],
				[MotherAddress],
				[MotherNote],
				[IsMotherDeath],
				[SpouseName],
				[SpouseYear],
				[SpouseAddress],
				[SpouseNote],
				[SpouseJob],
				[IsSpouseDeath],
				[EducationLevelID],
				[PoliticsID],
				[Language1ID],
				[Language2ID],
				[Language3ID],
				[LanguageLevel1ID],
				[LanguageLevel2ID],
				[LanguageLevel3ID],
				[CreateDate],
				[CreateUserID],
				[LastModifyDate],
				[LastModifyUserID],
				[ReAPK])
		 SELECT 4 as [Operation],
				[APK],
				[DivisionID],
				[EmployeeID] ,
				[FatherName],
				[FatherYear],
				[FatherJob],
				[FatherAddress],
				[FatherNote],
				[IsFatherDeath],
				[MotherName],
				[MotherYear],
				[MotherJob],
				[MotherAddress],
				[MotherNote],
				[IsMotherDeath],
				[SpouseName],
				[SpouseYear],
				[SpouseAddress],
				[SpouseNote],
				[SpouseJob],
				[IsSpouseDeath],
				[EducationLevelID],
				[PoliticsID],
				[Language1ID],
				[Language2ID],
				[Language3ID],
				[LanguageLevel1ID],
				[LanguageLevel2ID],
				[LanguageLevel3ID],
				[CreateDate],
				[CreateUserID],
				GETDATE(),
				[LastModifyUserID],
				[ReAPK]  FROM INSERTED
				
		insert into [HT1401_CT]
               ([Operation],
				[APK],
				[DivisionID],
				[EmployeeID] ,
				[FatherName],
				[FatherYear],
				[FatherJob],
				[FatherAddress],
				[FatherNote],
				[IsFatherDeath],
				[MotherName],
				[MotherYear],
				[MotherJob],
				[MotherAddress],
				[MotherNote],
				[IsMotherDeath],
				[SpouseName],
				[SpouseYear],
				[SpouseAddress],
				[SpouseNote],
				[SpouseJob],
				[IsSpouseDeath],
				[EducationLevelID],
				[PoliticsID],
				[Language1ID],
				[Language2ID],
				[Language3ID],
				[LanguageLevel1ID],
				[LanguageLevel2ID],
				[LanguageLevel3ID],
				[CreateDate],
				[CreateUserID],
				[LastModifyDate],
				[LastModifyUserID],
				[ReAPK])
		 SELECT 3 as [Operation],
				[APK],
				[DivisionID],
				[EmployeeID] ,
				[FatherName],
				[FatherYear],
				[FatherJob],
				[FatherAddress],
				[FatherNote],
				[IsFatherDeath],
				[MotherName],
				[MotherYear],
				[MotherJob],
				[MotherAddress],
				[MotherNote],
				[IsMotherDeath],
				[SpouseName],
				[SpouseYear],
				[SpouseAddress],
				[SpouseNote],
				[SpouseJob],
				[IsSpouseDeath],
				[EducationLevelID],
				[PoliticsID],
				[Language1ID],
				[Language2ID],
				[Language3ID],
				[LanguageLevel1ID],
				[LanguageLevel2ID],
				[LanguageLevel3ID],
				[CreateDate],
				[CreateUserID],
				GETDATE(),
				[LastModifyUserID],
				[ReAPK]  FROM DELETED
   END   
GO
SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
