IF EXISTS (SELECT TOP 1 1 FROM DBO.SYSOBJECTS WHERE ID = OBJECT_ID(N'[DBO].[AV0026]') AND OBJECTPROPERTY(ID, N'IsView') = 1)
DROP VIEW [DBO].[AV0026]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW AV0026
AS

SELECT PriceID, '' InventoryID, StandardID, UnitPrice
FROM OT1300

UNION ALL

SELECT PriceID, InventoryID, StandardID, UnitPrice
FROM AT0135
WHERE StandardID NOT IN
	(
		SELECT StandardID
		FROM OT1300
	)
GO
SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
