---- Create by Đoàn Duy on 10/02/2021
---- 1BOSS Danh mục gói sản phẩm/giải pháp cloud 1boss
IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[AT0016]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[AT0016]
(
  [APK] UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL,
  [DivisionID] VARCHAR(50) NOT NULL,
  [Disabled] TINYINT DEFAULT (0) NULL,
  [Description] NVARCHAR(MAX) NULL,
  [PackageID] NVARCHAR(50) NOT NULL, 
  [PackageName] NVARCHAR(MAX) NOT NULL, 
  [CreateDate] DateTime NULL,
  [DeleteFlg] TINYINT DEFAULT 0 NULL,
  [CreateUserID] VARCHAR(50) NULL,
  [LastModifyUserID] VARCHAR(50) NULL,
  [LastModifyDate] DATETIME NULL
CONSTRAINT [AT0016_PK] PRIMARY KEY CLUSTERED
(
  [PackageID]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END



