---- Create by Nguyễn Tấn Lộc on 4/9/2020 9:16:38 AM
---- Màn hình nhập liệu test

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[ADMT2011]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[ADMT2011]
(
  [APK] UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL,
  [APKMaster] UNIQUEIDENTIFIER NOT NULL,
  [DivisionID] VARCHAR(50) NULL,
  [TableID] VARCHAR(50) NULL,
  [ColumnID] VARCHAR(50) NULL,
  [ColumnName] NVARCHAR(250) NULL,
  [DataTypeID] VARCHAR(50) NULL,
  [DataTest] NVARCHAR(MAX) NULL,
  [TypeID] VARCHAR(50) NULL,
  [TypeInput] VARCHAR(50) NULL,
  [DeleteFlg] TINYINT DEFAULT 0 NULL,
  [RowNumber] INT NULL,
  [CreateDate] DATETIME NULL,
  [CreateUserID] VARCHAR(50) NULL,
  [LastModifyDate] DATETIME NULL,
  [LastModifyUserID] VARCHAR(50) NULL
CONSTRAINT [PK_ADMT2011] PRIMARY KEY CLUSTERED
(
  [APK]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END