---- Create by Khánh Đoan on 16/12/2019
---- Danh mục đưa đón Detail
IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[EDMT1111]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[EDMT1111]
(
  [APK] UNIQUEIDENTIFIER DEFAULT newid() NOT NULL,
  [APKMaster] VARCHAR(50) NOT NULL,
  [DivisionID] VARCHAR(50) NOT NULL,
  [StudentID] VARCHAR(50)  NULL,
  [CreateUserID] VARCHAR(50) NULL,
  [CreateDate] DATETIME NULL,
  [LastModifyUserID] VARCHAR(50) NULL,
  [LastModifyDate] DATETIME NULL

CONSTRAINT [PK_EDMT1111] PRIMARY KEY CLUSTERED
(
  [APK]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END

