-- Create by VanTinh on 20/10/2018
-- Phân công giáo viên - EDMF2030

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[EDMT2030]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[EDMT2030]
(
	[APK] UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL,
	[DivisionID] VARCHAR(50) NOT NULL,
	VoucherNo VARCHAR(50) NOT NULL,
	SchoolYearID VARCHAR(50) NULL,
	GradeID VARCHAR(50) NULL,
	ClassID VARCHAR(50) NULL,
	ApprovalID01 VARCHAR(50) NULL,
	ApprovalID02 VARCHAR(50) NULL,
	ApprovalID03 VARCHAR(50) NULL,
	ApprovalID04 VARCHAR(50) NULL,
	ApprovalID05 VARCHAR(50) NULL,
	CreateUserID VARCHAR(50) NULL,
	CreateDate DATETIME NULL,
	LastModifyUserID VARCHAR(50) NULL,
	LastModifyDate DATETIME NULL,
	DeleteFlg TINYINT DEFAULT(0) NULL,

CONSTRAINT [PK_EDMT2030] PRIMARY KEY CLUSTERED
(
  [APK], [DivisionID]
)
) ON [PRIMARY]

END
GO
