---- Create by Khánh Đoan on 15/01/2020
---- Nghiệp vụ Bảo lưu/ Chuyển nhượng

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[EDMT2152]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[EDMT2152]
(
  [APK] UNIQUEIDENTIFIER DEFAULT newid() NOT NULL,
  [DivisionID] VARCHAR(50) NOT NULL,
  [APKMaster] UNIQUEIDENTIFIER NOT NULL,    
  [VoucherNo] VARCHAR (50) NULL,
  [StudentID] VARCHAR(50) NULL,				--Học sinh bảo lưu
  [StudentIDReceiver] VARCHAR(50) NULL,	    -- Học sinh nhận bảo lưu 
  [DeleteFlg] TINYINT DEFAULT (0) NULL,
  [CreateUserID] VARCHAR(50) NULL,
  [CreateDate] DATETIME NULL,
  [LastModifyUserID] VARCHAR(50) NULL,
  [LastModifyDate] DATETIME NULL
CONSTRAINT [PK_EDMT2152] PRIMARY KEY CLUSTERED
(
  [APK],
  [DivisionID]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END
