---- Create by Khánh Đoan on 16/12/2019
---- Danh mục khuyến mãi

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[EDMT1100]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[EDMT1100]
(
  [APK] UNIQUEIDENTIFIER DEFAULT newid() NOT NULL,
  [DivisionID] VARCHAR(50) NOT NULL,
  [PromotionID] VARCHAR(50) NOT NULL,
  [PromotionName] NVARCHAR(250)  NULL,
  [PromotionType] NVARCHAR(50)  NULL,
  [Value] DECIMAL(28,8)NULL,
  [ReceiptTypeID] VARCHAR(50)  NULL,
  [Quantity] DECIMAL(28,8)  NULL,
  [FromDate] DATETIME  NULL,
  [ToDate] DATETIME NULL,
  [Description] NVARCHAR(250) NULL,
  [CreateUserID] VARCHAR(50) NULL,
  [CreateDate] DATETIME NULL,
  [LastModifyUserID] VARCHAR(50) NULL,
  [LastModifyDate] DATETIME NULL
CONSTRAINT [PK_EDMT1100] PRIMARY KEY CLUSTERED
(
  [DivisionID],
  [PromotionID]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END
