---- Create by Hồng Thảo on 25/08/2018
---- Danh mục loại hoạt động detail 

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[EDMT1061]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[EDMT1061]
(
  [APK] UNIQUEIDENTIFIER DEFAULT newid() NOT NULL,
  [DivisionID] VARCHAR(50) NOT NULL,
  [APKMaster] VARCHAR(50) NOT NULL,
  [ActivityID] VARCHAR(50) NOT NULL,
  [ActivityName] NVARCHAR(250) NULL,
  [Disabled] TINYINT DEFAULT (0) NULL
CONSTRAINT [PK_EDMT1061] PRIMARY KEY CLUSTERED
(
  [APK]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END


