---- Create by Khánh Đoan on 16/01/2020
---- Nghiệp vụ Thiết lập khoản phí đầu năm
IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[EDMT2210]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[EDMT2210]
(

  [APK] UNIQUEIDENTIFIER DEFAULT newid() NOT NULL,
  [DivisionID] VARCHAR(50) NOT NULL,
  [VoucherNo] VARCHAR(50) NOT NULL,
  [SchoolYearID] VARCHAR(50)  NULL,
  [GradeID]  VARCHAR(50)  NULL,
  [ClassID]  VARCHAR(50)  NULL,
  [StudentID] VARCHAR(50)  NULL,
  [FeeID]		 VARCHAR(50)  NULL,
  [DeleteFlg] TINYINT DEFAULT (0) NULL,
  [CreateUserID] VARCHAR(50) NULL,
  [CreateDate] DATETIME NULL,
  [LastModifyUserID] VARCHAR(50) NULL,
  [LastModifyDate] DATETIME NULL
CONSTRAINT [PK_EDMT2210] PRIMARY KEY CLUSTERED
(
  [DivisionID],
  [APK]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END

