-- Create by VanTinh on 20/10/2018
-- Điểm danh - EDMF2040

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[EDMT2040]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[EDMT2040]
(
	[APK] UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL,
	[DivisionID] VARCHAR(50) NOT NULL,
	VoucherNo VARCHAR(50) NOT NULL,
	AttendanceDate DATETIME NULL,
	SchoolYearID VARCHAR(50) NULL,
	GradeID VARCHAR(50) NULL,
	ClassID VARCHAR(50) NULL,
	CreateUserID VARCHAR(50) NULL,
	CreateDate DATETIME NULL,
	LastModifyUserID VARCHAR(50) NULL,
	LastModifyDate DATETIME NULL,
	DeleteFlg TINYINT DEFAULT(0) NULL,

CONSTRAINT [PK_EDMT2040] PRIMARY KEY CLUSTERED
(
  [APK], [DivisionID]
)
) ON [PRIMARY]

END
GO
