-- Create by VanTinh on 28/08/2018
-- Danh muc dinh muc - EDMF1010 - detail

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[EDMT1011]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[EDMT1011]
(
	[APK] UNIQUEIDENTIFIER DEFAULT newid() NOT NULL,
	[DivisionID] VARCHAR(50) NOT NULL,
	[LevelID] VARCHAR(50) NOT NULL,
	[Quantity] INT NULL,
	[APKMaster] UNIQUEIDENTIFIER NULL

CONSTRAINT [PK_EDMT1011] PRIMARY KEY CLUSTERED
(
  [APK]
)
) ON [PRIMARY]

END
GO

