---- Create by Nguyễn Thị Minh Hòa on 5/11/2018 2:29:31 PM
---- Nghiệp vụ Kết quả dự giờ
---- Select * from EDMT2060

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[EDMT2060]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE  [dbo].[EDMT2060]
(
  [APK] UNIQUEIDENTIFIER DEFAULT newid() NOT NULL,
  [DivisionID] VARCHAR(50) NOT NULL,
  [EvaluetionID] VARCHAR(50) NOT NULL,
  [EvaluetionDate] DATETIME NOT NULL,
  [SchoolYearID] VARCHAR(50) NOT NULL,
  [GradeID] VARCHAR(50) NOT NULL,
  [ClassID] VARCHAR(50) NOT NULL,
  [TeacherID] VARCHAR(50) NULL,
  [Time] DATETIME  NULL,
  [ResultID] VARCHAR(50)  NULL,
  [Content] NVARCHAR(500)  NULL,
  [DeleteFlg] TINYINT DEFAULT (0) NULL,
  [CreateUserID] VARCHAR(50) NULL,
  [CreateDate] DATETIME NULL,
  [LastModifyUserID] VARCHAR(50) NULL,
  [LastModifyDate] DATETIME NULL
CONSTRAINT [PK_EDMT2060] PRIMARY KEY CLUSTERED
(
  [APK],
  [DivisionID]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END



