-- Create by VanTinh on 20/10/2018
-- Phân công giáo viên - EDMF2030, lưu thông tin bảo mẫu

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[EDMT2032]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[EDMT2032]
(
	[APK] UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL,
	[DivisionID] VARCHAR(50) NOT NULL,
	[APKMaster] UNIQUEIDENTIFIER NOT NULL,
	NannyID VARCHAR(50) NULL,
	CreateUserID VARCHAR(50) NULL,
	CreateDate DATETIME NULL,
	LastModifyUserID VARCHAR(50) NULL,
	LastModifyDate DATETIME NULL,
	DeleteFlg TINYINT DEFAULT(0) NULL,

CONSTRAINT [PK_EDMT2032] PRIMARY KEY CLUSTERED
(
  [APK]
)
) ON [PRIMARY]

END
GO
