-- Create by VanTinh on 25/09/2018
-- Hồ sơ học sinh - EDMF2010 - Lưu điều tra tâm lý hoc sinh

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[EDMT2011]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].EDMT2011(
	[APK] UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL,
	[DivisionID] VARCHAR(50) NOT NULL,
	[APKMaster] UNIQUEIDENTIFIER NULL,
	[PsychologizeID] VARCHAR(50) NULL,
	[Answer] [nvarchar](500) NULL,
	DeleteFlg TINYINT DEFAULT(0) NULL,
	CreateUserID VARCHAR(50) NULL,
	CreateDate DATETIME NULL,
	LastModifyUserID VARCHAR(50) NULL,
	LastModifyDate DATETIME NULL,
CONSTRAINT [PK_EDMT2011] PRIMARY KEY CLUSTERED
(
  [APK]
)
) ON [PRIMARY]

END
GO
