---- Create by Khánh Đoan on 16/12/2019
---- Danh mục đưa đón

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[EDMT1110]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[EDMT1110]
(
  [APK] UNIQUEIDENTIFIER DEFAULT newid() NOT NULL,
  [DivisionID] VARCHAR(50) NOT NULL,
  [ShuttleID] VARCHAR(50) NOT NULL,
  [PickupPlace] NVARCHAR(250) NULL,
  [ArrivedPlace] NVARCHAR(250) NULL,
  [ReceiptTypeID] VARCHAR(50)  NULL,
  [Description] NVARCHAR(250) NULL,
  [PromotionID] VARCHAR(50)  NULL,
  [Disabled] TINYINT DEFAULT (0) NULL,
  [CreateUserID] VARCHAR(50) NULL,
  [CreateDate] DATETIME NULL,
  [LastModifyUserID] VARCHAR(50) NULL,
  [LastModifyDate] DATETIME NULL
CONSTRAINT [PK_EDMT1110] PRIMARY KEY CLUSTERED
(
  [DivisionID],
  [ShuttleID]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END
 

 



