-- Create by VanTinh on 16/11/2018
-- Điều chuyển giáo viên detail - EDMF2070

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[EDMT2071]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[EDMT2071]
(
	[APK] UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL,
	[DivisionID] VARCHAR(50) NOT NULL,
	[APKMaster] UNIQUEIDENTIFIER NULL,
	TeacherID VARCHAR(50) NULL,
	GradeIDFrom VARCHAR(50) NULL,
	ClassIDFrom VARCHAR(50) NULL,
	GradeIDTo VARCHAR(50) NULL,
	ClassIDTo VARCHAR(50) NULL,
	DateFrom DATETIME NULL,
	DateTo DATETIME NULL,
	Notes NVARCHAR(500),
	CreateUserID VARCHAR(50) NULL,
	CreateDate DATETIME NULL,
	LastModifyUserID VARCHAR(50) NULL,
	LastModifyDate DATETIME NULL,
	DeleteFlg TINYINT DEFAULT(0) NULL,

CONSTRAINT [PK_EDMT2071] PRIMARY KEY CLUSTERED
(
  [APK]
)
) ON [PRIMARY]

END
GO
