   ---- Create by Tra Giang on 16/08/2018 
---- Danh mục Định mức dinh dưỡng( detail)

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[NMT1031]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[NMT1031]
(
  [APK] UNIQUEIDENTIFIER DEFAULT newid() NOT NULL,
  [DivisionID] VARCHAR(50) NOT NULL,
  [APKMaster] UNIQUEIDENTIFIER  NOT NULL,  

  [SystemID] NVARCHAR(50) NOT NULL,
  [QuotaStandard] DECIMAL(28,8) NOT NULL,
  [MinRatio] DECIMAL(28,8)  NULL,
  [MaxRatio] DECIMAL(28,8) NULL,

  [CreateUserID] VARCHAR(50) NULL,
  [CreateDate] DATETIME NULL,
  [LastModifyUserID] VARCHAR(50) NULL,
  [LastModifyDate] DATETIME NULL
CONSTRAINT [PK_NMT1031] PRIMARY KEY CLUSTERED
(
  [APK] ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END



  