---- Create by Tra Giang on 15/08/2018 
---- Danh mục thực phẩm ( master)

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[NMT1010]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[NMT1010]
(
  [APK] UNIQUEIDENTIFIER DEFAULT newid() NOT NULL,
  [DivisionID] VARCHAR(50) NOT NULL,

  [MaterialsID] VARCHAR(50) NULL,
  [MaterialsTypeID] VARCHAR(50) NOT NULL,
  [Description]  NVARCHAR(250) NULL,
   [Disabled]  TINYINT NULL,

  [CreateUserID] VARCHAR(50) NULL,
  [CreateDate] DATETIME NULL,
  [LastModifyUserID] VARCHAR(50) NULL,
  [LastModifyDate] DATETIME NULL

CONSTRAINT [PK_NMT1010] PRIMARY KEY CLUSTERED
(
  [APK] ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END




  