---- Create by Tra Giang on 16/08/2018 
---- Nghiệp Vụ: Thực đơn tổng( master)

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[NMT2000]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[NMT2000]
(
  [APK] UNIQUEIDENTIFIER DEFAULT newid() NOT NULL,
  [DivisionID] VARCHAR(50) NOT NULL,

  [VoucherNo] VARCHAR(50) NOT NULL,
  [VoucherDate] DATETIME NOT NULL,
  [TranMonth] INT NOT NULL,
  [TranYear] INT NOT NULL,
  [MenuTypeID] VARCHAR(50) NOT NULL,
  [BeginDate] DATETIME NOT NULL,
  [FinishDate] DATETIME NOT NULL,
  [Description] NVARCHAR(250) NOT NULL,
  [DeleteFlg] TINYINT NOT NULL Default 0,
	  
  [CreateUserID] VARCHAR(50) NULL,
  [CreateDate] DATETIME NULL,
  [LastModifyUserID] VARCHAR(50) NULL,
  [LastModifyDate] DATETIME NULL
CONSTRAINT [PK_NMT2000] PRIMARY KEY CLUSTERED
(
  [APK] ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END


