---- Create by Tra Giang on 16/08/2018 
---- Nghiệp Vụ: Phiêu kê chợ ( detail:  chi tiết thực phẩm)

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[NMT2022]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[NMT2022]
(
  [APK] UNIQUEIDENTIFIER DEFAULT newid() NOT NULL,
  [APKMaster] UNIQUEIDENTIFIER NOT NULL,
  [DivisionID] VARCHAR(50) NOT NULL,

  [MenuName] NVARCHAR(50) NOT NULL,
  [MaterialsID] VARCHAR(50) NOT NULL,
  [ActualQuantity] DECIMAL(28,8) NOT NULL, 
   [UnitID] VARCHAR(50) NOT NULL,
 
    [TranMonth] int NOT NULL,
  [TranYear] int NOT NULL, 
  [CreateUserID] VARCHAR(50) NULL,
  [CreateDate] DATETIME NULL,
  [LastModifyUserID] VARCHAR(50) NULL,
  [LastModifyDate] DATETIME NULL
CONSTRAINT [PK_NMT2022] PRIMARY KEY CLUSTERED
(
  [APK] ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END





  