---- Create by Tra Giang on 16/08/2018 
---- Nghiệp Vụ: Tiếp phẩm 3 bước ( detail: Bước 1A )
IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[NMT2052]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[NMT2052]
(
		  [APK] UNIQUEIDENTIFIER DEFAULT newid() NOT NULL,
		  [APKMaster] UNIQUEIDENTIFIER NOT NULL,
		  [DivisionID] VARCHAR(50) NOT NULL,
		 
		  [VoucherDate] DATETIME NOT NULL,
		  [MaterialsID] VARCHAR(50) NOT NULL,
		  [ActualQuantity] DECIMAL(28,8) NOT NULL,
		 [SupplierID] VARCHAR(50) NOT NULL,		
		 [VoucherNo] VARCHAR(50) NOT NULL,
		 [QuarantineVoucherNo] VARCHAR(50) NOT NULL,
		 [PackagingType] NVARCHAR(50) NOT NULL,
		 [Feel] TINYINT NOT NULL,
		 [ResultsTest] TINYINT NOT NULL,

		 [InheritAPK] UNIQUEIDENTIFIER NULL,
		 [InheritAPKMaster] UNIQUEIDENTIFIER NULL,
		 [InheritTableID] VARCHAR(50) NULL,  
		 [TranMonth] INT NOT NULL,
         [TranYear] INT NOT NULL,
		 [DeleteFlg] TINYINT NOT NULL Default 0,
		 [CreateUserID] VARCHAR(50) NULL,
         [CreateDate] DATETIME NULL,
		 [LastModifyUserID] VARCHAR(50) NULL,
		 [LastModifyDate] DATETIME NULL

CONSTRAINT [PK_NMT2052] PRIMARY KEY CLUSTERED
(
  [APK] ASC 
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END
 


