---- Create by Tra Giang on 16/08/2018 
---- Nghiệp Vụ: Thực đơn ngày( detail: thực phẩm)

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[NMT2013]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[NMT2013]
(
  [APK] UNIQUEIDENTIFIER DEFAULT newid() NOT NULL,
  [APKMaster] UNIQUEIDENTIFIER NOT NULL,
  [DivisionID] VARCHAR(50) NOT NULL,
   
   [MaterialsID] VARCHAR(50)NOT NULL,
   [UnitID] VARCHAR(50) NOT NULL,
   [ActualQuantity] DECIMAL(28,8) NOT NULL,
   [ConvetedQuantity] DECIMAL(28,8) NULL,
   [UnitPrice] DECIMAL(28,8) NOT NULL,
   [Amount] DECIMAL(28,8) NOT NULL,

   [DeleteFlg] TINYINT Default 0 NOT NULL ,
   [TranMonth] INT NOT NULL,
   [TranYear] INT NOT NULL,
   [CreateUserID] VARCHAR(50) NULL,
   [CreateDate] DATETIME NULL,
   [LastModifyUserID] VARCHAR(50) NULL,
   [LastModifyDate] DATETIME NULL
CONSTRAINT [PK_NMT2013] PRIMARY KEY CLUSTERED
(
  [APK] ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END





  