---- Create by Tra Giang on 16/08/2018 
---- Nghiệp Vụ: Thực đơn tổng( detail: thông tin món ăn của bữa ăn)

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[NMT2001]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[NMT2001]
(
  [APK] UNIQUEIDENTIFIER DEFAULT newid() NOT NULL,
  [APKMaster] UNIQUEIDENTIFIER NOT NULL,
  [DivisionID] VARCHAR(50) NOT NULL,

  [Week] INT NOT NULL,
  [Day] INT NOT NULL,
  [MealID] VARCHAR(50) NOT NULL, 
  [DishID] VARCHAR(50) NULL,
  [DeleteFlg] TINYINT NOT NULL Default 0,
  [TranMonth] INT NOT NULL,
  [TranYear] INT NOT NULL,

  [CreateUserID] VARCHAR(50) NULL,
  [CreateDate] DATETIME NULL,
  [LastModifyUserID] VARCHAR(50) NULL,							
  [LastModifyDate] DATETIME NULL
CONSTRAINT [PK_NMT2001] PRIMARY KEY CLUSTERED
(
  [APK] ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END


